### ISSUE TITLE
Traefik+EKS+NLB+target type - ip

### ISSUE THREAD

**Issue by OlegSupport** [traefik/traefik-helm-chart#1005]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

26.0.0

### What version of Traefik are you using?

2.10.7

### What did you do?

We created traefik ingress controller in EKS 1.28. It works in pair with internal NLB which has target group type - "instance". 
It works correctly, but we have some random issues with latency and random timeouts on our ingress. Issues we are seeing just only on http part, https works perfect

### What did you see instead?

After many hours of search in google, we just found solution to change target group type on "ip" instead of "instance". But all tries of doing that were unsuccessful

### What is your environment & configuration?

Configuration for internal traefik that we have now:
```
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
```
 Configuration that we try to add, for change  target group type:

  ```
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```

So, after manipulations with "ip", we just saw service traefik in EKS in pending state and no any changes in loadbalancers in AWS console. And, i tried to add various traefik annotations - but no any of them works. 
Any ideas how to create internal NLB with target group type "ip" ?
