### ISSUE TITLE
helm traefik does not watch all namespaces when rbac namespaced

### ISSUE THREAD

**Issue by oleg-andreyev** [traefik/traefik-helm-chart#1011]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

3.14.2

### What version of Traefik are you using?

2.11.0

### What did you do?

Following documentation and default Chart values, it is stated that traefik will watch all namespaces, but it's not

https://github.com/traefik/traefik-helm-chart/blob/ba5918d221d9a6eb52384f945dbaf31dfe41b384/traefik/values.yaml#L237-L239

If `providers.kubernetesCRD.namespaces` is not defined, helm will use default traefik namespace.
if `providers.kubernetesCRD.namespaces` is defined as. empty array, same result as above.

### What did you see instead?

![image](https://github.com/traefik/traefik-helm-chart/assets/1244112/39681cd7-7c7c-45cf-b866-55122105f95b)

Expected
![image](https://github.com/traefik/traefik-helm-chart/assets/1244112/f5332055-0258-43a5-8ad7-80a7b35b5437)

### What is your environment & configuration?

```yaml
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

namespaceOverride: traefik

rbac:
  namespaced: true

deployment:
  replicas: null
  kind: Deployment
  name: traefik
  revisionHistoryLimit: 1

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"

#autoscaling:
#  enabled: true
#  maxReplicas: 2
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 80

service:
  spec:
    loadBalancerIP: "<public-ip>"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <group>

logs:
  general:
    level: DEBUG
  access:
    enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    namespaces: ['default', 'traefik', 'mktrade']

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/24
        - 172.16.0.0/20
        - 192.168.0.0/16
```
