### ISSUE TITLE
Error indexing on bool value

### ISSUE THREAD

**Issue by sbanoeon** [traefik/traefik-helm-chart#1033]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

27.0.0

### What version of Traefik are you using?

2.11.1

### What did you do?

Deployed traefik using helm chart with the default values

### What did you see instead?

Error: INSTALLATION FAILED: template: traefik/templates/service.yaml:27:12: executing "traefik/templates/service.yaml" at <index (default dict $config.expose) $name>: error calling index: can't index item of type bool

### What is your environment & configuration?

helm version: 3.13.3

**Comment by mloiseleur** [comment]
Default install is [tested](https://github.com/traefik/traefik-helm-chart/actions/runs/8551975087/job/23432125393) on each release. 

Are you sure it's with _default_ values ? Would you please share with us the complete helm install command used ?

**Comment by cmersinli** [comment]
i have same issue while upgrading on rancher

**Comment by call286** [comment]
Check your values.yaml. I had the same error message, because i didn't update the values.yaml to the new schema.
Check your `ports:` section for entries like `expose: true`
Change them to
```yml
expose:
  default: true
```
To be clearer, my `ports:` section before (broken):
```yml
ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    tls:
      enabled: true
  redis:
    port: 6379
    expose: true
```
and after (fixed):
```yml

ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    tls:
      enabled: true
  redis:
    port: 6379
    expose:
      default: true
```
