### ISSUE TITLE
Traefik helm chart upgrade failed - UPGRADE FAILED: template: traefik/templates/service.yaml:27:12

### ISSUE THREAD

**Issue by donnaran** [traefik/traefik-helm-chart#1036]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v3.14

### What version of Traefik are you using?

2.10.6

### What did you do?

Trying to upgrade the traefik  to latest with below command but failed

helm repo update
helm upgrade --install traefik traefik/traefik -f config-values.yml -n traefik

or 
helm repo update
helm upgrade --install traefik traefik/traefik  -n traefik

### What did you see instead?

getting error:
`Error: UPGRADE FAILED: template: traefik/templates/service.yaml:27:12: executing "traefik/templates/service.yaml" at <index (default dict $config.expose) $name>: error calling index: can't index item of type bool`

### What is your environment & configuration?

k3s

**Comment by mloiseleur** [comment]
Did you upgrade your values following [upgrade notes](https://github.com/traefik/traefik-helm-chart/releases/tag/v27.0.0) ?

**Comment by iamdnaran** [comment]
> Did you upgrade your values following [upgrade notes](https://github.com/traefik/traefik-helm-chart/releases/tag/v27.0.0) ?

Thank you for pointing out the release notes.
I have changed the values ias per release notes now i am getting below error when try to do the upgrade.

Error: UPGRADE FAILED: cannot patch "traefik" with kind Service: Service "traefik" is invalid: spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive && cannot patch "traefik" with kind Deployment: Deployment.apps "traefik" is invalid: spec.template.spec.containers[0].ports[1].containerPort: Required value


Following are my values in config yaml.

deployment:
  # -- Enable deployment
  enabled: true
  # -- Deployment or DaemonSet
  kind: Deployment
  # -- Number of pods of the deployment (only applies when kind == Deployment)
  replicas: 2
# Enable access log
logs:
  #general:
  # level: WARN
  access:
    enabled: true
    format: json
    filePath: "/var/log/traefik/access.log"
# Print access log to file instead of stdout
additionalArguments:
  - "--accesslog.filepath=/data/access.log"
  - "--serversTransport.insecureSkipVerify=true"
ports:
  tcp-dns:
    expose:
      default: true
      port: 53
      exposePort: 53
      protocol: TCP
  udp-dns:
    expose:
      default: true
      port: 53
      exposePort:  53
      protocol: UDP
  smtp:
    expose:
      port: 25
      default: true
      exposePort: 25
      protocol: TCP
  postgres:
    explose:
      port: 5432
      default: true
      exposePort: 5432
      protocol: TCP
  mqtt:
    expose:
      port: 1883
      default: true
      exposePort: 1883
      protocol: TCP
service:
  single: false
  annotations:
    metallb.universe.tf/allow-shared-ip: traefik-external-service
  spec:
    loadBalancerIP: 10.10.10.10
    externalTrafficPolicy: Local
providers:
  # Enable cross namespace references
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  # Enable published service
  kubernetesIngress:
    publishedService:
      enabled: true
    allowExternalNameServices: true

**Comment by donnaran** [comment]
> Did you upgrade your values following [upgrade notes](https://github.com/traefik/traefik-helm-chart/releases/tag/v27.0.0) ?

Thank you for pointing out the release notes.
I have changed the values ias per release notes now i am getting below error when try to do the upgrade.

Error: UPGRADE FAILED: cannot patch "traefik" with kind Service: Service "traefik" is invalid: spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive && cannot patch "traefik" with kind Deployment: Deployment.apps "traefik" is invalid: spec.template.spec.containers[0].ports[1].containerPort: Required value


Following are my values in config yaml.

> 

deployment:
  # -- Enable deployment
  enabled: true
  # -- Deployment or DaemonSet
  kind: Deployment
  # -- Number of pods of the deployment (only applies when kind == Deployment)
  replicas: 2
# Enable access log
logs:
  #general:
  # level: WARN
  access:
    enabled: true
    format: json
    filePath: "/var/log/traefik/access.log"
# Print access log to file instead of stdout
additionalArguments:
  - "--accesslog.filepath=/data/access.log"
  - "--serversTransport.insecureSkipVerify=true"
ports:
  tcp-dns:
    expose:
      default: true
      port: 53
      exposePort: 53
      protocol: TCP
  udp-dns:
    expose:
      default: true
      port: 53
      exposePort:  53
      protocol: UDP
  smtp:
    expose:
      port: 25
      default: true
      exposePort: 25
      protocol: TCP
  postgres:
    explose:
      port: 5432
      default: true
      exposePort: 5432
      protocol: TCP
  mqtt:
    expose:
      port: 1883
      default: true
      exposePort: 1883
      protocol: TCP
service:
  single: false
  annotations:
    metallb.universe.tf/allow-shared-ip: traefik-external-service
  spec:
    loadBalancerIP: 10.10.10.10
    externalTrafficPolicy: Local
providers:
  # Enable cross namespace references
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  # Enable published service
  kubernetesIngress:
    publishedService:
      enabled: true
    allowExternalNameServices: true

>

**Comment by donnaran** [comment]
> Did you upgrade your values following [upgrade notes](https://github.com/traefik/traefik-helm-chart/releases/tag/v27.0.0) ?

Thank you for pointing out the release notes. I have updated the values as per release notes but now i am getting below error when trying to do the upgrade.

Error: UPGRADE FAILED: cannot patch "traefik" with kind Service: Service "traefik" is invalid: spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive && cannot patch "traefik" with kind Deployment: Deployment.apps "traefik" is invalid: spec.template.spec.containers[0].ports[1].containerPort: Required value

Following is in my config values yaml

```
deployment:
  # -- Enable deployment
  enabled: true
  # -- Deployment or DaemonSet
  kind: Deployment
  # -- Number of pods of the deployment (only applies when kind == Deployment)
  replicas: 2
# Enable access log
logs:
  #general:
  # level: WARN
  access:
    enabled: true
    format: json
    filePath: "/var/log/traefik/access.log"
# Print access log to file instead of stdout
additionalArguments:
  - "--accesslog.filepath=/data/access.log"
  - "--serversTransport.insecureSkipVerify=true"
ports:
  tcp-dns:
    expose:
      default: true
      port: 53
      exposePort: 54
      protocol: TCP
  udp-dns:
    expose:
      default: true
      port: 53
      exposePort:  53
      protocol: UDP
  smtp:
    expose:
      port: 25
      default: true
      exposePort: 25
      protocol: TCP
  postgres:
    expose:
      port: 5432
      default: true
      exposePort: 5432
      protocol: TCP
  wireguard:
    expose:
      port: 58210
      default: true
      exposePort: 58210
      protocol: UDP
  xd:
    expose:
      port: 448
      default: true
      exposePort: 448
      protocol: TCP
  mqtt:
    expose:
      port: 1883
      default: true
      exposePort: 1883
      protocol: TCP
service:
  single: false
  annotations:
    metallb.universe.tf/allow-shared-ip: traefik-external-service
  spec:
    # Set load balancer external IP
    loadBalancerIP: 10.10.10.10
    externalTrafficPolicy: Local
providers:
  # Enable cross namespace references
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  # Enable published service
  kubernetesIngress:
    publishedService:
      enabled: true
    allowExternalNameServices: true
nodeSelector:
  node-type: worker


```

**Comment by mloiseleur** [comment]
One can check what yaml is generated with `helm template` command.

This section is invalid:

```yaml
ports:
  tcp-dns:
    expose:
      default: true
      port: 53
      exposePort: 53
      protocol: TCP
```

With v27+, it should be

```yaml
ports:
  tcp-dns:
    expose:
      default: true
    port: 53
    exposedPort: 53
    protocol: TCP
```

As formatted in [default values](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L627).
