### ISSUE TITLE
Default values doesn't work on Azure due to missing podSecurityContext.fsGroup

### ISSUE THREAD

**Issue by mucsi96** [traefik/traefik-helm-chart#1070]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

28.0.0

### What version of Traefik are you using?

v3.0.0

### What did you do?

I deploy Traefik to AKS.

### What did you see instead?

In logs of volume-permissions (init) I see:
```bash
total 52
drwxr-xr-x    1 root     root          4096 May 22 06:08 .
drwxr-xr-x    1 root     root          4096 May 22 06:08 ..
drwxr-xr-x    2 root     root         12288 May 18  2023 bin
drwxr-xr-x    3 root     root          4096 May 22 06:00 data
drwxr-xr-x    5 root     root           360 May 22 06:08 dev
drwxr-xr-x    1 root     root          4096 May 22 06:08 etc
drwxr-xr-x    2 nobody   nobody        4096 May 18  2023 home
drwxr-xr-x    2 root     root          4096 May 18  2023 lib
lrwxrwxrwx    1 root     root             3 May 18  2023 lib64 -> lib
dr-xr-xr-x  262 root     root             0 May 22 06:08 proc
drwx------    2 root     root          4096 May 18  2023 root
dr-xr-xr-x   12 root     root             0 May 22 06:05 sys
drwxrwxrwt    2 root     root          4096 May 18  2023 tmp
drwxr-xr-x    4 root     root          4096 May 18  2023 usr
drwxr-xr-x    1 root     root          4096 May 22 06:08 var
touch: /data/acme.json: Permission denied
chmod: /data/acme.json: No such file or directory
```

Seems like the mounted `data` volume is owned by `root` and has no permissions for user `65532` set in `podSecurityContext.runAsUser` set by chart in default values.

### What is your environment & configuration?

I host Trafik on AKS in Azure using following Ansible script:

```yml
- name: Deploy Traefik
  kubernetes.core.helm:
    kubeconfig: "{{ k8s_admin_config_path }}"
    name: traefik
    chart_repo_url: https://traefik.github.io/charts
    chart_ref: traefik
    chart_version: "{{ traefik_chart_version }}"
    wait: true
    release_namespace: traefik
    create_namespace: true
    release_values:
      persistence:
        enabled: true
        size: 128Mi
      certResolvers:
        letsencrypt:
          email: "{{ letsencrypt_email }}"
          #caServer: https://acme-v02.api.letsencrypt.org/directory # Production server
          caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Staging server
          dnsChallenge:
            provider: azuredns
          storage: /data/acme.json
      env:
        - name: AZURE_CLIENT_ID
          value: "{{ azure_dns_challenge_application_id }}"
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azuredns-secret
              key: client-secret
        - name: AZURE_SUBSCRIPTION_ID
          value: "{{ azure_subscription_id }}"
        - name: AZURE_TENANT_ID
          value: "{{ azure_tenant_id }}"
        - name: AZURE_RESOURCE_GROUP
          value: "{{ azure_resource_group }}"
      deployment:
        initContainers:
          - name: volume-permissions
            image: busybox:latest
            command: ["sh", "-c", "ls -la /; touch /data/acme.json; chmod -v 600 /data/acme.json"]
            volumeMounts:
            - mountPath: /data
              name: data
      ports:
        web:
          redirectTo: 
            port: websecure
            scheme: https
      service:
        spec:
          type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "{{ azure_node_resource_group }}"
          service.beta.kubernetes.io/azure-pip-name: "{{ azure_resource_group }}"
          service.beta.kubernetes.io/azure-dns-label-name: "{{ azure_resource_group }}"
          service.beta.kubernetes.io/azure-allowed-ip-ranges: "{{ ip_range | join(',') }}"
      extraObjects:
        - apiVersion: v1
          kind: Secret
          metadata:
            name: azuredns-secret
            namespace: traefik
          type: Opaque
          stringData:
            client-secret: "{{ azure_dns_challenge_application_secret }}"
```

### Additional Information

```shell
Setting `podSecurityContext.fsGroup: 65532` resolves the problem even though it's discouraged in default values documentation.


podSecurityContext:
  # /!\ When setting fsGroup, Kubernetes will recursively change ownership and
  # permissions for the contents of each volume to match the fsGroup. This can
  # be an issue when storing sensitive content like TLS Certificates /!\
  # fsGroup: 65532
  # -- Specifies the policy for changing ownership and permissions of volume contents to match the fsGroup.
  fsGroupChangePolicy: "OnRootMismatch"
  # -- The ID of the group for all containers in the pod to run as.
  runAsGroup: 65532
  # -- Specifies whether the containers should run as a non-root user.
  runAsNonRoot: true
  # -- The ID of the user for all containers in the pod to run as.
  runAsUser: 65532
```
