### ISSUE TITLE
podtemplate not passing ports.X.redirectTo.permanent parameter

### ISSUE THREAD

**Issue by berlincount** [traefik/traefik-helm-chart#1076]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

28.0.0 / master

### What version of Traefik are you using?

3.0.1

### What did you do?

values contain:

```
ports:
  web:
    redirectTo:
      permanent: true
      port: websecure
```

### What did you see instead?

`traefik/templates/_podtemplate.tpl` did _not_ create the expected

```
--entryPoints.web.http.redirections.entryPoint.permanent=true
```

commandline configuration argument

### What is your environment & configuration?

microk8s

**Comment by mloiseleur** [comment]
Hello @berlincount,

That's right. It's not implemented FTM. 

That's why it's not documented in the [values](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml):

```yaml
ports:
  traefik:
    web:
[...]
    # redirectTo:
    #   port: websecure
    #   (Optional)
    #   priority: 10
```

It can be set using `additionalArguments`.

Feel free to open a PR if you need it.
