### ISSUE TITLE
Default Values on Traefik Proxy dashboard

### ISSUE THREAD

**Issue by mloiseleur** [traefik/traefik-helm-chart#1078]
## Current Situation

By default in this Chart, Traefik Proxy local dashboard is deployed with those settings:

```yaml
## Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true
    # -- Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
    annotations: {}
    # -- Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
    labels: {}
    # -- The router match rule used for the dashboard ingressRoute
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    # -- Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
    # By default, it's using traefik entrypoint, which is not exposed.
    # /!\ Do not expose your dashboard without any protection over the internet /!\
    entryPoints: ["traefik"]
    # -- Additional ingressRoute middlewares (e.g. for authentication)
    middlewares: []
    # -- TLS options (e.g. secret containing certificate)
    tls: {}
```

It means that the _API_ and the _dashboard_ are enabled by default, on _traefik_ entrypoint. 
By default, Traefik Proxy does not enable them. It's explained in upstream [documentation](https://doc.traefik.io/traefik/operations/api/) why:

> Enabling the API in production is not recommended, because it will expose all configuration elements, including sensitive data.

It says also:

> In production, it should be at least secured by authentication and authorizations.

It also means an Helm Chart user can miss that it's the default in the Chart, missed the fact that it's enabled and read what is required for production environment.

## Proposal

Keeping the same setting and disable _dashboard_ (and so _API_) by default. 

So, the values would become:

```yaml
## Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: false
```

It comes with the following benefits:

1. Secure by default
2. Helm Chart User keep the capacity to configure it easily with _values_
3. When Helm Chart _has to_ enable it, it means he _can_ be aware of impact and so, secure it properly

It has also some impact:

1. It's a breaking change,
2. It may break some tutorials

**Comment by mloiseleur** [comment]
@x0ddf There is a [complete example](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#publish-and-protect-traefik-dashboard-with-basic-auth) on basic auth. Is this what you have in mind ?

**Comment by x0ddf** [comment]
@mloiseleur almost, but the whole logic can be simplified for the basic auth case(middleware + secret could be created automatically):
```yaml
ingressRoute:
  dashboard:
    basicAuth:
      # according to the documentation https://doc.traefik.io/traefik/middlewares/http/basicauth/#usersfile
      usersFile: ""
      # from this array we could generate usersFile entry https://helm.sh/docs/chart_template_guide/function_list/#htpasswd
      users:
        - name: someuser
           pass: somepass
```
