### ISSUE TITLE
Problem with persistence with certificates, pod in pending

### ISSUE THREAD

**Issue by lvothnrv** [traefik/traefik-helm-chart#1081]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

28.1.0

### What version of Traefik are you using?

3.0.0

### What did you do?

```yaml
additionalArguments:
  - --certificatesresolvers.ovh.acme.dnschallenge.provider=ovh
  - --certificatesresolvers.ovh.acme.email=f.l@live.fr
  - --certificatesresolvers.ovh.acme.dnschallenge.resolvers="dns200.anycast.me, ns200.anycast.me"
  - --certificatesresolvers.ovh.acme.storage=/ssl-certs/acme-cloudflare.json

logs:
# Configure log settings here...
  general:
    level: ERROR

ports:
# Configure your entrypoints here...
  web:
    # (optional) Permanent Redirect to HTTPS
     redirectTo:
       port: websecure
  websecure:
    tls:
      enabled: true
      # (optional) Set a Default CertResolver
      certResolver: ovh

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/containous/traefik/issues/6972
    - name: volume-permissions
      image: busybox:1.36.1
      command: ["sh", "-c", "chmod -Rv 600 /ssl-certs/*"]
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
  enabled: true
  isDefaultClass: true

env:
  - name: OVH_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: ovh
        key: OVH_ENDPOINT

  - name: OVH_APPLICATION_KEY
    valueFrom:
      secretKeyRef:
        name: ovh
        key: OVH_APPLICATION_KEY

  - name: OVH_APPLICATION_SECRET
    valueFrom:
      secretKeyRef:
        name: ovh
        key: OVH_APPLICATION_SECRET

  - name: OVH_CONSUMER_KEY
    valueFrom:
      secretKeyRef:
        name: ovh
        key: OVH_CONSUMER_KEY
        ````

### What did you see instead?

````bash

🚨 When enabling persistence for certificates, permissions on acme.json can be
lost when Traefik restarts. You can ensure correct permissions with an
initContainer. See https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-traefik-native-lets-encrypt-integration-without-cert-manager
for more info. 🚨

````

### What is your environment & configuration?

I'm on Debian 12 with KubeADM, Traefik, and MetalLB on a personal VPS.

### Additional Information

```shell
I have the error message I sent, and my Traefik pod is stuck in pending and doesn't move, whereas when I use the chart without persistence, it works. I've searched everywhere on forums, etc., but none of the solutions given work.
```
