### ISSUE TITLE
Dashboard starts returning 404 after 28.2.0 update

### ISSUE THREAD

**Issue by mmeier86** [traefik/traefik-helm-chart#1096]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v28.3.0

### What version of Traefik are you using?

v3.0.2

### What did you do?

I upgraded the Helm chart to v28.2.0 (and today to v28.3.0) and realized today that the Traefik dashboard suddenly started to return 404 not found, even though many other IngressRoute and Ingress manifests still work perfectly fine.

### What did you see instead?

Dashboard returns 404.

### What is your environment & configuration?

I'm deploying the Helm chart on my Kubernetes cluster, with the following relevant `values.yaml` values:

```
deployment:
  healthchecksPort: 4435
  podLabels:
    homelab/ingress: "true"
additionalArguments:
  - "--ping.entryPoint=health"
  - "--providers.kubernetesingress.ingressendpoint.hostname=ingress-k8s.mei-home.net"
  - "--providers.kubernetescrd.allowCrossNamespace=true"
ingressRoute:
  dashboard:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: null
    entryPoints:
      - admin
    middlewares:
      - name: admin-basic-auth
        namespace: traefik-ingress
  admin:
    port: 4434
    exposedPort: 4434
    expose:
      default: true
    protocol: TCP
    tls:
      enabled: true
    middlewares:
      - traefik-ingress-headers-security@kubernetescrd
      - traefik-ingress-local-net@kubernetescrd
```

I'm not changing the `ingressClass` value at all.

### Additional Information

```shell
I do not see any entries related to the dashboard route during Traefik startup in the logs, but I do see log entries for all of the other IngressRoutes and Ingresses which do work.
When I delete and re-add the dashboard IngressRoute created by the Helm chart, the only log entry that I see which fits the timing is this one:

level=debug providerName=kubernetescrd caller=github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/kubernetes.go:177 message="Skipping Kubernetes event kind *v1alpha1.IngressRoute"
```
The `traefik-ingress-dashboard` resource created by the Helm chart looks like this:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    meta.helm.sh/release-name: traefik-ingress
    meta.helm.sh/release-namespace: traefik-ingress
    kubernetes.io/ingress.class: traefik-ingress
  creationTimestamp: "2024-06-20T21:38:57Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: traefik-ingress-traefik-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-28.3.0
    homelab/part-of: traefik-ingress
  name: traefik-ingress-dashboard
  namespace: traefik-ingress
  resourceVersion: "72257444"
  uid: ce8958e7-6ebd-4a26-b396-9a97f38a8089
spec:
  entryPoints:
  - admin
  routes:
  - kind: Rule
    match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    middlewares:
    - name: admin-basic-auth
      namespace: traefik-ingress
    services:
    - kind: TraefikService
      name: api@internal
```
If I make a copy of it and remove the `kubernetes.io/ingress.class` annotation, Traefik happily creates the router and I can access the dashboard again.

I believe the culprit might be PR #1079. This sets the ingress class for the route to the `traefik.fullname` value. But the IngressClass for the Kubernetes CRD provider does not seem to get set in the chart, and so it uses Traefik's default "Otherwise, resources missing the annotation, having an empty value, or the value traefik are processed." value as documented. And because the annotation for the dashboard route is now `traefik-ingress`, from `traefik.fullname`, it is neither missing, nor empty, nor "traefik", and so the IngressRoute for the dashboard is ignored.
```
