### ISSUE TITLE
Unable to use additionalServices to setup internal loadbalancer on AKS

### ISSUE THREAD

**Issue by arthar360** [traefik/traefik-helm-chart#1103]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

28.3.0

### What version of Traefik are you using?

3.0.2

### What did you do?

I have edited the values.yaml to use additionalServices. I intend to use AKS internal loadbalancer.

```
service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations: {}
  annotationsTCP: {}
  annotationsUDP: {}
  labels: {}
  spec: {}
  loadBalancerSourceRanges: []
  externalIPs: []

  # My Changes
  additionalServices:
    internal:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```
All other values in the file are untouched

It should have created an internal load balancer in azure

### What did you see instead?

It shows an error
```
$ helm upgrade --install traefik traefik/traefik -f values.yaml --version 28.3.0
                                                                                                                                   
Error: UPGRADE FAILED: execution error at (traefik/templates/service.yaml:34:6): You need to expose at least one port or set enabled=false to service
```

### What is your environment & configuration?

macOS 14.3.1
Helm: version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}

### Additional Information

```shell
Not sure if it is a bug or I am doing something wrong. I am currently using chart version 23.0.1 on prod and it works perfectly. 28.3.0 has problems. I have read the breaking changes and applied the breaking changes CRD's accordingly.
```

**Comment by mloiseleur** [comment]
The error message says:
> You need to expose at least one port or set enabled=false to service

And that's right. As you can see in [EXAMPLES.md](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#add-custom-internal-services), you have to specify in `ports:` section which one you want to expose on this service.

Does that answer your question ?

**Comment by mloiseleur** [comment]
@arthar360 I've opened a PR to improve error message (#1104). Wdyt ?

**Comment by arthar360** [comment]
Thanks a lot, The example helped to fix the problem. So now we need to expose services individually to the `additionalServices` and that was the missing part.

In the previous chart version 23.0.1 I had this config
```
ports:
  app1:
    port: 8080
    expose: true

  app2:
    port: 8081 
    expose: true

service:
  enabled: true
  single: true
  type: LoadBalancer
  internal:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-ipv4: 192.168.0.5
```

This would create 2 loadBalancers. Both of them used to have same ports without exposing ports individually. 

In the new config I have to add 
```
ports:
  app1:
    port: 8080 
    expose:
      default: true # For Public
      internal: true # For private

  app2:
    port: 8081
    expose:
      default: true # For Public
      internal: true # For private
```

This works as expected. 

Is there a way to expose all defined ports to default and additional services? It will save repeating `internal: true # For private` for each port.

**Comment by mloiseleur** [comment]
> Is there a way to expose all defined ports to default and additional services? It will save repeating `internal: true # For private` for each port.

I'm not aware of it. Feel free to open a PR if you need it.

**Comment by bronhy** [comment]
This does not work for me 

`ports:
  internal80:
    expose:
      internal: true
    port: 80
    redirectTo:
      port: internal443
  internal443:
    expose:
      internal: true
    port: 443
  web:
    redirectTo:
      port: websecure`

`service:
  additionalServices:
    internal:
      enabled: true
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      labels:
        traefik-service-label: internal`

funny enough the lb changes the port to 443 and 80 but the chart update fails and reverts back to 9000

**Comment by bronhy** [comment]
I got it working.

Here is the answer for users looking for the solution to this issue

```
ports:
  web:
    expose:
      internal: true
      default: true
    redirectTo:
      port: websecure
  websecure:
    expose:
      internal: true
      default:  true
```
```

service:
  additionalServices:
    internal:
      enabled: true
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      labels:
        traefik-service-label: internal

```
