### ISSUE TITLE
Templates have wrong indentation?

### ISSUE THREAD

**Issue by david-garcia-garcia** [traefik/traefik-helm-chart#1110]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

28.3.0

### What version of Traefik are you using?

2.11.5

### What did you do?

Apply the helm chart, using this as values:

```
additionalVolumes:
  - name: static-config
    configMap:
      name: traefik-config

additionalVolumeMounts:
  - name: static-config
    mountPath: /etc/traefik/traefik.yml
    subPath: traefik-config.yaml
```

### What did you see instead?

```
* Deployment.apps "traefik" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "static-config"
```

### What is your environment & configuration?

Using terraform

**Comment by david-garcia-garcia** [comment]
Should this in the templates:

```
          {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 10 }}
          {{- end }}
```

be

```
          {{- if .Values.additionalVolumeMounts }}
{{- toYaml .Values.additionalVolumeMounts | nindent 10 }}
          {{- end }}
```

**Comment by mloiseleur** [comment]
With this values, it will add the volume:

```yaml
deployment:
  additionalVolumes:
  - name: static-config
    configMap:
      name: traefik-config

additionalVolumeMounts:
  - name: static-config
    mountPath: /etc/traefik/traefik.yml
    subPath: traefik-config.yaml
```
