### ISSUE TITLE
Default gateway is incompatible with cert-manager

### ISSUE THREAD

**Issue by roee88** [traefik/traefik-helm-chart#1126]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v29.0.1

### What version of Traefik are you using?

3.1.0

### What did you do?

I want to deploy with gateway enabled (default) but integrate it with cert-manager as indicated in the docs:
> Additional gateway annotations (e.g. for cert-manager.io/issuer)

### What did you see instead?

As documented in https://cert-manager.io/docs/usage/gateway/, the hostname and tls.mode fields are required. However, the chart template doesn't specify them.

### What is your environment & configuration?

N/A

**Comment by darkweaver87** [comment]
Hello @roee88 ,

Thanks for reaching out.

Here is a working example.

Create a cluster:

```bash
k3d cluster create traefik --port 80:80@loadbalancer --port 443:443@loadbalancer --k3s-arg "--disable=traefik@server:0"
```

`traefik-values.yaml`:

```yaml
image:
  tag: v3.1.0

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
  certificateRefs:
    - name: whoami-tls
```

Install traefik:

```bash
helm repo add traefik https://traefik.github.io/charts  --force-update
helm upgrade --install \
  traefik traefik/traefik\
  --namespace traefik \
  --create-namespace \
  --version v29.0.1 \
 -f values.yaml
```

Install cert-manager:

```bash
helm repo add jetstack https://charts.jetstack.io --force-update
helm upgrade --install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.15.1 \
  --set crds.enabled=true \
  --set "extraArgs={--enable-gateway-api}"
```

`whoami-example`:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: traefik
spec:
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
  hostnames:
    - whoami.docker.localhost
  rules:
    - matches:
        - path:
            type: Exact
            value: /

      backendRefs:
        - name: whoami
          port: 80
          weight: 1

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: traefik
spec:
  selfSigned: {}

---                           
apiVersion: cert-manager.io/v1
kind: Certificate             
metadata:                     
  name: whoami-tls            
  namespace: traefik          
spec:                         
  commonName: whoami          
  secretName: whoami-tls      
  dnsNames:                   
    - "whoami.docker.localhost
  issuerRef:                  
    name: selfsigned-issuer   
    kind: Issuer              
    group: cert-manager.io
```

```bash
kubectl apply -f whoami-example.yaml
```

Check:

```bash
curl https://whoami.docker.localhost -k
echo | openssl s_client -showcerts -servername whoami.docker.localhost -connect whoami.docker.localhost:443 2>/dev/null | openssl x509 -noout -text 2>&1 | grep CN
        Issuer: CN=whoami
        Subject: CN=whoami
```

I think setting hostnames at gateway level is not likely what people want because you'll need as much gateways as you have TLS hosts. Maybe it has something to see with https://github.com/cert-manager/cert-manager/issues/6051 ?
What do you think ?

**Comment by roee88** [comment]
I believe your example will work without `cert-manager.io/issuer: selfsigned-issuer` (I'll try without it later). That is, you don't benefit from the Annotated Gateway resource feature of cert-manager in that example.

I agree that in many use cases hostname in Gateway isn't what people would use, but in other cases it would. The request here is to allow specifying tls.mode and hostname as optional values in the chart, for those use cases.

**Comment by darkweaver87** [comment]
Yes that's right, I forgot to remove it from my tests :sweat_smile: 
I'm ok with opening a PR to allows setting those parameters but we will have to document the fact that it will only allow one TLS name and users should then create additional gateways to cover other TLS names.
I guess that's fine. Don't you think ?

**Comment by roee88** [comment]
Hi, that could work. 

However, `Gateway` can have multiple listeners for the same port, so no need for multiple gateways (which in some implementations create new deployments). Examples in [Listeners with different certificates](https://gateway-api.sigs.k8s.io/guides/tls/#listeners-with-different-certificates) and [cert-manager examples](https://cert-manager.io/docs/usage/gateway/#two-listeners-with-the-same-secret-name) (tested with traefik too).

So for flexibility the template can be changed to allow specifying full websecure listeners (excluding port). For example, `values.yaml `:

```yaml
gateway:
  # -- When providers.kubernetesGateway.enabled, deploy a default gateway
  enabled: true
  # -- Set a custom name to gateway
  name:
  # -- By default, Gateway is created in the same `Namespace` than Traefik.
  namespace:
  # -- Additional gateway annotations (e.g. for cert-manager.io/issuer)
  annotations: 
  # -- Listeners for the websecure port
  websecureListeners:
  # - # -- See [SectionName](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.SectionName) 
  #  name: websecure
  #  # -- See [Hostname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.Hostname)
  #  hostname: 
  #  # -- See [ProtocolType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.ProtocolType)
  #  protocol: HTTPS
  #  # -- See [GatewayTLSConfig](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayTLSConfig)
  #  tls:
  #  # -- See[AllowedRoutes](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.AllowedRoutes)
  #  allowedRoutes: 
```

Or, just remove the comment about cert-manager annotations and treat the gateway deployment at example level (I personally would make it `enabled: false` by default in that case). What do you think?
