### ISSUE TITLE
helm executing "traefik/templates/gateway.yaml" at <.Values.ports.web.port>: nil pointer evaluating interface {}.port

### ISSUE THREAD

**Issue by qianlongzt** [traefik/traefik-helm-chart#1132]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

29.0.1

### What version of Traefik are you using?

3.1.0

### What did you do?

```shell
helm upgrade --install --namespace=traefik --create-namespace   traefik traefik/traefik   --values=cluster/traefik-helm-spec.yaml
```

### What did you see instead?

```shell
Error: UPGRADE FAILED: template: traefik/templates/gateway.yaml:18:22: executing "traefik/templates/gateway.yaml" at <.Values.ports.web.port>: nil pointer evaluating interface {}.port
```

### What is your environment & configuration?

```yaml
image:
  tag: v3.1.0
ports:
  web: null
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    hostPort: 443
    http3:
      enabled: true
    tls:
      enabled: true
service:
  enabled: false
  type: NodePort
  spec:
    externalTrafficPolicy: Local
hostNetwork: true
additionalArguments:
  - --log.format=json
  - --accesslog
  - --providers.kubernetescrd.allowCrossNamespace=true
deployment:
  kind: Deployment
updateStrategy:
  type: Recreate
  rollingUpdate: null
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0 # 
  runAsNonRoot: false
  runAsUser: 0
providers:
  # Disable the Ingress provider (optional)
  # We do not want to use Ingress objects anymore!
  kubernetesIngress:
    enabled: false
  # Enable the GatewayAPI provider
  kubernetesGateway:
    enabled: true
# Allow the Gateway to expose HTTPRoute from all namespaces
gateway:
  namespacePolicy: All

```
