### ISSUE TITLE
Invalid value: "array": tls must be specified for protocols ['HTTPS', 'TLS']

### ISSUE THREAD

**Issue by conradwt** [traefik/traefik-helm-chart#1147]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm attempting to follow the following walkthrough of using the Gateway API:

https://traefik.io/blog/getting-started-with-kubernetes-gateway-api-and-traefik

When I run 

```zsh
helm upgrade --install --namespace traefik traefik traefik/traefik -f values.yaml
```

### What did you see instead?

```zsh
Release "traefik" does not exist. Installing it now.
Error: 1 error occurred:
	* Gateway.gateway.networking.k8s.io "traefik-gateway" is invalid: spec.listeners: Invalid value: "array": tls must be specified for protocols ['HTTPS', 'TLS']
```

### What version of Traefik are you using?

v3.1.0

### What is your environment & configuration?

```yaml
## File values.yaml ##
providers:
  # Disable the Ingress provider (optional)
  # We do not want to use Ingress objects anymore!
  kubernetesIngress:
	enabled: false
  # Enable the GatewayAPI provider
  kubernetesGateway:
	enabled: true
# Allow the Gateway to expose HTTPRoute from all namespaces
gateway:
  namespacePolicy: All
```

**Comment by mmatur** [comment]
Hi @conradwt,

I moved this issue because it is not related to Traefik but to the helm chart. Someone would take a look to this issue pretty soon.

**Comment by michalsteyn** [comment]
I experienced the same problem for v30 of the helm chart. Downgrading to v29.0.1 resolves the issue. So there is something wrong with v30.

**Comment by rohanrehman** [comment]
It looks like tls value may be missing in the listeners ?
[Here is the traefik-helm-chart values.yaml](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml)

```
gateway:
  # -- When providers.kubernetesGateway.enabled, deploy a default gateway
  enabled: true
  # -- Set a custom name to gateway
  name:
  # -- By default, Gateway is created in the same `Namespace` than Traefik.
  namespace:
  # -- Additional gateway annotations (e.g. for cert-manager.io/issuer)
  annotations:
  # -- Define listeners
  listeners:
    web:
      # -- Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules.
      # The port must match a port declared in ports section.
      port: 8000
      # -- Optional hostname. See [Hostname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Hostname)
      hostname:
      # Specify expected protocol on this listener. See [ProtocolType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.ProtocolType)
      protocol: HTTP
      # -- Routes are restricted to namespace of the gateway [by default](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.FromNamespaces
      namespacePolicy:
    websecure:
      # -- Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules.
      # The port must match a port declared in ports section.
      port: 8443
      # -- Optional hostname. See [Hostname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Hostname)
      hostname:
      # Specify expected protocol on this listener See [ProtocolType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.ProtocolType)
      protocol: HTTPS
      # -- Routes are restricted to namespace of the gateway [by default](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.FromNamespaces)
      namespacePolicy:
      # -- Add certificates for TLS or HTTPS protocols. See [GatewayTLSConfig](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayTLSConfig)
      certificateRefs:
      # -- TLS behavior for the TLS session initiated by the client. See [TLSModeType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.TLSModeType).
      mode:
```
@darkweaver87 could you take a look?
[Traefiks official docs on enabeling the Gateway Api ](https://traefik.io/blog/getting-started-with-kubernetes-gateway-api-and-traefik/) is currently not working and throws with k3s version v1.30.2+k3s1.

```
Error: UPGRADE FAILED: failed to create resource: Gateway.gateway.networking.k8s.io "traefik-gateway" is invalid: spec.listeners: Invalid value: "array": tls must be specified for protocols ['HTTPS', 'TLS']
```
