### ISSUE TITLE
Hostname wildcards not allowed due to "error converting YAML to JSON"

### ISSUE THREAD

**Issue by marcopaggioro** [traefik/traefik-helm-chart#1156]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v30.0.2

### What version of Traefik are you using?

docker.io/traefik:v3.1.0

### What did you do?

`helm install traefik traefik/traefik --version v30.0.2 --values /root/traefik_helm_values.yaml --namespace traefik --create-namespace`

### What did you see instead?

`Error: INSTALLATION FAILED: YAML parse error on traefik/templates/gateway.yaml: error converting YAML to JSON: yaml: line 17: did not find expected alphabetic or numeric character`

### What is your environment & configuration?

`/root/traefik_helm_values.yaml` file
```
providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      hostname: "*.example.it"
      namespacePolicy: "All"
```

### Additional Information

```shell
Maybe add `| quote` to the helm? Ref: https://github.com/helm/helm/issues/9917#issuecomment-1163791279
```
