### ISSUE TITLE
Support Gateway infrastructure

### ISSUE THREAD

**Issue by hongbo-miao** [traefik/traefik-helm-chart#1157]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great to support Gateway `infrastructure`, thanks!
https://kubernetes.io/blog/2023/11/28/gateway-api-ga/#gateway-infrastructure-labels

It will help us pass `service.beta.kubernetes.io/aws-load-balancer-type: nlb` to use AWS Network Load Balancer ☺️

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: horizon-cilium-gateway
  namespace: production-horizon-gateway-api
  annotations:
    cert-manager.io/cluster-issuer: staging-lets-encrypt-issuer
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  # ...
```
