### ISSUE TITLE
ingressRoute dashboard

### ISSUE THREAD

**Issue by mehran-torkaman** [traefik/traefik-helm-chart#1163]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

30.0.2

### What version of Traefik are you using?

v3.1.0

### What did you do?

I've tried to enable helm chart dashboard value inside values file of traefik 30.0.2 helm chart.

### What did you see instead?

Inside the ingressroute.yaml template file, there was an issue in the "if statement" where it was getting the value true from .Values.ingressRoute.enabled instead of from .Values.ingressRoute.dashboard.enabled. This issue might be related to the values.yaml file, and it may need a refactor to remove "dashboard" under "ingressRoute" from the values.yaml file or add "dashboard" to the "if statement" in the ingressroute.yaml file.

### What is your environment & configuration?

I'm using kubernetes cluster version v1.28.6 and helm version v3.14.2

**Comment by mloiseleur** [comment]
There are many [tests](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/tests/dashboard-ingressroute_test.yaml) ensuring `IngressRoute` template for dashboard is working.

Would you please share the _values_ used?

**Comment by mehran-torkaman** [comment]
sorry, you write it was may fault. it works fine.
actually i was trying to deploy traefik with helm dependency but there was a typo in my values file.

**Comment by devantler** [comment]
I dunno, I can't make it work. It has worked before:

```yaml
  values:
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        middlewares:
          - traefik-auth-headers@kubernetescrd
    tlsStore:
      default:
        defaultCertificate:
          secretName: cluster-issuer-certificate-tls
    service:
      type: ${traefik_service_type:=ClusterIP}
      spec:
        loadBalancerIP: ${traefik_ingress_load_balancer_ip}
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.${cluster_domain}`)
        entryPoints:
          - websecure
        middlewares:
          - name: traefik-forward-auth
```

Seems correct to me, so I think something is afoot.
