### ISSUE TITLE
Traefik Promeuths metrics do not work

### ISSUE THREAD

**Issue by alfredopalhares** [traefik/traefik-helm-chart#1175]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v.30.1.0

### What version of Traefik are you using?

v3.1.2

### What did you do?

Hello. I have tried to reach the metrics endpoints but the traefik port is unreachble at at. There are the flags on the deployment.
```yaml
      - args:
        - --api.insecure=true
        - --providers.kubernetesingress.ingressendpoint.ip
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowExternalNameServices=true
        - --providers.kubernetesingress
        - --entryPoints.websecure.http.tls=true
        - --log.level=INFO
```

### What did you see instead?

When I try to reach the port this is what i get.
```
-> % kubectl -n traefik-ingress port-forward deployment/traefik-ingress 9100:9100
Forwarding from 127.0.0.1:9100 -> 9100
Forwarding from [::1]:9100 -> 9100
Handling connection for 9100
E0822 00:49:59.545482 3696122 portforward.go:413] an error occurred forwarding 9100 -> 9100: error forwarding port 9100 to pod a37c926c9625c6a70b417ca48032beda729ebd61460df8d93ecd3b72579d5c72, uid : failed to execute portforward in network namespace "/var/run/netns/cni-e4766662-d438-069d-6d75-36d0ec32f08c": failed to connect to localhost:9100 inside namespace "a37c926c9625c6a70b417ca48032beda729ebd61460df8d93ecd3b72579d5c72", IPv4: dial tcp4 127.0.0.1:9100: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
error: lost connection to pod'
```

On the admin interface I even get this 
![Screenshot from 2024-08-22 00-51-22](https://github.com/user-attachments/assets/8db39df8-7f47-4658-a643-52b7cb20230a)

### What is your environment & configuration?

Here are my values:
```yaml
-> % helm  -n traefik-ingress get values traefik-ingress
USER-SUPPLIED VALUES:
deployment:
  autoscaling:
    enabled: true
    maxReplicas: 5
    minReplicas: 2
  replicas: 2
globalArguments:
- --api.insecure=true
- --providers.kubernetesingress.ingressendpoint.ip
ingressClass:
  enabled: true
  fallbackApiVersion: v1
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: true
providers:
  kubernetesCRD:
    allowExternalNameServices: true
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
serviceAccountAnnotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::0000000000:role/eks-lb-controller
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Equal
  value: ingress
```

This is running on EKS Cluster verion 1.29

**Comment by mloiseleur** [comment]
Thanks for your interest in Traefik and this report.

It seems to be an upstream problem. On a local cluster, with this values, metrics endpoint is here and works as expected:

```yaml
deployment:
  autoscaling:
    enabled: true
    maxReplicas: 5
    minReplicas: 2
  replicas: 2
globalArguments:
- --api.insecure=true
ingressClass:
  enabled: true
  fallbackApiVersion: v1
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.docker.localhost`)
    entryPoints:
      - web
ports:
  web:
    nodePort: 30000
  websecure:
    nodePort: 30001
providers:
  kubernetesCRD:
    allowExternalNameServices: true
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
serviceAccountAnnotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::0000000000:role/eks-lb-controller
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Equal
  value: ingress
```

When adding `--providers.kubernetesingress.ingressendpoint.ip`, the metrics endpoint cease to work.

As a matter of fact, when setting 
```yaml
globalArguments:
- --providers.kubernetesingress.ingressendpoint.ip
- --api.insecure=true
```

_metrics_ endpoint works as expected. 

It's like the CLI arg just after `--providers.kubernetesingress.ingressendpoint.ip` is taken as the value of it instead as the next arg.

According to [upstream documentation on it](https://doc.traefik.io/traefik/providers/kubernetes-ingress/#ip), this arg cannot be used like that, without a string value representing IPv4 or IPv6.

Since there is nothing to do on the Chart, I'll close this issue. Feel free to re-open it if needed.
