### ISSUE TITLE
Make IngressRouteTCP more similar to IngressRoute

### ISSUE THREAD

**Issue by StefanTheWiz** [traefik/traefik-helm-chart#1190]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When writing helm templates, it would make it much easier if the `IngressRouteTCP` and `IngressRoute` CRDs were more alike, at least in a few key places.

For instance:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-example
spec:
  entryPoints: [vpc-http]
  routes:
  - kind: Rule # this is missing from TCP although the other properties exist
    match: Host(`my-server.my-vpc.private`)
    services:
    - kind: Service
      namespace: my-namespace
      name: my-app
      port: http
```

In particular, having the `kind` property on `routes[]` and `routes[].services[]` of `IngressRouteTCP` would mean that we can use an almost identical template for TCP and HTTP routes (just need to set `.kind` to IngressRoute±TCP and `.entryPoints`)

Cases like [this](https://github.com/traefik/traefik-helm-chart/issues/820) are encountered quite often because these two CRDs are so similar but Traefik complains because of this extra `kind` field that would have to be removed for the TCP route to be admitted by the CRD controller.
