### ISSUE TITLE
Traefik installed with the latest Helm chart version (32.1.0) not recognising IngressRoutes

### ISSUE THREAD

**Issue by AnitaErnszt** [traefik/traefik-helm-chart#1215]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

32.1.0

### What version of Traefik are you using?

3

### What did you do?

We currently have Helm v12 running in the cluster, and want to upgrade to the latest version.

Instead of going through multiple complicated major version upgrades we have opted to deploy the latest Helm chart in a new namespace, recreated all resources in the new namespace, verify it's working as expected, switch over, and deprecate the old namespace. Upgrade should happen without downtime.

I have installed the new CRDs in the cluster (so I have both the old (`traefik.containo.us`) and new (`traefik.io`) sets installed), a deployed the latest Helm.

### What did you see instead?

Resources created using the new apiVersion `traefik.io/v1alpha1` are not working, traefik returns 404.

When I check the success of the Helm deployment I see the dashboard IngressRoute also having issue, despite the CRDs installed, and the IngressRoute manifest uses the correct apiVersion
![Image](https://github.com/user-attachments/assets/496408fe-e94f-40b3-9802-8b3881262814)
![Image](https://github.com/user-attachments/assets/3808e14c-c8b9-41db-a51f-e35c530edecc)
![Image](https://github.com/user-attachments/assets/909b81f4-7f19-492d-83bf-10eda9da8b42)

Tried upgrading my existing v12 Helm chart to v27, but was running into the same issue, so it suggest to me I'm missing something obvious. Found a similar [open topic](https://community.traefik.io/t/traefik-v3-does-not-pick-up-any-kubernetes-ingressroutes/24545) on the community forum but it has no answer yet.

### What is your environment & configuration?

I tried various Helm chart configs but I couldn't get it working with either of them. This was my last chart attempts:
```
core:
    defaultRuleSyntax: "v2"
deployment:
    enabled: true
    kind: Deployment
    replicas: 1
    minReadySeconds: 15
ingressClass:
    enabled: false
ingressRoute:
    dashboard:
        enabled: true
        entryPoints:
            - websecure
        matchRule: Host(`traefik-new-${env}.example.com`)
        middlewares:
            - name: traefik-forward-auth
        services:
            - kind: TraefikService
              name: api@internal
instanceLabelOverride: "traefik"
logs:
    access:
        enabled: true
        format: "json"
    general:
        format: "json"
        level: INFO
        noColor: true
ports:
    traefik:
        expose:
            default: false
   websecure:
         expose:
             default: true
providers:
    kubernetesCRD:
        allowCrossNamespace: true
        allowEmptyServices: true
        allowExternalNameServices: false
        enabled: true
    kubernetesIngress:
        enabled: false
rbac:
    enabled: true
    namespaced: false
service:
    enabled: true
    type: ClusterIP
```

**Comment by AnitaErnszt** [comment]
`traefik-dashboard` uses the new API in the new namespace:
```
# Source: traefik/templates/dashboard-ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
```

`traefik-forward-auth` has also been deployed to the new namespace, using the new API:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: traefik
```

Even if I delete the helm chart and re-create it using v27, still having the same issue:
![Image](https://github.com/user-attachments/assets/7cb2dde4-b142-4ccb-a5d8-5de4eff053e2)
