### ISSUE TITLE
Can't get HTTPS to work with Kubernetes Gateway API

### ISSUE THREAD

**Issue by wanGiB** [traefik/traefik-helm-chart#1230]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

32.1.1

### What version of Traefik are you using?

3.1.6

### What did you do?

I have my `values.yaml` file configured as shown below

```yaml

providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

deployment:
  kind: "DaemonSet"

gateway:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  listeners:
    websecure:
      hostname: "*.mydomain.xyz"
      port: 8443
      protocol: HTTPS
      namespacePolicy: All
      certificateRefs:
        - name: whoami-tls
      mode: "Terminate"

service:
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/name: "cluster-lb"
    load-balancer.hetzner.cloud/network-zone: "eu-central"

```

Here is how my cluster issuer is defined in `whoami-issuer.yaml`:

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: example@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-credentials
              key: api-token
```

Here is how `cloudflare-credentials.yaml` is defined:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "{{CLOUDFLARE_TOKEN}}"
```

Below are the steps I took:

```bash
# Install or upgrade cert-manager
helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.16.1 --set crds.enabled=true --set "extraArgs={--enable-gateway-api}" --debug

kubectl apply -f "cloudflare-credentials.yaml"
kubectl apply -f "whoami-issuer.yaml"

helm upgrade --install --version 32.1.1 --namespace traefik traefik traefik/traefik -f "values.yaml" --debug

```

The certificate was successfully issued, as shown below:

```
NAMESPACE   NAME         READY   SECRET       AGE
traefik     whoami-tls   True    whoami-tls   88m
```

I then applied a sample HTTP route, as shown below:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux
  namespace: socials
  labels:
    app: flux
spec:
  parentRefs:
    - name: traefik-gateway
       sectionName: websecure
       namespace: traefik
  hostnames:
    - "flux.mydomain.xyz"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: flux
          port: 80
          namespace: socials
```

Now, when I visit the above route at https://flux.mydomain.xyz/, I expect the connection to be secured and my routes to resolve correctly.

### What did you see instead?

I received a 404 Page Not Found error, and the browser indicates that my connection to https://flux.mydomain.xyz/ is not secure.

### What is your environment & configuration?

Ubuntu 24.04, Hetzner Cloud

### Additional Information

My routes resolve perfectly if I remove the websecure listener and use only the web listener; however, the connections are not secure, which is not acceptable.

By the way [here](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-kubernetes-gateway-api-with-cert-manager) is the example I followed

**Comment by mloiseleur** [comment]
There is an indentation error in this yaml:

```yaml
# [...]
  parentRefs:
    - name: traefik-gateway
       sectionName: websecure
       namespace: traefik
#    ^ Here

**Comment by darkweaver87** [comment]
Hello 👋 
Would you also mind to check which are the domains your certificate is valid for ?

**Comment by mloiseleur** [comment]
The example is working.

There is an indentation error in this yaml:

```yaml
# [...]
  parentRefs:
    - name: traefik-gateway
       sectionName: websecure
       namespace: traefik
#    ^ Here

**Comment by wanGiB** [comment]
@mloiseleur and @darkweaver87 thanks for your responses. I have no indentation issues as you can see below:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: instagram
  namespace: socials
  labels:
    app: instagram
spec:
  parentRefs:
    - name: traefik-gateway
       sectionName: websecure
       namespace: traefik
  hostnames:
    - "flux.example.xyz"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: instagram
          port: 80
          namespace: socials
```

As a matter of fact, the above route works if i remove the `websecure` listener and go back to the unsecured `web` listener in the helm chart values. If there was an indentation issue, the pages won't resolve at all even when I switch back to `sectionName: web`.

I strongly feel, the issue lies somewhere around the helm chart values which is below:

```yaml
providers:
kubernetesIngress:
  enabled: false
kubernetesGateway:
  enabled: true

deployment:
  kind: "DaemonSet"

rbac:
  enabled: true

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true

gateway:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  listeners:
    websecure:
      hostname: "*.{{domain}}"
      port: 8443
      protocol: HTTPS
      namespacePolicy: All
      certificateRefs:
        - name: multi-domain-tls
      mode: "Terminate"

service:
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/name: "cluster-lb"
    load-balancer.hetzner.cloud/network-zone: "eu-central"

```

Also, here is the output of the certificate generated by the `cert-manager` annotation above:

```
Name:         multi-domain-tls
Namespace:    traefik
Labels:       app.kubernetes.io/instance=traefik-traefik
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=traefik
              helm.sh/chart=traefik-32.1.1
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2024-10-21T07:31:53Z
  Generation:          1
  Owner References:
    API Version:           gateway.networking.k8s.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Gateway
    Name:                  traefik-gateway
    UID:                   d1729449-3308-4b8f-8b9f-53a27643d27a
  Resource Version:        2170
  UID:                     e618472f-fcf4-48d4-9afa-a1086a9f2b18
Spec:
  Dns Names:
    *.example.xyz
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt-production
  Secret Name:  multi-domain-tls
  Usages:
    digital signature
    key encipherment
Status:
  Conditions:
    Last Transition Time:  2024-10-21T07:33:14Z
    Message:               Certificate is up to date and has not expired
    Observed Generation:   1
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2025-01-19T06:34:42Z
  Not Before:              2024-10-21T06:34:43Z
  Renewal Time:            2024-12-20T06:34:42Z
  Revision:                1
Events:
  Type    Reason     Age   From                                       Message
  ----    ------     ----  ----                                       -------
  Normal  Issuing    15m   cert-manager-certificates-trigger          Issuing certificate as Secret does not exist
  Normal  Generated  15m   cert-manager-certificates-key-manager      Stored new private key in temporary Secret resource "multi-domain-tls-m66df"
  Normal  Requested  15m   cert-manager-certificates-request-manager  Created new CertificateRequest resource "multi-domain-tls-1"
  Normal  Issuing    13m   cert-manager-certificates-issuing          The certificate has been successfully issued

```
My real domain name is in the certificate above, but I just replaced my real domain name name with just `example` just for the purpose of this issue

And here is the equivalent secret generated as well:

```
Name:         multi-domain-tls
Namespace:    traefik
Labels:       controller.cert-manager.io/fao=true
Annotations:  cert-manager.io/alt-names: *.example.xyz
              cert-manager.io/certificate-name: multi-domain-tls
              cert-manager.io/common-name: *.example.xyz
              cert-manager.io/ip-sans: 
              cert-manager.io/issuer-group: cert-manager.io
              cert-manager.io/issuer-kind: ClusterIssuer
              cert-manager.io/issuer-name: letsencrypt-production
              cert-manager.io/uri-sans: 

Type:  kubernetes.io/tls

Data
====
tls.crt:  3570 bytes
tls.key:  1675 bytes

```

**Comment by wanGiB** [comment]
For anyone else who might face a similar issue when using CloudFlare DNS-01, the issue all along was the API token. Cloudflare tokens don't work in this case.

Instead of using an API token, you need to generate and use a Global API Key from your Cloudflare account. This was the root cause of the issue.

Here's the corrected configuration:


**Incorrect (won't work):**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "{{CLOUDFLARE_TOKEN}}"     # ❌ This will fail
```

**Correct (will work):**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-key: "{{CLOUDFLARE_API_KEY}}"     # ✅ Use this instead
```

Make sure to use the Global API Key from your Cloudflare account settings. This change should resolve any related credential issues with cert-manager and voilla HTTPS works now
