### ISSUE TITLE
Router uses a nonexistent certificate resolver

### ISSUE THREAD

**Issue by Miras4207** [traefik/traefik-helm-chart#1232]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

32.1.1

### What version of Traefik are you using?

v3.1.6

### What did you do?

I installed traefik using this helm chart and tried to setup Let's Encrypt Certificate for Ingress. Unfortunately, traefik **doesn't recognize the certificate resolver**, although it is configured in helm values.

The error shown in logs is:
```
ERR Router uses a nonexistent certificate resolver certificateResolver=letsEncrypt routerName=test-whoami-ingress-whoami-example-com@kubernetes
```

The issue seems to be that configured storage file `acme.json` is not created (even in `/tmp` directory, which should be always writable).  Please note that persistence is **not** enabled - this is to rule out any permission issues like reported in https://github.com/traefik/traefik-helm-chart/issues/396.

Steps to reproduce:

_(Private information redacted  with example.com domain)_

### 1. Install Traefik with following values

```bash
helm install --namespace traefik traefik traefik/traefik --values traefik/values.yaml
```

```yaml
# traefik/values.yaml

certificatesResolvers:
  letsEncrypt:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: redacted@example.com
      httpChallenge:
        entryPoint: web
      storage: /tmp/acme.json

persistence:
  enabled: false
```

### 2. Create Ingress with TLS

```bash
kubectl apply -f test/ingress.yaml
```

```yaml
# test/ingress.yaml

kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: whoami
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test
  name: whoami-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsEncrypt
spec:
  rules:
    - host: "whoami.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  name: web
  tls:
    - hosts:
      - "whoami.example.com"
```

### 3. See error in Traefik logs 

```bash
kubectl -n traefik logs traefik-659d574c56-vgfjx
```

```
2024-10-22T17:38:07Z INF Traefik version 3.1.6 built on 2024-10-09T13:57:41Z version=3.1.6
2024-10-22T17:38:07Z INF Stats collection is enabled.
2024-10-22T17:38:07Z INF Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.
2024-10-22T17:38:07Z INF Help us improve Traefik by leaving this feature on :)
2024-10-22T17:38:07Z INF More details on: https://doc.traefik.io/traefik/contributing/data-collection/
2024-10-22T17:38:07Z INF Starting provider aggregator aggregator.ProviderAggregator
2024-10-22T17:38:07Z INF Starting provider *traefik.Provider
2024-10-22T17:38:07Z INF Starting provider *crd.Provider
2024-10-22T17:38:07Z INF label selector is: "" providerName=kubernetescrd
2024-10-22T17:38:07Z INF Creating in-cluster Provider client providerName=kubernetescrd
2024-10-22T17:38:07Z INF Starting provider *ingress.Provider
2024-10-22T17:38:07Z INF ingress label selector is: "" providerName=kubernetes
2024-10-22T17:38:07Z INF Creating in-cluster Provider client providerName=kubernetes
2024-10-22T17:38:07Z INF Starting provider *acme.ChallengeTLSALPN
2024-10-22T17:49:21Z ERR Router uses a nonexistent certificate resolver certificateResolver=letsEncrypt routerName=test-whoami-ingress-whoami-example-com@kubernetes
```

### 4. Check for existence of `acme.json`

```
kubectl -n traefik exec -it traefik-659d574c56-vgfjx -- ls -la /tmp/acme.json
```

```
ls: /tmp/acme.json: No such file or directory
command terminated with exit code 1
```

### What did you see instead?

I would expect that configured storage file `acme.json` is created and Let's Encrypt Certificate is properly configured.

### What is your environment & configuration?

I am using bare-metal cluster installed via `kubeadm` and hosted on Contabo VPS with Debian 12.

```
$ kubeadm version

kubeadm version: &version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.1", GitCommit:"948afe5ca072329a73c8e79ed5938717a5cb3d21", GitTreeState:"clean", BuildDate:"2024-09-11T21:26:49Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl version

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1
```

```
$ uname -r

6.1.0-10-amd64
```

```
$ cat /etc/os-release

uname -r
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
```

### Additional Information

I would be grateful for any help, as I have already spent hours trying to solve this without any success.

I tried it even with persistence enabled together with most fixes reported in https://github.com/traefik/traefik-helm-chart/issues/396, but it doesn't even seem to work with persistence disabled, so I suspect there may be other underlying issue.

I am new to Traefik, so perhaps there is something I am overlooking. If there are any other information that I could provide, please, let me know.

Thank you.

**Comment by mloiseleur** [comment]
Hello @Miras4207,

In the values, the syntax on certificate resolver was different and is different in v32.1.1 of the Chart. 

It was changed with this PR https://github.com/traefik/traefik-helm-chart/pull/1214 .

**Comment by Miras4207** [comment]
Hello @mloiseleur,

thanks for your support. I was able to obtain Let's Encrypt Staging Certificate using these values instead:

```yaml
certResolvers:
  letsEncrypt:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: redacted@example.com
      httpChallenge:
        entryPoint: web
      storage: /tmp/acme.json
```
