### ISSUE TITLE
http3 + internal port cause error deploying

### ISSUE THREAD

**Issue by jalberto** [traefik/traefik-helm-chart#1233]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

32.1.1

### What version of Traefik are you using?

3.1.6

### What did you do?

When I combine http3 + port + internal service to access dashboard, I get this error:

`Error: INSTALLATION FAILED: failed to create resource: Service "traefik-internal-udp" is invalid: spec.ports: Required value`

If I remove the `http3` it installs as expected, but the dashboard is not accessible from inside the k8s network:

```sh
% curl traefik-internal.infra.svc.cluster.local:9000/dashboard/ -v
* Host traefik-internal.infra.svc.cluster.local:9000 was resolved.
* IPv6: (none)
* IPv4: 10.33.168.7
*   Trying 10.33.168.7:9000...
* Connected to traefik-internal.infra.svc.cluster.local (10.33.168.7) port 9000
> GET /dashboard/ HTTP/1.1
> Host: traefik-internal.infra.svc.cluster.local:9000
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 24 Oct 2024 10:23:04 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host traefik-internal.infra.svc.cluster.local left intact
```

### What did you see instead?

`Error: INSTALLATION FAILED: failed to create resource: Service "traefik-internal-udp" is invalid: spec.ports: Required value`

### What is your environment & configuration?

```yaml
service:
  additionalServices:
    internal:
      type: ClusterIP
      labels:
        traefik-service-label: internal


ports:
  web:
    redirectTo:
      port: websecure
    forwardedHeaders:
      trustedIPs: *SCWTrustedIPs
    proxyProtocol:
      trustedIPs: *SCWTrustedIPs
  websecure:
    forwardedHeaders:
      trustedIPs: *SCWTrustedIPs
    proxyProtocol:
      trustedIPs: *SCWTrustedIPs
    http3:
      enabled: true
    tls:
      # default SSL provider
      certResolver: "traefik-lestag"
  # required for the dashboard
  traefik:
    expose:
      # Sensitive data should not be exposed on the internet
      # => Keep this disabled !
      default: false
      internal: true
```
