### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by wanGiB** [traefik/traefik-helm-chart#1242]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

32.1.1

### What version of Traefik are you using?

3.1.6

### What did you do?

I created the following `values.yaml` file when installing the helm chart:

```
providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

deployment:
  kind: "DaemonSet"

rbac:
  enabled: true

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true

gateway:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  listeners:
    websecure:
      # hostname: "*.{{domain}}"
      port: 8443
      protocol: HTTPS
      namespacePolicy: All
      certificateRefs:
        - name: multi-domain-tls
      mode: "Terminate"

service:
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/type: "lb21"
    load-balancer.hetzner.cloud/name: "cluster-lb"
    load-balancer.hetzner.cloud/network-zone: "eu-central"
    load-balancer.hetzner.cloud/use-proxy-protocol: "true"

```

The certificate was issued successfully for the domain, and I can connect securely to the server using subdomain.domain.com.

However, after the certificate was issued, I intentionally commented out the hostname field, as I have external customers who need to connect to my server using their own domain names.

I asked them to create a CNAME pointing to subdomain.domain.com, which they did. However, all they’re seeing in the browser is:

```
This site can’t provide a secure connection
subdomain.externalcustomer.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

And I'm not sure where to look.

Below is how I defined the clusterissuer.yaml file:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: example@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: example@gmail.com
            apiKeySecretRef:
              name: cloudflare-credentials
              key: api-key
```

The strange thing is that when I pointed another domain I control to the subdomain.domain.com, it worked seamlessly, even though it’s also not included in the certificate. I'm not sure if this is because both domains are under the same Cloudflare account.

### What did you see instead?

```
This site can’t provide a secure connection
subdomain.externalcustomer.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

### What is your environment & configuration?

Ubuntu, Hetzner Cloud
