### ISSUE TITLE
allowACMEBypass

### ISSUE THREAD

**Issue by mback2k** [traefik/traefik-helm-chart#1245]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

33.0.0

### What version of Traefik are you using?

3.2.0

### What did you do?

I configured `allowACMEByPass: true` on the `web` entrypoint.

### What did you see instead?

Entrypoint name in `Pod` template is hard-coded to `name` and not using variable:
https://github.com/traefik/traefik-helm-chart/blob/218333c7b3406f81fb309900beb9e510921ea54c/traefik/templates/_podtemplate.tpl#L602

### What is your environment & configuration?

```
        service:
          additionalServices:
            internal:
              type: ClusterIP
        ports:
          traefik:
            expose:
              default: false
              internal: true
          web:
            allowACMEByPass: true
            redirectTo:
              port: websecure
              priority: 1
          websecure:
            asDefault: true
```
