### ISSUE TITLE
Plugins do not install when using a PVC for plugins mounted on /plugins-storage

### ISSUE THREAD

**Issue by martinsarrionandia** [traefik/traefik-helm-chart#1261]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v33.0.0

### What version of Traefik are you using?

traefik:v3.2.0

### What did you do?

Install traefik using the helm command line 

```bash
helm repo add traefik https://traefik.github.io/charts
helm repo update

# Install Traefik v3

export TRAEFIK_PLUGINS_PATH=/mnt/traefik-plugins
mkdir $TRAEFIK_PLUGINS_PATH
chown 65532:65532 $TRAEFIK_PLUGINS_PATH
chmod 700 $TRAEFIK_PLUGINS_PATH
semanage fcontext -a -t container_file_t -r s0 $TRAEFIK_PLUGINS_PATH

kubectl create namespace traefik

cat > /root/traefik-volume.yaml << EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-plugins
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: $TRAEFIK_PLUGINS_PATH
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "${acme-domain}"
EOF

kubectl apply -f /root/traefik-volume.yaml

cat > /root/traefik-pvc.yaml << EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: traefik
  name: traefik-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeName: traefik-plugins
EOF

kubectl apply -f /root/traefik-pvc.yaml

helm install --replace traefik traefik/traefik \
  --namespace traefik \
  --set-json deployment.additionalVolumes='[{"name": "plugins","persistentVolumeClaim": {"claimName": "traefik-plugins"}}]' \
  --set-json additionalVolumeMounts='[{"name": "plugins","mountPath": "/plugins-storage"}]' \
  --set providers.kubernetesCRD.enabled=true \
  --set securityContext.seccompProfile.type=RuntimeDefault \
  --set-json service.spec='{"externalTrafficPolicy":"Local"}'
```

Then apply a HelmChartConfig using a terrafrom template.

```yaml
apiVersion: helm.cattle.io/v1

kind: HelmChartConfig
metadata:
  name: traefik
  namespace: traefik
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        enabled: true
    logs:
      general:
        level: "${traefik-log-level}"
      access:
        enabled: "${traefik-access-log}"
    service:
      spec:
        externalTrafficPolicy: "${traefik-external-access-policy}"
    experimental:
      plugins:
        rewrite-body:
          moduleName: "github.com/packruler/rewrite-body"
          version: "v1.2.0"
      crowdsec-bouncer-traefik-plugin:
        moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
        version: "v1.3.5"
```

No plugins are installed. The /plugins-storage is emplty but clearly writable.

```bash
/plugins-storage $ ls -la
total 0
drwx------    2 65532    65532            6 Nov 24 13:20 .
drwxr-xr-x    1 root     root            63 Nov 24 11:40 ..
/plugins-storage $ touch myself
/plugins-storage $ ls -la
total 0
drwx------    2 65532    65532           20 Nov 24 14:00 .
drwxr-xr-x    1 root     root            63 Nov 24 11:40 ..
-rw-r--r--    1 65532    65532            0 Nov 24 14:00 myself
/plugins-storage $ 
```

This works perfectly well with the default emptyDir for the plugins volume.

### What did you see instead?

No plugins are active or installed.

### What is your environment & configuration?

K3S and Rancher (latest) on Centos 9

### Additional Information

```shell

```
