### ISSUE TITLE
value of `providers.kubernetesingress.ingressendpoint.publishedservice` not correct when overriding namespace

### ISSUE THREAD

**Issue by piximos** [traefik/traefik-helm-chart#1289]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

7.7.11

### What version of Traefik are you using?

v3.2.2

### What did you do?

While configuring a local environment, I created a monolithic helm chart that imports and configures dependencies where traefik is one.
I set the `namespaceOverride` config to `traefik`. All resources deployed to the traefik namespace except for value of the `--providers.kubernetesingress.ingressendpoint.publishedservice` arg where it was `default/local-traefik` where default is the helm installation namespace and not the one for traefik.

### What did you see instead?

I expected for the value of `--providers.kubernetesingress.ingressendpoint.publishedservice` to have the namespace I specified `traefik/local-traefik`

### What is your environment & configuration?

I ran a Minikube and deployed helm chart with the following:

```yaml
# file: Chart.yaml

#...

dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.7.11
    alias: argo-cd
    condition: argo-cd.deploy
#...
```

```yaml
# file: Values.yaml
#...

traefik:
  namespaceOverride: traefik
  deploy: true
  ports:
    traefik:
      expose:
        default: true
  service:
    type: NodePort

#...
```

Then I ran: `helm install local . -n default`

### Additional Information

```shell
I believe the issue is due to line 102 in `_helpers.tpl` where instead of being:


{{- $defServiceName := printf "%s/%s" .Release.Namespace (include "traefik.fullname" .) -}}


it should be:


{{- $defServiceName := printf "%s/%s" (include "traefik.namespace" .) (include "traefik.fullname" .) -}}
```
