### ISSUE TITLE
Json schema validation fails when using traefik-crds as chart dependency

### ISSUE THREAD

**Issue by Soortor** [traefik/traefik-helm-chart#1311]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

1.1.0

### What version of Traefik are you using?

34.0.0

### What did you do?

We deploy many of our applications with ArgoCD by defining them as subcharts.
For Traefik this works, but for Traefik-crds this does not as the `additionalProperties` is set to false in the `.schema.yaml`

Example chart.yaml to reproduce:

```
apiVersion: v2
name: traefik-crds
description: Traefik CRDS Helm Chart

version: 1.0.0

dependencies:
  - name: traefik-crds
    version: 1.1.0
    repository: https://traefik.github.io/charts
```

The expectation is that this renders a helm template with default values.

### What did you see instead?

```
$ helm template .
Error: values don't meet the specifications of the schema(s) in the following chart(s):
gateway:
- (root): Additional property global is not allowed
```

### What is your environment & configuration?

ArgoCD

### Additional Information

```shell
Similar issue reported here: https://github.com/helm/helm/issues/10392#issuecomment-1091673838
It appears that helm implicitly injects a global section from the parent chart, which is not allowed by the subchart.
```

**Comment by darkweaver87** [comment]
Hello @Soortor ,

Thanks for reporting this.
Those charts needs to be used separately (cf. https://github.com/traefik/traefik-helm-chart/blob/master/README.md#an-installation-with-additional-crds-chart).
After a lot of tests we intentionally removed the dependency from the original [PR](https://github.com/traefik/traefik-helm-chart/pull/1223).
We will open a PR to detail the reasons so it will be explicit in the README.

Rémi

**Comment by Soortor** [comment]
Instead of loading as a subchart, we ended up loading the chart directly via ArgoCD:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik-crds
    repoURL: https://traefik.github.io/charts
    targetRevision: 1.1.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Comment by darkweaver87** [comment]
I'm glad to see that it works 👍 
I'll let this issue opened to not forgot to create a PR for the documentation part I mentioned :-)

**Comment by cirias** [comment]
Hi! I just ran into the same issue as well. I understand that `additionalProperties` should stay being `false` to prevent the old traefik only values accidentally leaks to this new crds chart. But can we at least add a dummy `global` property, like [this](https://github.com/helm/helm/issues/10392#issuecomment-1513258871), just to unblock people using subchart?

**Comment by darkweaver87** [comment]
Hello @cirias ,

I'll look into it with other maintainers.

Rémi

**Comment by Nitive** [comment]
I faced this problem as well through not when using chart as subchart. I'm installing chart with helmfile and use `global.cluster=<my-cluster>` value for all charts. Unfortunately, it breaks CRDs chart instead of being ignored.

```yaml
helmDefaults:
  kubeContext: my-cluster
  args:
    - "--set global.cluster=my-cluster"

releases:
  - name: crds
    namespace: traefik-ingress-controller
    chart: ../../traefik-ingress-controller-crds
```
