### ISSUE TITLE
Documentation improvement? How to disable tracing

### ISSUE THREAD

**Issue by Lp-Francois** [traefik/traefik-helm-chart#1314]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello 👋 
My current tracing config:

```yaml
...
        metrics:
          prometheus:
            service:
              enabled: true
            serviceMonitor:
              enabled: true
        tracing:
          otlp:
            enabled: true
            http:
              enabled: true
              endpoint: "http://grafana-k8s-monitoring-grafana-agent.monitoring.svc:4318/v1/traces"
```

I noticed traefik reports all calls to /metrics. How can I disable it to report only requests that are meant to be forwarded? ie, requests meant for the reverse proxy.

![Image](https://github.com/user-attachments/assets/7358e7e7-7d39-410a-9e4b-2b99511ccbd7)
