### ISSUE TITLE
Allow to configure tlsOptions annotations

### ISSUE THREAD

**Issue by M0NsTeRRR** [traefik/traefik-helm-chart#1317]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I've deployed two traefik, one for internal services and one for external services.
I'm setting in both `values.yaml`
```
providers:
  kubernetesCRD:
    ingressClass: <ingress-class>
tlsOptions:
  default:
    minVersion: VersionTLS12
    cipherSuites:
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    sniStrict: true
```
I want each Helm chart to have its own manifests and setup. If I remove one, the other should not be impacted. Currently, I can't set annotations to allow each chart to look for its own TLS options, and I am receiving the error below (I can't restrict the namespace because some manifests are deployed in different namespaces).
```
2025-01-21T23:47:09Z ERR Default TLS Options defined in multiple namespaces: [ingress-external ingress-internal] providerName=kubernetescrd                                                                                                                2025-01-21T23:47:10Z ERR Default TLS Options defined in multiple namespaces: [ingress-internal ingress-external] providerName=kubernetescrd
```

I can implement it if it's accepted.
