### ISSUE TITLE
permanent redirect annotation not added if permanent: false

### ISSUE THREAD

**Issue by lutz108** [traefik/traefik-helm-chart#1318]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

34.1.0

### What version of Traefik are you using?

v3.3.2

### What did you do?

I wanted to update to the current chart version, which included the [move redirectTo => redirections](https://github.com/traefik/traefik-helm-chart/pull/1301) breaking change. As I used the redirect for http->https, I did not want to have a permanent redirect, so i set the parameter `permanent: false`. 

### What did you see instead?

The result was, the traefik pod annotation `--entryPoints.web.http.redirections.entryPoint.permanent=false` was missing. If I set `permanent: true` I get

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-traefik
  namespace: default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: release-name-default
    helm.sh/chart: traefik-34.1.0
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: release-name-default
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9100"
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: release-name-default
        helm.sh/chart: traefik-34.1.0
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-traefik
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      containers:
      - image: docker.io/traefik:v3.3.2
        imagePullPolicy: IfNotPresent
        name: release-name-traefik
        resources:
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        lifecycle:
        ports:
        - name: "metrics"
          containerPort: 9100
          protocol: "TCP"
        - name: "traefik"
          containerPort: 9000
          protocol: "TCP"
        - name: "web"
          containerPort: 8000
          hostPort: 8000
          protocol: "TCP"
        - name: "websecure"
          containerPort: 8443
          protocol: "TCP"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: data
            mountPath: /data
          - name: tmp
            mountPath: /tmp
        args:
          - "--global.checknewversion"
          - "--global.sendanonymoususage"
          - "--entryPoints.metrics.address=:9100/tcp"
          - "--entryPoints.traefik.address=:9000/tcp"
          - "--entryPoints.web.address=:8000/tcp"
          - "--entryPoints.websecure.address=:8443/tcp"
          - "--api.dashboard=true"
          - "--ping=true"
          - "--metrics.prometheus=true"
          - "--metrics.prometheus.entrypoint=metrics"
          - "--providers.kubernetescrd"
          - "--providers.kubernetescrd.allowEmptyServices=true"
          - "--providers.kubernetesingress"
          - "--providers.kubernetesingress.allowEmptyServices=true"
          - "--providers.kubernetesingress.ingressendpoint.publishedservice=default/release-name-traefik"
          - "--entryPoints.web.http.redirections.entryPoint.to=:443"
          - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
          - "--entryPoints.web.http.redirections.entryPoint.permanent=true" # exists only for permanent: true
          - "--entryPoints.websecure.http.tls=true"
          - "--log.level=INFO"

        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
```

Where the last line will be missing.

### What is your environment & configuration?

the charts values.yaml
used to render the output above via `helm template . --debug`
```yaml
traefik:
  service:
    enabled: true
  [...]

  ports:
    traefik:
      port: 9000
    web:
      port: 8000
      hostPort: 8000
      expose:
        default: true
      exposedPort: 80
      protocol: TCP
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true | false
```

### Additional Information

```shell
the `with` flow control does not seem to perform the scope, when the variables value is "false". From Go and [Helm Flow Control docu](https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with), I just found the statement, that "[...] the block after with only executes if the value of PIPELINE is not empty." However testing showed me, that false is also not evaluated.

If the annotation is not present, traefik will fall back to the default, which is again [permanent: true](https://doc.traefik.io/traefik/routing/entrypoints/).

So how would I achieve having a non permanent redirect?
```
