### ISSUE TITLE
Documentation for setting up behind an Azure Application Gateway?

### ISSUE THREAD

**Issue by Poltergeisen** [traefik/traefik-helm-chart#1381]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What do you want to achieve with this Chart ?

Hello, 

I have seen a lot of questions on the traefik forums about how to set this up behind and azure application gateway. I see some documentation with a google gateway.

Can you please provide some documentation in the examples.md file, or even in this issue itself? I've tried many things currently, but nothing is working to allow the health probes to connect to the traefik pod and get a healthy response.

Thank you!

https://community.traefik.io/t/application-gateway-health-probe-failing-502-with-traefik-as-backend/26920

https://community.traefik.io/t/aks-cluster-traefik-as-ingress-controller-and-an-application-gateway-doing-the-tls-termination/15854

https://community.traefik.io/t/aks-traefik-behind-azure-app-gateway/25056

**Comment by Poltergeisen** [comment]
It's really weird... I'm not sure if this is a traefik issue or an app gateway issue. 

The app gateway cant connect to port 8000 on the pod IP. If I substitute the load balancer IP on the backend it works, but it's not possible for app gateway at this time to do that.

I'll try to see if I can come up with a solution, but definitely looking for help if someone has done this before. I will do a PR to update the documentation if I figure it out and it's something easy with the helm chart that I can set.

**Comment by dkrizic** [comment]
I just see your issue. I am running Traefik on Azure AKS (but not behind the Azure Application Gateway). I needed those settings to make the Load Balancer "green":

```
service:
  single: true
  spec:
    externalTrafficPolicy: "Local"
  annotations:
    service.beta.kubernetes.io/port_80_health-probe_protocol: "http"
    service.beta.kubernetes.io/port_80_health-probe_port: "8080" # Must match ports.traefik.port
    service.beta.kubernetes.io/port_80_health-probe_request-path: "/ping"
    service.beta.kubernetes.io/port_443_health-probe_protocol: "http"
    service.beta.kubernetes.io/port_443_health-probe_port: "8080" # Must match ports.traefik.port
    service.beta.kubernetes.io/port_443_health-probe_request-path: "/ping"
    service.beta.kubernetes.io/port_8080_no_lb_rule: "true" # Do not create a load balancer rule for port 8080
```

<img width="713" height="998" alt="Image" src="https://github.com/user-attachments/assets/890e5e47-bf90-44dd-9463-1c0dfd813045" />

Maybe this helps
