### ISSUE TITLE
additionnalServices doesn't create new ReplicaSet/DaemonSet

### ISSUE THREAD

**Issue by TsengSR** [traefik/traefik-helm-chart#1426]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-35.3.0

### What version of Traefik are you using?

3.4.0

### What did you expect to happen ?

I wanted setup traefik with two gateways, for internal and external traefik. After trying for a few days, I came accross `additionalServices` and tried this attempt. 

Everything gets up, i can reach 80, 443, 8080 and 8443 ports, the correct certificates for each are passed. But the gateways kept getting the wrong ip assigned (from the first defined gateway)

I expected to see two different pods within eacah of the service, but instead they shared the same pod. And the IPs of the both gateways were of the main, external gateway. 



### What did you notice instead ?


The services get the correct IP from their metallb pools too, 192.168.0.80 (internal) and 192.168.0.90 (external). 

```bash
NAME               TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                        AGE   SELECTOR
traefik            LoadBalancer   10.110.3.211   192.168.0.90   80:30128/TCP,443:32560/TCP                     20h   app.kubernetes.io/instance=traefik-traefik,app.kubernetes.io/name=traefik
traefik-internal   LoadBalancer   10.105.53.28   192.168.0.80   8081:32057/TCP,8080:30635/TCP,8443:31865/TCP   48m   app.kubernetes.io/instance=traefik-traefik,app.kubernetes.io/name=traefik
```

But the gateways, get wrong ips assigned

```bash
NAME                       CLASS              ADDRESS        PROGRAMMED   AGE
traefik-gateway            traefik            192.168.0.90   True         20h
traefik-gateway-internal   traefik-internal   192.168.0.90   True         20h
```
while fiddling around, I found out that both services reference to the same pod. So there is only one pod running for BOTH services. 

Looking closer at it, there is also only one replica set. Looking further, both services have 

```yaml                                                                                                                                                                                                                                    selector:
   app.kubernetes.io/instance: traefik-traefik
   app.kubernetes.io/name: traefik
```

as selector and only one replica which manages the one pod. Hence both services show this pod as their own. 

I think this is a bug and additional services should generate additional replica sets and have the `traefik-traefk-internal` instance name on it so they are assigned to the additional service (with the name `internal`), as I don't see any added value in a service which doesnt run pods on its own. 

Imho the helm chart needs to be adjusted to create a ReplicaSet (or DaemonSet depending on service.kind value) and each run their own pods. 

Since I did further experimenting, like installing two instances of traefik in two namespaces, I encountered a lot of issues, like both traefik gateways still getting the same IP address. Until I came accross `providers.kubernetesGateway.labelselector` and set it to `"app.kubernetes.io/instance=traefik-traefik"` and `"app.kubernetes.io/instance=traefik-traefik-internal"` respectively. Then the gateways got the same IP assigned.

Since the `providers.kubernetesGateway.labelselector` is passed as an "--" argument to the pod instance, one instance can't handle both gateways it seems, so for this setup to work and `services.additionalServices` be useful at all, the pods must run in different replica sets and have a configurable labelselector passed to it in order for it to work.


That asside I also noticed that in this two-gateway setup (with one instance in one namespace or two instances in two namespaces) I encounted issues with the headers passed. 

Sometimes whoami test container returns my correct IP

```
X-Forwarded-For: 192.168.0.3
X-Forwarded-Host: whoami.xyz.external
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-698f459f5d-fqtjz
X-Real-Ip: 192.168.0.3
```
and sometimes it returns the kubernetes internal IP 
```
X-Forwarded-For: 10.x.x.x
X-Forwarded-Host: whoami.xyz.external
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik-698f459f5d-fqtjz
X-Real-Ip: 10.x.x.102
```

I couldn't find out which resource was using that IP, it was none of the pods or services. This is very irritating as it brings undefined behavior in applications relying on these to get the correct original IP. 


### What are your values ?


```yaml
global:
  sendAnonymousUsage: false
providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
ports:
  web:
    exposedPort: 80
    port: 9000
  websecure:
    exposedPort: 443
    port: 9443
  web-int:
    exposedPort: 8080
    expose:
      default: false
      internal: true
    port: 9001
  websecure-int:
    exposedPort: 8443
    expose:
      default: false
      internal: true
    port: 9444
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs: 10.0.0.0/8
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs: 10.0.0.0/8
  web-int:
    address: ":8080"
    forwardedHeaders:
      trustedIPs: 10.0.0.0/8
  websecure-int:
    address: ":8443"
    forwardedHeaders:
      trustedIPs: 10.0.0.0/8
gateway:
  enabled: true
  namespacePolicy: All
  annotations:
    cert-manager.io/issuer: my-issuer
  listeners:
    web:
      protocol: HTTP
      port: 9000
      namespacePolicy: All
    websecure:
      port: 9443
      protocol: HTTPS
      certificateRefs:
        - name: my-public-certificate
      namespacePolicy: All
service:
  annotations:
    metallb.io/address-pool: homelab-pool
  additionalServices:
    internal:
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: homelab-internal-pool
      ports:
        web-int:
          port: 9001 # 8080
          exposedPort: 8080
        websecure-int:
          port: 9444
          exposedPort: 8443
      labels:
        app.kubernetes.io/instance: traefik-internal
        traefik-service-label: internal
      labelSelector:
        app.kubernetes.io/instance: traefik-internal
        traefik-service-label: internal

extraObjects:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: GatewayClass
    metadata:
      name: traefik-internal
      namespace: traefik
    spec:
      controllerName: traefik.io/gateway-controller
  - apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: traefik-gateway-internal
      namespace: traefik
      labels:
        app.kubernetes.io/instance: traefik-internal
        traefik-service-label: internal
    spec:
      gatewayClassName: traefik-internal
      listeners:
        - name: web-int
          allowedRoutes:
            namespaces:
              from: All
          protocol: HTTP
          port: 9001
        - name: websecure-int
          allowedRoutes:
            namespaces:
              from: All
          protocol: HTTPS
          port: 9444
          tls:
            mode: Terminate
            certificateRefs:
              - name: my-homelab-certificate
                kind: Secret
                group: ""

additionalArguments:
  - "--global.sendAnonymousUsage=false"
```

deploying it with 

```bash
helm upgrade --install traefik traefik/traefik \
  --namespace traefik \
  -f traefik.yaml
```

### Additional Information

```shell

```

**Comment by TsengSR** [comment]
On top of that it seems the Helm Chart adds default endpoints, even when one sets their own in the values.yaml. I tried to install two traefik instances in two namespaces and the chart ended up adding `web` and `websecure` ports to the pod too despite nothing being in the values.yaml

```yaml
log:
  level: DEBUG
global:
  sendAnonymousUsage: false
deployment:
  replicas: 1
ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik-internal
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.atomicgear.local`)
    entryPoints: ['websecure-int']
providers:
  kubernetesIngress:
    enabled: false
    ingressClass: traefik-internal
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
    statusAddress:
      service:
        enabled: true
        name: traefik
        namespace: traefik-internal
    labelselector: "app.kubernetes.io/instance=traefik-traefik-internal"
ports:
  web-int:
    exposedPort: 8080
    port: 9001
  websecure-int:
    exposedPort: 8443
    port: 9444
entryPoints:
  web-int:
    address: ":80"
  websecure-int:
    address: ":443"
service:
  annotations:
    metallb.io/address-pool: homelab-internal-pool
gateway:
  enabled: true
  name: traefk-gateway-internal
  namespacePolicy: All
  annotations:
    cert-manager.io/issuer: atomicgear-issuer
  listeners:
    web-int:
      protocol: HTTP
      port: 9001
      namespacePolicy: All
    websecure-int:
      port: 9444
      protocol: HTTPS
      certificateRefs:
        - name: my-homelab-certificate
      namespacePolicy: All
gatewayClass:
  enabled: true
  name: traefik-internal

additionalArguments:
  - "--api.dashboard=true"
  - "--global.sendAnonymousUsage=false"
  - "--entryPoints.web-int.forwardedHeaders.trustedIPs=10.0.0.0/8"
  - "--entryPoints.websecure-int.forwardedHeaders.trustedIPs=10.0.0.0/8"
```

would have this parameters in the deployment:

```
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage  # set here, even though its set to false via additionalArguments
        - --entryPoints.metrics.address=:9100/tcp   # not defiend in values.yaml
        - --entryPoints.traefik.address=:8080/tcp  # not defiend in values.yaml
        - --entryPoints.web.address=:8000/tcp  # not defiend in values.yaml
        - --entryPoints.web-int.address=:9001/tcp
        - --entryPoints.websecure.address=:8443/tcp  # not defiend in values.yaml
        - --entryPoints.websecure-int.address=:9444/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics # metric endpoint not defined in the values.yaml
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowEmptyServices=true
        - --providers.kubernetesgateway
        - --providers.kubernetesgateway.statusaddress.service.name=traefik
        - --providers.kubernetesgateway.statusaddress.service.namespace=traefik-internal
        - --providers.kubernetesgateway.experimentalchannel=true
        - --providers.kubernetesgateway.labelselector=app.kubernetes.io/instance=traefik-traefik-internal
        - --entryPoints.websecure.http.tls=true                             # not defiend in values.yaml
        - --log.level=INFO
        - --api.dashboard=true
        - --global.sendAnonymousUsage=false
        - --entryPoints.web-int.forwardedHeaders.trustedIPs=10.0.0.0/8
        - --entryPoints.websecure-int.forwardedHeaders.trustedIPs=10.0.0.0/8
```

When I tested the dashboard ended up in the wrong instance.

![Image](https://github.com/user-attachments/assets/d453e91f-1fbd-42c8-9039-0ed24198d524)
This was on the external traefiks dashboard where the internal one didn't had either

They were defined in the values.yaml as

```yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.xyz.local`)
    entryPoints: ['websecure-int']
```

and 

```yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.xyz.external`)
    entryPoints: ['websecure']
```

respectively

**Comment by mloiseleur** [comment]
Please open simple issue with minimal yaml and expected results.

1. additionalServices is, FTM, a feature allowing to generate the YAML for:
> An additional and optional internal Service.

([source](https://github.com/traefik/traefik-helm-chart/blob/2a7e2e8202dff4a6bb749a07a4299e41cebab30d/traefik/values.yaml#L801))

Nothing less, nothing more.

2. This is an expected behavior. See default [values](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml). One can set un-wanted default values to null.

**Comment by mloiseleur** [comment]
>  It doesn't seem very well tested (or documented) 

I kindly invite you to take a look at our [Code of Conduct](https://github.com/traefik/traefik/blob/master/CODE_OF_CONDUCT.md) and the current [code base on tests](https://github.com/traefik/traefik-helm-chart/tree/master/traefik/tests).

This is a community driven project. Your help is welcome. 

> But how are the gateways then supposed to get the correct ips?

Isn't this is a configuration issue ? Does my answer about this part was not clear ? 

On nullifying, with this values:

```yaml
ports:
  web: null
  websecure: null
```

It produces this error message:

```console
$ helm template test -f test.yaml traefik/traefik
Error: execution error at (traefik/templates/service.yaml:40:6): ERROR: Cannot create Service test-traefik without ports
```

It's an expected error message, there is no port to expose and values are asking to create a `Service` (`service.enabled` is [set to true](https://github.com/traefik/traefik-helm-chart/blob/2a7e2e8202dff4a6bb749a07a4299e41cebab30d/traefik/values.yaml#L766) by default)

As an example, to expose only a 400/tcp port named _tcp400_, with this values:

```
ports:
  web: null
  websecure: null
  tcp400:
    port: 400
    expose:
      default: true
```

it produces the expected yaml for the `Service`:

```yaml
---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-traefik
  namespace: flux-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: test-flux-system
    helm.sh/chart: traefik-35.4.0
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: test-flux-system
  ports:
  - port: 400
    name: tcp400
    targetPort: tcp400
    protocol: TCP
```

and the expected pod arguments:

```yaml
        args:
          - "--global.checknewversion"
          - "--global.sendanonymoususage"
          - "--entryPoints.metrics.address=:9100/tcp"
          - "--entryPoints.tcp400.address=:400/tcp"
          - "--entryPoints.traefik.address=:8080/tcp"
          - "--api.dashboard=true"
          - "--ping=true"
          - "--metrics.prometheus=true"
          - "--metrics.prometheus.entrypoint=metrics"
          - "--providers.kubernetescrd"
          - "--providers.kubernetescrd.allowEmptyServices=true"
          - "--providers.kubernetesingress"
          - "--providers.kubernetesingress.allowEmptyServices=true"
          - "--providers.kubernetesingress.ingressendpoint.publishedservice=flux-system/test-traefik"
          - "--log.level=INFO"
```

Does that answer your question ?
