### ISSUE TITLE
Errors when defining more than 1 ingress route in values.yaml

### ISSUE THREAD

**Issue by TsengSR** [traefik/traefik-helm-chart#1427]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-35.4.0

### What version of Traefik are you using?

3.4.0

### What did you expect to happen ?

While debugging/trying to get the dashboard exposed on both my internal and external gateways, I first tried with a single route but two different entrypoints (websecure and websecure-internal) which only had tls enabled on one but not on other and only the external one was accessible. 

So one of my attempts was to define two ingress routes for the dashboard

```yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.example.external`)
    entryPoints: ['websecure']
    tls:
      secretName: my-homelab-certificates
  dashboard-internal:
    enabled: true
    matchRule: Host(`traefik.example.local`)
    entryPoints: ['websecure-int']
    tls:
      secretName: my-homelab-certificates
```

This throw an error 

> Error: template: traefik/templates/ingressroute.yaml:7:57: executing "traefik/templates/ingressroute.yaml" at <$config.annotations>: wrong type for value; expected map[string]interface {}; got interface {}

Then I added empty annotations

```yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.example.external`)
    entryPoints: ['websecure']
    tls:
      secretName: my-homelab-certificates
    annotations: {}
  dashboard-internal:
    enabled: true
    matchRule: Host(`traefik.example.local`)
    entryPoints: ['websecure-int']
    tls:
      secretName: my-homelab-certificates
    annotations: {}
```

And got

> Error: template: traefik/templates/gateway.yaml:31:15: executing "traefik/templates/gateway.yaml" at <eq $portConfig.port $config.port>: error calling eq: incompatible types for comparison

### What did you notice instead ?

With only one entry, it works w/o any errors

```yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.example.external`)
    entryPoints: ['websecure']
    tls:
      secretName: my-homelab-certificates
```

### What are your values ?

```yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.example.external`)
    entryPoints: ['websecure']
    tls:
      secretName: my-homelab-certificates
  dashboard-internal:
    enabled: true
    matchRule: Host(`traefik.example.local`)
    entryPoints: ['websecure-int']
    tls:
      secretName: my-homelab-certificates
```

Rest is irrelevant and can be even a simple most simplest setup. The TLS can be removed and entry "web" used instead of "web-int" 

### Additional Information

```shell
The `ingressRoutes` clearly is defined as a list of objects, so the usecase should work. Especially since none of the linked errors were related to any of the set fields and none appear, when only one entry is there.
```
