### ISSUE TITLE
How to host and access dashboards from multiple traefiks in one namespace ?

### ISSUE THREAD

**Issue by den-is** [traefik/traefik-helm-chart#143]
Not sure if I have had to post that issue in original traefik repo or here in chart repo.

TLDR: How to serve dashboards from multiple ingress-controllers (traefiks) using single Ingress-controller dedicated for serving these dashboards?

With traefik 1.7 I have multiple ingress controllers deployed in the kube-system namespace. Each is for different purposes - mainly monitoring its own subset of namespaces.
There is one main Traefik in the kube-system namespace, which is serving only "internal" cluster, administrative ingress objects. dashboards, grafanas, etc.
Every other traefik-dashboard is exposed by own Ingress object which is then intercepted by that administrative-traefik. So each dashboard has own URL: traefik-x.example.com traefik-y.example.com.

How to achieve same with traefik v2?

What are the best or "all possible" ways to access dashboard in traefik v2?

1. Port forwarding suggested here https://github.com/containous/traefik-helm-chart/issues/85#issuecomment-598347705 doesn't work without IngressRoute. Is that intentional and how that works? 
2. I was trying to expose using NodePort only and it didn't work without IngressRoute definition. kubectl-proxy didn't work too.
3. I was able to expose Dashboard using default `web` entrypoint and it did work.
But "service" points  to some api@internal TraefikService. here is my IngressRouter
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: admin-ing-dashboard
  labels:
    app: traefik
    release: admin-ing
spec:
  entryPoints:
  - web
  # - traefik
  routes:
  - match: Host(`admin-ing.test`)
    kind: Rule
    services:
    # - name: admin-ing-dashboard
    #   port: 9000
    - name: api@internal
      kind: TraefikService
```
But some other traefik will be pointing to the same `api@internal`. How to make traefik understand that I'm requesting dashboard of some other traefik deployment?
For example next I want to setup `default-ing` traefik which will be serving public apps in default namespace.
Again. I have tried to create individual service `admin-ing-dashboard` for exposing dashboard only. But it didn't work.

Is that possible at all? How to view the other traefik dashboard on the same cluster?

**Comment by mmatur** [comment]
Hi @den-is ,

Thanks for your question.

This is not a common use case. 

Today with the helm chart you have multiple possibilities to expose a Traefik dashboard.

1. Port forwarding, the IngressRoute is required. https://docs.traefik.io/operations/dashboard/#dashboard-router-rule
2. Expose using a NodePort and `--api.insecure=true` flag (not recommended in production) https://docs.traefik.io/operations/dashboard/#dashboard-router-rule

To achieve your needs, that is not a common use case, one possibility is to:

- Deploy all your Traefik instances with the values.yaml:
```yaml
additionalArguments: 
  - "--api.insecure=true"
```

- For each Traefik instances create manually a Kubernetes service like that:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-a-dashboard
  namespace: traefik-a
  labels:
    app.kubernetes.io/name: name
    app.kubernetes.io/instance: ReleaseName
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: traefik
  selector:
     app.kubernetes.io/name: name
     app.kubernetes.io/instance: ReleaseName
```

- And for each Traefik instances create the associated IngressRoute

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-a-dashboard
spec:
  entryPoints:
    - traefik
  routes:
    - match: Host(`traefik-a-dashboard.example.com`)
      kind: Rule
      services:
        - name: traefik-a-dashboard
           port: 9000
```

I will close this issue because I think that your question is answered.

Please join our [Community Forum](https://community.containo.us/) on the [Traefik section](https://community.containo.us/c/traefik) if you are further questions.
