### ISSUE TITLE
Add support for prometheus ServiceMonitor

### ISSUE THREAD

**Issue by arlyon** [traefik/traefik-helm-chart#156]
It would be nice to be able to be able to include a CRD for a prometheus service monitor with the chart.

**Comment by SantoDE** [comment]
Hello @arlyon,

as previously stated, up until know we declined feature requests like that. However, I'd like to acknowledge that we started some discussions around that topic, as we see that you, our community has a demand for it.

So for now, no real updates on it but please be aware, we're talking over it.

**Comment by r3kzi** [comment]
Since then you can use the `additionalServiceMonitors` feature in the Prometheus-Operator. That's what we are using right now.

```
prometheus:
  additionalServiceMonitors:
    - name: traefik
      selector:
        matchLabels:
      ...
```
