### ISSUE TITLE
helm chart should support protocol field while configuring traefik service by ports

### ISSUE THREAD

**Issue by viveksatasiya** [traefik/traefik-helm-chart#172]
Hello,

I wanted to terminate tls connection on AWS ELB using aws certificate manager. So I added annotations to the traefik service to add certificate arn into load balancer. It added tls certificates successfully and created two listeners in aws elb. One for port 80(web) and another for 443(websecure) but listener protocol for `web` had been changed to 'SSL' whose port is 80. So it was not forwarding my regular HTTP traffic to the traefik service. So I just changed the listener protocol from 'SSL' to 'TCP' and it worked. 

So I think that helm chart should support protocol configuration for traefik ports so that SSL protocol can be only bound to 443 port in the AWS ELB.

Let me know If I was making any mistake.

Thanks.

**Comment by dennisroche** [comment]
> just changed the listener protocol from 'SSL' to 'TCP' and it worked.

sorry don't understand; where did you change this?

**Comment by viveksatasiya** [comment]
I changed listener protocol into classic load balancer configuration via AWS console.

**Comment by Mhs-220** [comment]
Hi, I had the same problem for a long long time since v1.7 and figured that out that Kubernetes create an ELB and set Health check port to first ports that defined in service and as it's sort base on the alphabet, it will set to the web.
Is there a chance to define order using helm?

for example:
```yaml
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
      nodePort: 31502
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: websecure
      nodePort: 31714
```
should be:
```yaml
spec:
  ports:
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: websecure
      nodePort: 31714
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
      nodePort: 31502
```
if you wanna set `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https` in service annotations. or it will be failed.

**Comment by haghabozorgi** [comment]
I just wanted to add, I am not sure if it is the exact same issue, but  I have a similar issue where setting annotations on the traefik service for elb does not work properly. You end up with a elb deployed as expected, but with listeners for `80` and `443` but both are HTTP for "Load Balancer Protocol", which is wrong since 443 should be HTTPS and the ACM cert should be attached to that listener.

Note: I am also using the helm chart from https://github.com/traefik/traefik-helm-chart, so my snippet looked like 
```
service:
  enabled: true
  type: "LoadBalancer"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "traefik.example.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "$ARNOFMYCERT"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
``` 

What I found is changing the `web` and `websecure` to `http` and `https` respectively seems to solve this issue. Not sure if the issue I am running across needs some docs to make it clear or if there is something else that needs to be done to address.

```
service:
  enabled: true
  type: "LoadBalancer"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "traefik.example.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "$ARNOFMYCERT"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
ports:
  http:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  https:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
```
