### ISSUE TITLE
Topic: Metrics options worth adding

### ISSUE THREAD

**Issue by dirtycajunrice** [traefik/traefik-helm-chart#238]
Initial Proposal:
```yaml
# Metrics
# https://docs.traefik.io/v2.2/observability/metrics/overview/
metrics:
  prometheus:
    # To enable Prometheus
    enabled: false
    # Buckets for latency metrics. Optional, Default="0.100000, 0.300000, 1.200000, 5.000000"
    buckets: "0.100000, 0.300000, 1.200000, 5.000000"
    # Enable metrics on entry points. Optional, Default=true
    addEntryPointsLabels: true
    # Enable metrics on services. Optional, Default=true
    addServicesLabels: true
    # Entry point used to expose metrics. Optional, Default=traefik
    entryPoint: traefik
    # If manualRouting is true, it disables the default internal router in
    # order to allow one to create a custom router for the prometheus@internal service.
    # Optional, Default=false
    manualRouting: false
  influxdb:
    # To enable InfluxDB
    enabled: false
    # Address instructs exporter to send metrics to influxdb at this address.
    # Required, Default="localhost:8089"
    address: "localhost:8089"
    # InfluxDB's address protocol (udp or http). Required, Default="udp"
    protocol: udp
    # InfluxDB database used when protocol is http. Optional, Default=""
    database: ""
    # InfluxDB retention policy used when protocol is http. Optional, Default=""
    retentionPolicy: ""
    # InfluxDB username (only with http). Optional, Default=""
    username: ""
    # InfluxDB password (only with http). Optional, Default=""
    password: ""
    # Enable metrics on entry points. Optional, Default=true
    addEntryPointsLabels: true
    # Enable metrics on services. Optional, Default=true
    addServicesLabels: true
    # The interval used by the exporter to push metrics to influxdb. Optional, Default=10s
    pushInterval: 10s
  datadog:
    # To enable Datadog
    enabled: false
    # Address instructs exporter to send metrics to datadog-agent at this address.
    # Required, Default="127.0.0.1:8125"
    address: "127.0.0.1:8125"
    # Enable metrics on entry points. Optional, Default=true
    addEntryPointsLabels: true
    # Enable metrics on services. Optional, Default=true
    addServicesLabels: true
    # The interval used by the exporter to push metrics to datadog-agent. Optional, Default=10s
    pushInterval: 10s
  statsd:
    # To enable StatsD
    enabled: false
    # Address instructs exporter to send metrics to statsd at this address.
    # Required, Default="localhost:8125"
    address: "localhost:8125"
    # Enable metrics on entry points. Optional, Default=true
    addEntryPointsLabels: true
    # Enable metrics on services. Optional, Default=true
    addServicesLabels: true
    # The interval used by the exporter to push metrics to datadog-agent. Optional, Default=10s
    pushInterval: 10s
    # The prefix to use for metrics collection. Optional, Default="traefik"
    prefix: traefik
```

What do yall think is not needed?
