### ISSUE TITLE
Enable tls for websecure in arguments

### ISSUE THREAD

**Issue by rony36** [traefik/traefik-helm-chart#248]
From traefik 2.2,  [the TLS section in a Ingress don't control the activation of the TLS](https://github.com/containous/traefik/pull/6504).

To enable TLS:
* use the TLS configuration on the entry point
* use annotation traefik.ingress.kubernetes.io/router.tls: "true"

I suggest enable tls on the entryp point.
That will be eazier to migrate from other ingress controller to treafik.

For example:
```
additionalArguments:                                                                                                                                                                                               
  - "--entryPoints.websecure.http.tls=true"
```
Or an additional tls config in values.yaml:
```
  websecure:                                                                                                                                                                                                       
    port: 8443                                                                                                                                                                                                     
    # hostPort: 8443                                                                                                                                                                                               
    expose: true                                                                                                                                                                                                   
    exposedPort: 443                                                                                                                                                                                               
    # The port protocol (TCP/UDP)                                                                                                                                                                                  
    protocol: TCP                                                                                                                                                                                                  
    # nodePort: 32443
    tls: true 
```
