### ISSUE TITLE
Defining namespace in the command "helm template" doesn't add namespace to metadata

### ISSUE THREAD

**Issue by fheinonen** [traefik/traefik-helm-chart#252]
Defining namespace in the command in `helm template` doesn't add namespace metadata in the generated files. I'm using helm version 3.2.4.
Here's the commands I ran:

```
helm fetch traefik/traefik --version 9.1.0
```
```
helm template traefik-9.1.0.tgz --output-dir . -f ~/kubernetes-charts/traefik.yml --name-template traefik --namespace traefik --include-crds
```
Here's a snippet of the deployment.yaml and no namespace is added to the metadata of the generated file:
```
---
# Source: traefik/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
  annotations:
spec:
```
