### ISSUE TITLE
Peristence permission problems 660, should be 600

### ISSUE THREAD

**Issue by zzvara** [traefik/traefik-helm-chart#257]
Deployed as:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-default
  namespace: kube-system
spec:
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 9.1.0
  releaseName: traefik-default
  values:
    ingressRoute:
      dashboard:
        enabled: false
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 100Mi
      storageClass: "ceph-replicated"
      path: /data
      annotations: {}
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    additionalArguments:
      - "--serverstransport.maxidleconnsperhost=10"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.dns-cloudflare.acme.dnschallenge.delaybeforecheck=60"
      - "--certificatesresolvers.dns-cloudflare.acme.email=redacted"
      - "--certificatesresolvers.dns-cloudflare.acme.storage=/data/dns-cloudflare.json"
      - "--certificatesresolvers.tls.acme.tlschallenge=true"
      - "--certificatesresolvers.tls.acme.email=redacted"
      - "--certificatesresolvers.tls.acme.storage=/data/tls.json"
      - "--providers.kubernetescrd.throttleduration=15"
    ports:
      traefik:
        expose: true
      web:
        port: 30080
        nodePort: 30080
      websecure:
        port: 30443
        nodePort: 30443
    service:
      type: NodePort
    resources:
      requests:
        cpu: "500m"
        memory: "100Mi"
      limits:
        cpu: "1000m"
        memory: "250Mi"
```

When the Pod restarts, certificate resolvers like `tls` and `dns-cloudflare` refuse to work. Logs indicate that files under /data are with permission 660, but Traefik/ACME library requires 600. The Pod works when it starts the first time, every time, then it fails in every consecutive restart.
