### ISSUE TITLE
labelSelector field for kuberneteingress provider

### ISSUE THREAD

**Issue by tardich** [traefik/traefik-helm-chart#264]
labelSelector allows to decide wheter an ingress should be managed by traefik or not (ingress controller selection). Right now, the only to achieve this is through the additionalArguments, but should rather be available directly under the provider section, such as:

```
providers:
  kubernetesIngress:
    enabled: true
    labelSelector: A and not B
```
