### ISSUE TITLE
Unable to install traefik v2 as a dependency in the helm chart.

### ISSUE THREAD

**Issue by kiranbaddi** [traefik/traefik-helm-chart#268]
I am using traefik v1 helm chart as a dependency within my helm chart.

```
dependencies:
- name: traefik

  version: '1.87.1'
  repository: 'https://kubernetes-charts.storage.googleapis.com'

```
I am not able to find the documentation to use traefik v2 in the same way. The official documentation doesn't help much. Could you please help me with this?

Thanks in Advance.

**Comment by DirtyCajunRice** [comment]
```
dependencies:
  - name: traefik
    version: 9.3.0
    repository: https://helm.traefik.io/traefik
```
