### ISSUE TITLE
ssl redirect prevents cert-manager http challenge with k8s ingress

### ISSUE THREAD

**Issue by monotek** [traefik/traefik-helm-chart#276]
Traefik chart version: 9.3.0

For a smooth update from traefik 1 to trafik 2.x i still want to use k8s ingress instead of traefiks ingress route crd.

The only way i know to configure k8s ingress redirect via the chart is with the config of traefik and my grafana ingress config shown below.

The problem is that cert-manager creates another ingress for the http acme challenge, to get the cert, which is now ssl redirected too.

ACME server tries to reach the .well-known/... path but gets an redirect and therefore it does not work.

How to solve this?

My helm values look like:

```
    deployment: 
      replicas: 2
      podAnnotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
          pathOverride: "infra/traefik"

    service:
      spec:
        loadBalancerIP: "1.2.3.4"

    additionalArguments: 
      # permanent redirecting of all requests on http (80) to https (443)
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # prometheus
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--metrics.prometheus.entryPoint=traefik"
      - "--metrics.prometheus.manualRouting=false"

    ports: 
      websecure:
        port: 443

    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0

    # Pod disruption budget
    podDisruptionBudget: 
      enabled: true
      minAvailable: 1

    ingressRoute:
      dashboard:
        enabled: false
```

My ingress config looks like:

```
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: 'true'
        kubernetes.io/tls-acme: 'true'
      hosts:
        - grafana.domain.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.domain.com
```
