### ISSUE TITLE
Service template is broken

### ISSUE THREAD

**Issue by bastienbc** [traefik/traefik-helm-chart#279]
Hi,

When I install traefik on EKS 1.17 with helm v3, the service created has no annotations except for the one created by helm.
When I use the --dry-run option I can see that the service.yaml file generated is as expected, with the correct annotations in it.

I think that using the kind List to create 2 services is the problem, because List is a type created for the server to return a json with a list of items, it is not really intended to create multiple resources. There maybe no support for annotations (and maybe more?) at creation.
The chart should simply put 2 documents in a single yaml file using "---".

The modification has been brought with the commit 4a1e6f9708bb3d3a187505e4e1dbf3e3cf800270.

Edit:
It is not BROKEN.
What happens is more subtle than I thought:
Usually I write `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true` and it works fine.
Here I don't know why but the yaml parser did not liked the boolean true so the annotations section was completely ignored.
It works when I write `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"`.

I am not completely sure this issue is really directed to traefik, helm, kubernetes or me.
It is not a major issue since it only requires the user to use quotes.

**Comment by briandenicola** [comment]
Unless I am doing something competely off on the command line, I think there is an issue here.

If I add ```service\\.beta\\.kubernetes\\io/azure-load-balancer-internal"="true"``` to the values.yaml then I get the proper annotations and Azure will create an internal load balancer

``` 
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefiklocal
    meta.helm.sh/release-namespace: default
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  creationTimestamp: "2020-11-19T19:44:09Z"
```

But when I try to set the the annotation via a --set on the command, the quotes always gets striped and so the annotation is ignored.
```
helm install traefik7 traefik/traefik --set service.annotations."service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"="true"
```
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik7
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-11-19T19:53:18Z"
```
```
brian@pc:~/working/traefik/traefik$ k get service
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
kubernetes     ClusterIP      10.0.0.1       <none>          443/TCP                      82m
traefik7       LoadBalancer   10.0.184.140   52.182.228.xyz   80:31366/TCP,443:32070/TCP   21m
traefiklocal   LoadBalancer   10.0.246.30    10.240.0.5      80:31080/TCP,443:30344/TCP   31m
```

The helm template command shows the annotations but the quotes are stripped.
```
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: traefik7
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-9.10.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: traefik7
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: true
```

I've tried pass a quoted "true" via the bash command line with variations like:
--set service.annotations."service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"='"true"'
--set service.annotations."service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"=\"true\"
--set service.annotations."service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"='true'
--set service.annotations."service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"=""true""
but nothing works.
