### ISSUE TITLE
Unable to access application on ports 80 or 443

### ISSUE THREAD

**Issue by worldofgeese** [traefik/traefik-helm-chart#302]
The chart sets the following values for web and websecure:
![image](https://user-images.githubusercontent.com/59834693/98246663-e560ef00-1f72-11eb-98ce-eab1b19010c3.png)

So naturally when I curl my subdomain I get an error code. Here's what I have for my additional arguments.
```
additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=tworldof@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge=true"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=INFO"
# added based on other issues opened here
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
```

From what I've been able to glean from the issues, it appears that the reasonable defaults were changed somewhere between 2.1 and 2.2 but I haven't been able to find documentation of that switch. 

What should I alter for right behaviour?

**Comment by worldofgeese** [comment]
Reopening issue with edits.

**Comment by Letme** [comment]
Does traefik return 404 or what does it mean unable to access application?

**Comment by worldofgeese** [comment]
> Does traefik return 404 or what does it mean unable to access application?

A `curl $IP` gives a `port 443: Connection refused`. This is to an nginx application. Traefik can see and connect my service:
![image](https://user-images.githubusercontent.com/59834693/98253246-10e7d780-1f7b-11eb-981e-8b1aa06e7adb.png)

**Comment by worldofgeese** [comment]
Here's my service entry:
```
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  type: ClusterIP
  selector:
    app: dashboard
  ports:
  - port: 80
    protocol: TCP
```

Thinking this was a matter of running the container with websecure port 443, I have tried @monotek's solution:
```
    additionalArguments:
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"

    ports:
      websecure:
        port: 443

    securityContext:
      capabilities: 
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
```
to no success.

I have also simply tried https://dashboard.mqs.dk at port 8443 also to no success.

I can confirm the app behind the nginx container app is running because I can change the service to be of NodePort type and access it directly under the NodePort. But any attempt to run it behind Traefik with or without defaults results in failure. I'd love to get some clarity on where I'm going wrong because I run Traefik 2 under a docker-compose scheme at home and it works beautifully.

**Comment by Letme** [comment]
Umn, ok so this app:dashboard service you can check if it works by port forwarding (opening http://127.0.0.1:9000 in your local web browser):

```
kubectl port-forward service/dashboard-service 9000:80
```

Service looks OK, but what do you have as IngressRoute? Also check on your master, if you have ports opened and pointing to your localhost: `ss -tnlp`

**Comment by worldofgeese** [comment]
> Umn, ok so this app:dashboard service you can check if it works by port forwarding (opening http://127.0.0.1:9000 in your local web browser):
> 
> ```
> kubectl port-forward service/dashboard-service 9000:80
> ```
> 
> Service looks OK, but what do you have as IngressRoute? Also check on your master, if you have ports opened and pointing to your localhost: `ss -tnlp`

We're getting close! `kubectl port-forward (kubectl get pods --selector "app=dashboard" --output=name) 9000:80` and opening `localhost:9000` gets me into the app dashboard.

Here's my IngressRoute sandwiched by a CORS header manifest and the dashboard Deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deployment
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
         app: dashboard
    spec:
      containers:
      - name: dashboard
        image: ghcr.io/mqsdk/dashboard:latest
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: github-cr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`dashboard.mqs.dk`)
    kind: Rule
    services:
    - name: dashboard-service
      port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-header
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowOriginList:
      - "https://dashboard.mqs.dk"
    accessControlAllowHeaders:
      - "Authorization" 
    accessControlMaxAge: 100
    addVaryHeader: true
```

`ss -tnlp`:
```
State  Recv-Q Send-Q   Local Address:Port    Peer Address:Port Process 
LISTEN 0      4096         127.0.0.1:10256        0.0.0.0:*            
LISTEN 0      4096     127.0.0.53%lo:53           0.0.0.0:*            
LISTEN 0      128            0.0.0.0:22           0.0.0.0:*            
LISTEN 0      4096           0.0.0.0:30007        0.0.0.0:*            
LISTEN 0      4096     172.31.39.210:19001        0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:1338         0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:33699        0.0.0.0:*            
LISTEN 0      4096           0.0.0.0:30372        0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:10248        0.0.0.0:*            
LISTEN 0      2048           0.0.0.0:25000        0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:10249        0.0.0.0:*            
LISTEN 0      4096           0.0.0.0:30763        0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:9099         0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:10251        0.0.0.0:*            
LISTEN 0      4096         127.0.0.1:10252        0.0.0.0:*            
LISTEN 0      4096                 *:10255              *:*            
LISTEN 0      4096                 *:10257              *:*            
LISTEN 0      4096                 *:10259              *:*            
LISTEN 0      128               [::]:22              [::]:*            
LISTEN 0      4096                 *:16443              *:*            
LISTEN 0      4096                 *:10250              *:*         
```

I see my API NodePort on there (different deployment, not proxied) as 30007 but not 443, 80, 8000, or 8443. But I know I have them open in my Security Group on AWS:
![image](https://user-images.githubusercontent.com/59834693/98290791-72736a80-1faa-11eb-88ee-930c513d72d9.png)
