### ISSUE TITLE
AWS EKS - 400 Bad Request

### ISSUE THREAD

**Issue by serban-nicusor-toptal** [traefik/traefik-helm-chart#307]
Hello,

I'm deploying an EKS cluster and a NLB for it to map 80->32080 and 443 ->32443.
I've tried to deploy this helm chart `helm upgrade --install traefik traefik/traefik --namespace kube-system --values traefik/values.yaml`
My `values.yaml` only changed service type to `NodePort` for the NLB, everything else is default.
I'm getting a `400 Bad Request`.

I have a basic deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: tutum/hello-world
          imagePullPolicy: IfNotPresent
          name: hello-world
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      restartPolicy: Always

```

Basic service:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  annotations:
    update: v1
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: hello-world
  sessionAffinity: None
  type: ClusterIP
```

Basic IngressRoute:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: hello-world-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`hello-world-development.XXX.XXX`) && PathPrefix(`/`)
      services:
        - name: hello-world
          priority: 20
          port: 80
```

Note: The exact above is working if I deploy Traefik by myself without the helm chart, same configuration. That's why I've decided to post here, maybe there's something wrong helm-chart side.

Thanks!
