### ISSUE TITLE
Why the / at the end ?

### ISSUE THREAD

**Issue by VladoPortos** [traefik/traefik-helm-chart#312]
Hi all,
I'm not sure if this is the right place to ask, but I finally managed to get my Kubernetes cluster up, using MetalLB for Ingress IP assignment ( everything contained to the cluster ). And I deployed Traefik via Helm 3... 

I can get dashboard using this IngressRoute definition
```
# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```

But I can accessing it I need to add / to the end of the url like kubernetes.local/dashboard/ how to set it without the / at the end ? Sorry if the question seems primitive, but I'm at loss a little.
