### ISSUE TITLE
404 when trying to test whoami service

### ISSUE THREAD

**Issue by kevinjcoleman** [traefik/traefik-helm-chart#326]
I've installed the helm release with the values below.
```
logs:
  general:
    level: INFO
  access:
    enabled: true
ports:
  websecure:
    tls:
      enabled: true

additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=EMAIL"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directorys"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge=true"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
  - "--api.insecure=true"

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: dns-token
```
ingress route
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`whoami.custom.domain`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: letsencrypt
```

I am able to curl `whoami` from a container running on my cluster and it works fine, however attempting to hit `whoami.custom.domain` from outside of the cluster returns a `404 page not found error`. I can even see the requests in the traefik logs, it just never hits the whoami service. What am I doing wrong here?
