### ISSUE TITLE
crd serverstransports missing

### ISSUE THREAD

**Issue by khassel** [traefik/traefik-helm-chart#340]
After update to traefik v2.4.0 traefik fails starting because the crd of serverstransports is missing:

```yaml
kind: CustomResourceDefinition
metadata:
  name: serverstransports.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: ServersTransport
    plural: serverstransports
    singular: serverstransport
  scope: Namespaced
```

The serverstransports is also missing in the `clusterrole.yaml`.
