### ISSUE TITLE
loadBalancerIP - Doesn't work.

### ISSUE THREAD

**Issue by doug62** [traefik/traefik-helm-chart#342]
Greetings - When I set a loadBalancerIP in the values file the corresponding property is not set in traefik svc spec.loadBalancerIp property, and the service does not listen on the desired exposed port - this is critical as MetalLB needs a static IP....

(thanks)

**Comment by mnorrsken** [comment]
Where do you set it? It works fine for me, this is how i set it in values file:
```
service:
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.125
```
