### ISSUE TITLE
Traefik not noticing new services

### ISSUE THREAD

**Issue by maxisme** [traefik/traefik-helm-chart#363]
Every 24 hours or so traefik seems to become completely unresponsive to new changes (adding/deleting services)

# helm setup

```
helm repo add traefik https://helm.traefik.io/traefik
helm upgrade traefik traefik/traefik -f values.yaml --install --wait
```

## values.yml
```
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      certResolver: "le"
nodeSelector:
  kubernetes.io/hostname: ovh-node
additionalArguments: [
    '--certificatesresolvers.le.acme.storage=/data/acme.json',
    '--certificatesresolvers.le.acme.tlschallenge',
    '--certificatesresolvers.le.acme.email=max@max.me.uk',
    '--tracing.jaeger.propagation=b3',
    '--tracing.jaeger.gen128Bit',
    '--tracing.jaeger.collector.endpoint=http://jaeger-collector:14268/api/traces?format=jaeger.thrift',
    '--ping',
    '--ping.entrypoint=web',
]

image:
  tag: "v2.4.2"

rollingUpdate:
  maxUnavailable: 0

logs:
  general:
    level: WARN
```

# Example Ingress (`ingress.yaml`)
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kibana-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kibana.example.com`)
      kind: Rule
      services:
        - name: kibana
          port: 5601
```

So for example after ~24 hours of a traefik upgrade/deployment if I ran:
```
kubectl apply -f ingress.yaml
```
I would see no change in the dashboard and it is not accessable at `kibana.example.com`. And also same in the other direction if I were to delete it, it would stay in the traefik dashboard and I would still be able to access. 

I have tried looking at the logs but everything seems normal? Please would you be able to help me debug.

Thank you
