### ISSUE TITLE
Traefik Dashboard via `kubectl port-forward`: Error occurred forwarding 9000 -> 9000

### ISSUE THREAD

**Issue by jaydrogers** [traefik/traefik-helm-chart#379]
# :thinking: Issue description
* I am attempting to use `kubectl port-forward` to access the Traefik dashboard
* I get a connection, but it says "error forwarding port 9000 to pod"

#### Command I am using
```sh
kubectl port-forward -n traefik $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name -n traefik) 9000:9000
```

#### Error I am getting
```txt
E0302 15:53:03.890635   24003 portforward.go:400] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod c9aee8a53793f63b87ae1cea843c252a235b483bc7ce51252a7c4703f518ada8, uid : exit status 1: 2021/03/02 21:53:03 socat[15622] E getaddrinfo("localhost", "NULL", {1,2,1,6}, {}): Try again
Handling connection for 9000
```
#### Screenshot of the error
This is what I see when I visit http://traefik.localhost/dashboard/
<img width="1802" alt="Screen Shot 2021-03-02 at 4 01 09 PM" src="https://user-images.githubusercontent.com/3174134/109721115-8dc53f80-7b70-11eb-9146-14b46eaf62ee.png">

# :earth_americas: Environment
### Software versions
* K3s Version: [v1.20.4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.20.4%2Bk3s1)
* Traefik: v2 (installed via Helm)

### Configurations

 **🚨👉 IMPORTANT NOTE:**
* I am running Traefik in the `traefik` namespace (I figured it is best practice to not run Traefik in the default namespace?)
* I added `namespace: traefik` to the "dashboard.yml" configuration below (with or without this I am getting the same error)

<details>
  <summary>dashboard.yml (taken from Github)</summary>

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```

</details>
<details>
  <summary>helm-values.yml</summary>

```yaml
#
# Advanced K8s settings
#
rbac:
  enabled: true
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

#
# Configure providers
#
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
#
# Create an IngressRoute for the dashboard
#
ingressRoute:
  dashboard:
    enabled: true
# #
# # Redirect to HTTPs
# #
# ports:
#   web:
#     redirectTo: websecure

# #
# # Options for the main traefik service, where the entrypoints traffic comes
# # from.
# service:
#   type: NodePort

# Configure ports
ports:
  # The name of this one can't be changed as it is used for the readiness and
  # liveness probes, but you can adjust its config to your liking
  traefik:
    port: 9000
    # Use hostPort if set.
    # hostPort: 9000
    #
    # Use hostIP if set. If not set, Kubernetes will default to 0.0.0.0, which
    # means it's listening on all your interfaces and all your IPs. You may want
    # to set this value if you need traefik to listen on specific interface
    # only.
    # hostIP: 192.168.100.10

    # Defines whether the port is exposed if service.type is LoadBalancer or
    # NodePort.
    #
    # You SHOULD NOT expose the traefik port on production deployments.
    # If you want to access it from outside of your cluster,
    # use `kubectl port-forward` or create a secure ingress
    expose: false
    # The exposed port for this service
    exposedPort: 9000
    # The port protocol (TCP/UDP)
    protocol: TCP
  web:
    port: 8000
    # hostPort: 8000
    expose: true
    exposedPort: 80
    # The port protocol (TCP/UDP)
    protocol: TCP
    # Use nodeport if set. This is useful if you have configured Traefik in a
    # LoadBalancer
    # nodePort: 32080
    # Port Redirections
    # Added in 2.2, you can make permanent redirects via entrypoints.
    # https://docs.traefik.io/routing/entrypoints/#redirection
    # redirectTo: websecure
  websecure:
    port: 8443
    # hostPort: 8443
    expose: true
    exposedPort: 443
    # The port protocol (TCP/UDP)
    protocol: TCP
    # nodePort: 32443
    # Set TLS at the entrypoint
    # https://doc.traefik.io/traefik/routing/entrypoints/#tls
    tls:
      enabled: true
      # this is the name of a TLSOption definition
      options: ""
      certResolver: ""
      domains: []
      # - main: example.com
      #   sans:
      #     - foo.example.com
      #     - bar.example.com

# Options for the main traefik service, where the entrypoints traffic comes
# from.
service:
  enabled: true
  type: LoadBalancer
  # Additional annotations (e.g. for cloud provider specific config)
  annotations: {}
  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}
  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  spec:
    externalTrafficPolicy: Local
    # loadBalancerIP: "1.2.3.4"
    # clusterIP: "2.3.4.5"
  loadBalancerSourceRanges: []
    # - 192.168.0.1/32
    # - 172.16.0.0/16
  externalIPs: []
    # - 1.2.3.4


#
# Things that I felt more comfortable setting via the CLI
#
additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=me@email.test"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=ERROR"
```

</details>

# 🙌 Thank you for your help!

If there is anything else that you would like to see, just let me know! Thanks!!!

**Comment by jakubhajek** [comment]
Hello @jaydrogers 
Seems that the root cause of the issue is resolving the DNS name `traefik.localhost`. Please make sure that the name resolution is working correctly.

1. Can you please try to use the configuration that is automatically created once you deploy Traefik using Helm? 
The object `ingressroutes.traefik.containo.us/traefik-dashboard ` uses the following matching rule:

```
PathPrefix(`/dashboard`) || PathPrefix(`/api`)
```

and works correctly with port-forwarding, just use `http://localhost/dashboard/` to access the Traefik dashboard.

2. If you need to use a DNS name I  recommend using a  temporary DNS name e.g. `traefik.127.0.0.1.nip.io` which points to localhost. It is done automatically through `nip.io` DNS servers and should be suitable for testing purposes. You don't have to change anything on your side in order to use that kind of DNS name. 

Hope that helps.

**Comment by jaydrogers** [comment]
Wow, I feel so foolish! 😆 I assumed `traefik.localhost` was resolving -- it wasn't. Thanks for pointing that out @jakubhajek. Even with changing it to `traefik.127.0.0.1.nip.io` it does work for me.

### The problem still persists
Here are my results:

#### Ping test
<img width="1552" alt="Screen Shot 2021-03-04 at 12 43 18 PM" src="https://user-images.githubusercontent.com/3174134/110013794-af950280-7ce7-11eb-9b89-33e48c91464e.png">

#### Web browser
<img width="1392" alt="Screen Shot 2021-03-04 at 12 42 24 PM" src="https://user-images.githubusercontent.com/3174134/110013885-c50a2c80-7ce7-11eb-9b01-d717b228d0e6.png">


#### Tunnel output
<img width="1392" alt="Screen Shot 2021-03-04 at 12 43 54 PM" src="https://user-images.githubusercontent.com/3174134/110013839-ba4f9780-7ce7-11eb-92f9-fc97a5e00a2b.png">

## Further question:
The terminal still has `getaddrinfo("localhost", "NULL", {1,2,1,6}, {}): Try again` in it. Not sure why it says "localhost".

Just to be extra clear on your question:
<img width="932" alt="Screen Shot 2021-03-04 at 12 49 53 PM" src="https://user-images.githubusercontent.com/3174134/110014342-4d88cd00-7ce8-11eb-8dd0-981c912f0548.png">

**You mean:**
* Just install it with helm normally and it is already enabled by default? ([I assume via this value?](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L82))

☝️ If so, I did run a `kubectl delete -f dashboard.yml` before running my tests above.

Thanks for your help!

**Comment by jakubhajek** [comment]
Hey @jaydrogers,
The dashboard is enabled by default when you install Traefik using the official Helm chart. No need to create any other configuration to access it through port-forward feature. 
The Helm chart will create ingressroutes called traefik-dashboard. You can check the details using the command below:

`kubectl describe ingressroutes traefik-dashboard -n <namespace>`

Please note the section: 

```yaml
 Routes:
    Kind:   Rule
    Match:  PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    Services:
      Kind:  TraefikService
      Name:  api@internal
```

Then you have to execute port-forward:
```shell
kubectl port-forward -n <namespace> $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name -n <namespace>) 9000:9000
```

Again, please notice the namespace name in that command; than the following resources `/api` and `/dashboard/` should be accessible via localhost:9000

`curl localhost:9000/dashboard/`
`curl localhost:9000/api/version`

If you need a rule-based on HTTP HOST header it should be adapted accordingly and the given host has to point to your cluster; nip.io is one of the free DNS as an example. 

Seems that it is a configuration issue so I suggest moving the conversation to our community forum.  

Thanks,
