### ISSUE TITLE
How to set X-Real-Ip when using NodePort service?

### ISSUE THREAD

**Issue by jaydrogers** [traefik/traefik-helm-chart#380]
# :thinking: Issue description
* I have the `containous/whoami` image deployed
* When I visit the page, the `X-Real-Ip` header is wrong
#### Screenshot for more detail
<img width="833" alt="Screen Shot 2021-03-02 at 4 24 36 PM" src="https://user-images.githubusercontent.com/3174134/109723814-3c1eb400-7b74-11eb-9ee0-1e027249f781.png">

# 🤞 What I attempted
In my `values.yml`, I added `externalTrafficPolicy: Local` (see my full **helm-values.yml** file below)

```yaml
# Options for the main traefik service, where the entrypoints traffic comes
# from.
service:
  enabled: true
  type: LoadBalancer
  # Additional annotations (e.g. for cloud provider specific config)
  annotations: {}
  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}
  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  spec:
    externalTrafficPolicy: Local
    # loadBalancerIP: "1.2.3.4"
    # clusterIP: "2.3.4.5"
  loadBalancerSourceRanges: []
    # - 192.168.0.1/32
    # - 172.16.0.0/16
  externalIPs: []
    # - 1.2.3.4
```

# :earth_americas: Environment
### Software versions
* K3s Version: [v1.20.4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.20.4%2Bk3s1)
* Traefik: v2 (installed via Helm)

### Service Port Type
Please excuse me being a Kubernetes n00b (just getting started). I believe I have everything configured as `NodePort`. I followed the logic of Nginx Ingress (lol, sorry 😆) but the logic seemed like it applied to Traefik as well: https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#over-a-nodeport-service

### Configurations
<details>
  <summary>Output of "kubectl edit svc traefik -n traefik"</summary>

🚨👉 **IMPORTANT NOTE:** The IPs of `1.2.3.4` and `2.3.4.5` are the WAN IPs of my Digital Ocean nodes (two nodes total...one master and one node)

```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
  creationTimestamp: "2021-03-02T16:41:20Z"
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.15.2
  name: traefik
  namespace: traefik
  resourceVersion: "12108"
  uid: a5357eba-0791-4067-864d-29c245ded920
spec:
  clusterIP: 10.43.189.198
  clusterIPs:
  - 10.43.189.198
  externalTrafficPolicy: Local
  healthCheckNodePort: 30895
  ports:
  - name: web
    nodePort: 31940
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31775
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 1.2.3.4
    - ip: 2.3.4.5
```

</details>

<details>
  <summary>helm-values.yml</summary>

```yaml
#
# Advanced K8s settings
#
rbac:
  enabled: true
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

#
# Configure providers
#
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
#
# Create an IngressRoute for the dashboard
#
ingressRoute:
  dashboard:
    enabled: true
# #
# # Redirect to HTTPs
# #
# ports:
#   web:
#     redirectTo: websecure

# #
# # Options for the main traefik service, where the entrypoints traffic comes
# # from.
# service:
#   type: NodePort

# Configure ports
ports:
  # The name of this one can't be changed as it is used for the readiness and
  # liveness probes, but you can adjust its config to your liking
  traefik:
    port: 9000
    # Use hostPort if set.
    # hostPort: 9000
    #
    # Use hostIP if set. If not set, Kubernetes will default to 0.0.0.0, which
    # means it's listening on all your interfaces and all your IPs. You may want
    # to set this value if you need traefik to listen on specific interface
    # only.
    # hostIP: 192.168.100.10

    # Defines whether the port is exposed if service.type is LoadBalancer or
    # NodePort.
    #
    # You SHOULD NOT expose the traefik port on production deployments.
    # If you want to access it from outside of your cluster,
    # use `kubectl port-forward` or create a secure ingress
    expose: false
    # The exposed port for this service
    exposedPort: 9000
    # The port protocol (TCP/UDP)
    protocol: TCP
  web:
    port: 8000
    # hostPort: 8000
    expose: true
    exposedPort: 80
    # The port protocol (TCP/UDP)
    protocol: TCP
    # Use nodeport if set. This is useful if you have configured Traefik in a
    # LoadBalancer
    # nodePort: 32080
    # Port Redirections
    # Added in 2.2, you can make permanent redirects via entrypoints.
    # https://docs.traefik.io/routing/entrypoints/#redirection
    # redirectTo: websecure
  websecure:
    port: 8443
    # hostPort: 8443
    expose: true
    exposedPort: 443
    # The port protocol (TCP/UDP)
    protocol: TCP
    # nodePort: 32443
    # Set TLS at the entrypoint
    # https://doc.traefik.io/traefik/routing/entrypoints/#tls
    tls:
      enabled: true
      # this is the name of a TLSOption definition
      options: ""
      certResolver: ""
      domains: []
      # - main: example.com
      #   sans:
      #     - foo.example.com
      #     - bar.example.com

# Options for the main traefik service, where the entrypoints traffic comes
# from.
service:
  enabled: true
  type: LoadBalancer
  # Additional annotations (e.g. for cloud provider specific config)
  annotations: {}
  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}
  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  spec:
    externalTrafficPolicy: Local
    # loadBalancerIP: "1.2.3.4"
    # clusterIP: "2.3.4.5"
  loadBalancerSourceRanges: []
    # - 192.168.0.1/32
    # - 172.16.0.0/16
  externalIPs: []
    # - 1.2.3.4


#
# Things that I felt more comfortable setting via the CLI
#
additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=me@email.test"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=ERROR"
```

</details>

# 🙌 Thank you for your help!
The Traefik Community is amazing and I am very grateful for everyone's help!
