### ISSUE TITLE
Communicating via NodePort in kind

### ISSUE THREAD

**Issue by jasonatball** [traefik/traefik-helm-chart#388]
I didn't see Traefik as one of the known to work in the [Kind Ingress](https://kind.sigs.k8s.io/docs/user/ingress/) page but I've been trying to get it to work and feel like I'm close. My kind-config.yaml is:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://registry:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30001
        hostPort: 9000 # minio
      - containerPort: 30003
        hostPort: 2901 # cmd-tlm-api
      - containerPort: 30004
        hostPort: 2902 # script-runner-api
      - containerPort: 30005
        hostPort: 2900 # traefik
    extraMounts:
      - hostPath: C:\ProgramData\linuxcerts
        containerPath: /etc/ssl/certs
  - role: worker
    extraMounts:
      - hostPath: C:\ProgramData\linuxcerts
        containerPath: /etc/ssl/certs
  - role: worker
    extraMounts:
      - hostPath: C:\ProgramData\linuxcerts
        containerPath: /etc/ssl/certs
  - role: worker
    extraMounts:
      - hostPath: C:\ProgramData\linuxcerts
        containerPath: /etc/ssl/certs
```
So I'm trying to map 2900 through the container port 30005. I'm using the traefik chart with the following values.yaml:
```
traefik:
  # hostNetwork: true # Should this be true???
  service:
    type: NodePort
  ports:
    web:
      port: 8000
      expose: true
      exposedPort: 2900
      # The port protocol (TCP/UDP)
      protocol: TCP
      nodePort: 30005
  volumes:
    - name: traefik
      mountPath: "/etc/traefik/"
      type: configMap
  additionalArguments:
    - --providers.file.filename=/etc/traefik/traefik.yaml
  nodeSelector:
    ingress-ready: 'true' # assign to the kind-control-plane
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Equal
      effect: NoSchedule
```
Then I create a ConfigMap which where traefik loads the traefik.yaml:
```
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  traefik.yaml: |
    # Listen for everything coming in on our port
    entrypoints:
      web:
        address: ":8000"
    http:
      middlewares:
        # Removes the first part of the url before passing onto the service
        # ie. /cosmos-api/api becomes /api
        removeFirst:
          replacePathRegex:
            regex: "^/([^/]*)/(.*)"
            replacement: "/$2"
        # Adds /tools/base to the beginning of the given url
        # ie. /index.html becomes /tools/base/index.html
        addToolsBase:
          replacePathRegex:
            regex: "^/(.*)"
            replacement: "/tools/base/$1"
        # Adds index.html to the end of urls that end in /
        # ie. /something/ becomes /something/index.html
        addIndex:
          replacePathRegex:
            regex: "(.*)/$"
            replacement: "$1/index.html"
        # Handle any not found errors from the regular default route
        # to pull from index.html to allow the SPA to work with the
        # URL
        indexOnNotFound:
          errors:
            status:
              - "400-499"
            service: service-minio
            query: "/tools/base/index.html"
      routers:
        # This is the default route for everything that doesn't match a more specific route
        # It gets us to the base cosmos application
        web-router:
          rule: Host(`localhost`)
          middlewares:
            # Add /tools/base/ and optionally index.html for ending in /
            # ie. / becomes /tools/base/index.html before being passed to Minio
            # This gets us to the right url for Minio to serve the static webpage
            # 404 errors will serve /tools/base/index.html to make the single page app
            # wor as expected
            - "addToolsBase"
            - "addIndex"
            - "indexOnNotFound"
          service: service-minio
        # Route to the cosmos cmd/tlm api
        api-router:
          rule: PathPrefix(`/cosmos-api`)
          middlewares:
            # Remove /cosmos-api from urls
            - "removeFirst"
          service: service-api
        # Route to the script api
        script-router:
          rule: PathPrefix(`/script-api`)
          middlewares:
            # Remove /script-api from urls
            - "removeFirst"
          service: service-script
        # Route to other tool plugins hosted statically in Minio
        tools-router:
          rule: PathPrefix(`/tools`)
          service: service-minio
      services:
        # The COSMOS cmd/tlm api service
        service-api:
          loadBalancer:
            servers:
              - url: "http://cosmos-cmd-tlm-api:2901"
        # The COSMOS script api service
        service-script:
          loadBalancer:
            servers:
              - url: "http://cosmos-script-runner-api:2902"
        # The Minio S3 file server
        service-minio:
          loadBalancer:
            servers:
              - url: "http://cosmos-minio:9000"
    # Declare the routes are currently coming from this file, not dynamically
    providers:
      file:
        filename: /etc/traefik/traefik.yaml
```
When everything starts up I can see the service:
```
>kubectl describe svc cosmos-traefik
Name:                     cosmos-traefik
Namespace:                default
Labels:                   app.kubernetes.io/instance=cosmos
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=traefik
                          helm.sh/chart=traefik-9.15.2
Annotations:              meta.helm.sh/release-name: cosmos
                          meta.helm.sh/release-namespace: default
Selector:                 app.kubernetes.io/instance=cosmos,app.kubernetes.io/name=traefik
Type:                     NodePort
IP:                       10.96.28.99
Port:                     web  2900/TCP
TargetPort:               web/TCP
NodePort:                 web  30005/TCP
Endpoints:
Port:                     websecure  443/TCP
TargetPort:               websecure/TCP
NodePort:                 websecure  32319/TCP
Endpoints:
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
However, the traefik pod constantly dies with the following:
```
>kubectl logs cosmos-traefik-58fb646b4f-jfpn9
time="2021-03-09T19:59:57Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yaml"
time="2021-03-09T20:00:26Z" level=error msg="accept tcp [::]:8000: use of closed network connection" entryPointName=web
time="2021-03-09T20:00:26Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-03-09T20:00:26Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-03-09T20:00:26Z" level=error msg="close tcp [::]:8000: use of closed network connection" entryPointName=web
```
It's as if traefik is trying to connect to port 8000 but that's where I said to listen so shouldn't it be opening that port? Eventually I'm trying to route requests over to my minio microservice which is listenting on port 9000.

I appreciate any help as I've tried many other combinations of ports and kind configurations and nothing seems to work.

**Comment by jasonatball** [comment]
I think the issue was the traefik entrypoint and extra configuration in values.yaml. The relevant snippets from each of the yaml files which worked:

kind-config.yaml:
```
    extraPortMappings: # See values.yaml and other templates for matching NodePorts
      - containerPort: 30010
        hostPort: 2900 # Traefik frontend
```
Chart.yaml:
```
dependencies:
  - name: traefik
    version: 9.15.2
    repository: "@traefik"
```
values.yaml:
```
traefik:
  service:
    type: NodePort
  ports:
    web:
      nodePort: 30010
    websecure:
      nodePort: 30011
  volumes:
    - name: traefik
      mountPath: "/etc/traefik/"
      type: configMap
  additionalArguments:
    - --providers.file.filename=/etc/traefik/cosmos.yaml
```
templates\traefik.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  cosmos.yaml: |
    # Listen for everything coming in on our port
    http:
      middlewares:
        # Various stuff we're doing
      routers:
        # This is the default route for everything that doesn't match a more specific route
        # It gets us to the base cosmos application
        web-router:
          rule: Host(`localhost`)
        # Various other routes specific to our application
      services:
        # The COSMOS cmd/tlm api service
        service-api:
          loadBalancer:
            servers:
              - url: "http://cosmos-cmd-tlm-api:2901"
        # The COSMOS script api service
        service-script:
          loadBalancer:
            servers:
              - url: "http://cosmos-script-runner-api:2902"
        # The Minio S3 file server
        service-minio:
          loadBalancer:
            servers:
              - url: "http://cosmos-minio:9000"
    # Declare the routes are currently coming from this file, not dynamically
    providers:
      file:
        filename: /etc/traefik/cosmos.yaml
```
