### ISSUE TITLE
how to enable https on traefik dashboard

### ISSUE THREAD

**Issue by kconde2** [traefik/traefik-helm-chart#412]
this is configuration I use 
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  routes:
  - match: Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
```

Thanks in advance

**Comment by SantoDE** [comment]
Your `IngressRoute` needs to be attached to the websecure entrypoint.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
```
