### ISSUE TITLE
Included ingressroute traefik-dashboard not working

### ISSUE THREAD

**Issue by trallnag** [traefik/traefik-helm-chart#432]
Hello,

while the default traefik-dashboard is deployed, I cannot access the dashboard through Traefik ingress. When I port-forward the traefik pod it works. So it is an issue with the ingressroute.

I am using:

* K3s single node cluster
* Installed traefik via this helm chart

```
- name: Install Helm chart traefik
  kubernetes.core.helm:
    name: traefik
    namespace: kube-system
    chart_ref: traefik/traefik
    chart_version: 9.19.1
    values:
      logs:
        access:
          enabled: true
      additionalArguments:
        - "--metrics.prometheus=true"
```

## It works with port-forward

```
> kubectl port-forward traefik-5dc8dfdd7-vg6g8  12345:9000
> curl localhost:12345/dashboard/
<!DOCTYPE html>[...]
```

In the logs:

```
127.0.0.1 - - [12/Jun/2021:17:33:37 +0000] "GET /dashboard/ HTTP/1.1" 200 3026 "-" "-" 208 "kube-system-traefik-dashboard-d012b7f875133eeab4e5@kubernetescrd" "-" 0ms
```

## It does not work with ingressroute

```
> curl localhost:80/dashboard/
404 page not found
> curl 192.168.178.48:80/dashboard/
404 page not found
```

In the logs:

```
10.42.0.1 - - [12/Jun/2021:17:35:57 +0000] "GET /dashboard/ HTTP/1.1" - - "-" "-" 239 "-" "-" 0ms
10.42.0.1 - - [12/Jun/2021:17:35:57 +0000] "GET /dashboard/ HTTP/1.1" - - "-" "-" 240 "-" "-" 0ms
10.42.0.1 - - [12/Jun/2021:17:35:58 +0000] "GET /dashboard/ HTTP/1.1" - - "-" "-" 241 "-" "-" 0ms
```

Here is the full description of the ingressroute that is automatically created:

```yaml
Name:         traefik-dashboard
Namespace:    kube-system
Labels:       app.kubernetes.io/instance=traefik
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=traefik
              helm.sh/chart=traefik-9.19.1
Annotations:  helm.sh/hook: post-install,post-upgrade
API Version:  traefik.containo.us/v1alpha1
Kind:         IngressRoute
Metadata:
  Creation Timestamp:  2021-06-12T17:17:42Z
  Generation:          1
  Managed Fields:
    API Version:  traefik.containo.us/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:helm.sh/hook:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:helm.sh/chart:
      f:spec:
        .:
        f:entryPoints:
        f:routes:
    Manager:         Go-http-client
    Operation:       Update
    Time:            2021-06-12T17:17:42Z
  Resource Version:  493343
  UID:               4077acd5-4210-4368-867a-b381ff02d45f
Spec:
  Entry Points:
    traefik
  Routes:
    Kind:   Rule
    Match:  PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    Services:
      Kind:  TraefikService
      Name:  api@internal
Events:      <none>
```

**Comment by trallnag** [comment]
Okay, so the ingress route created by default has a different entrypoint and is not made to enable access from outside the cluster

**Comment by trallnag** [comment]
I disabled the default ingressroute and instead I use a custom one

**Comment by challapradyumna** [comment]
@trallnag Can you paste the custom one here ...

**Comment by trallnag** [comment]
@challapradyumna 

```yaml
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: traefik-dashboard
  namespace: ingress
  labels:
    {{ common_labels | indent(4) }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.example.org`)
      middlewares:
        - name: forwardauth-authelia # I use Authelia for auth.
          namespace: ingress
      services:
        - name: api@internal
          kind: TraefikService
```

**Comment by ccll** [comment]
@trallnag Thank you for the solution, solved my problem perfectly.

Just a hint, another simpler way is to override Helm values to patch the created IngressRoute with `helm ... --values values.yaml`.

```yaml
# values.yaml
...
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.example.com`) && PathPrefix(`/dashboard`, `/api`)
    entryPoints: ["websecure"]
    tls:
      secretName: your-tls-cert
...
```

A full version of available values could be shown with `helm inspect values traefik/traefik` for anyone didn't know.
