### ISSUE TITLE
Add additional service for internal IP

### ISSUE THREAD

**Issue by muffl0n** [traefik/traefik-helm-chart#436]
We're running a private GKE cluster that is reachable via internal IPs (via VPN) as well as via external IPs (via external Loadbalancer). We currently use ingress-nginx where you can configure an additional internal service. See:
* https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-service.yaml
* https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-service-internal.yaml

```
controller:
  service:
    internal:
      enabled: true
      annotations:
        networking.gke.io/internal-load-balancer-subnet: gke-services
        networking.gke.io/load-balancer-type: Internal
      loadBalancerIP: 10.10.10.10
```

The benefit is, that we can allow some Ingresses to only be accessible via private IPs.

I could not find a smiliar possibility to do this in Traefik. Am I missing something?
