### ISSUE TITLE
persistent volume annotations bug

### ISSUE THREAD

**Issue by corbosman** [traefik/traefik-helm-chart#471]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.1.1

### What version of Traefik are you using?

2.4.9

### What did you do?

I tried passing annotations to the persistent volume for acme certs.

```yaml
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteMany
  size: 128Mi
  storageClass: "nfs-client"
  path: /data
  annotations:
    nfs.io/storage-path: "acme"
```

I expected a PVC containing those annotations. Instead I got a yaml parsing error.

### What did you see instead?

The helm chart creates this yaml which seems to be indented wrong.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  annotations:
      nfs.io/storage-path: acme
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.1.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
```

### What is your environment & configuration?

k8s 1.21.4, helm 3.6.3, homelab system

**Comment by faust64** [comment]
Indeed, template uses some `indent`, while it should be `nindent`.

I did submit a PR, that would generate something like:

```
...
# Source: traefik/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  annotations:

    foo: bar
    helm.sh/resource-policy: keep
...
```

**Comment by faust64** [comment]
FYI, PR was merged yesterday.
Can you confirm it solved your issue, @corbosman ?

**Comment by corbosman** [comment]
I actually now see a new problem, there is now an empty line after the annotations.

This is what my values.yaml holds:

```
persistence:
  enabled: true
  name: data
  # existingClaim: "traefik"
  accessMode: ReadWriteMany
  size: 128Mi
  storageClass: "nfs"
  path: /data
  annotations:
    foo: bar
  # subPath: "acme" # only mount a subpath of the Volume into the pod
```
  
And resulting manifest:

```
 Source: traefik/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  annotations:

    foo: bar
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.2.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "128Mi"
  storageClassName: "nfs"
  ```
