### ISSUE TITLE
Cannot use IngressClass stanza - set to `nil` causing comparison error

### ISSUE THREAD

**Issue by mylesagray** [traefik/traefik-helm-chart#473]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.1.2

### What version of Traefik are you using?

2.4.13

### What did you do?

When attempting to use the chart with `ingressClass.enabled=true` templating will fail as `fallbackApiVersion` is a key with no value, making it `nil` - when helm tries to compare the `nil` to the string values here it fails:

https://github.com/traefik/traefik-helm-chart/blob/f1696abb2ab346d6cf40154b89297211c96ca3cb/traefik/templates/ingressclass.yaml#L6-L7

Definition of `fallbackApiVersion`:

 https://github.com/traefik/traefik-helm-chart/blob/f1696abb2ab346d6cf40154b89297211c96ca3cb/traefik/values.yaml#L67

Error seen:

```Error: template: traefik-v2/charts/traefik/templates/ingressclass.yaml:6:18: executing "traefik-v2/charts/traefik/templates/ingressclass.yaml" at <eq .Values.ingressClass.fallbackApiVersion "v1beta1">: error calling eq: incompatible types for comparison
helm.go:88: [debug] template: traefik-v2/charts/traefik/templates/ingressclass.yaml:6:18: executing "traefik-v2/charts/traefik/templates/ingressclass.yaml" at <eq .Values.ingressClass.fallbackApiVersion "v1beta1">: error calling eq: incompatible types for comparison
```

### What did you see instead?

Definition of `fallbackApiVersion` should be:

```yaml
fallbackApiVersion: ""
```

### What is your environment & configuration?

K8s 1.21.3

values.yaml:

```yaml
traefik:
  deployment:
    replicas: 4
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  ingressClass:
    enabled: true
    isDefaultClass: true
  pilot:
    enabled: true
    token: "xxxxxxxxxxxxxxxxx"
    dashboard: true
  ingressRoute:
    dashboard:
      enabled: true
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: traefik
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - traefik
        topologyKey: "kubernetes.io/hostname"
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```
