### ISSUE TITLE
Helm Upgrade - 2.5.0 MiddlewaresTCP Missing

### ISSUE THREAD

**Issue by evanreichard** [traefik/traefik-helm-chart#482]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-10.3.0

### What version of Traefik are you using?

2.5.0

### What did you do?

Automated helm upgrade to Traefik 2.5.0

### What did you see instead?

Logs:

```
Failed to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP: the server could not find the requested resource (get middlewaretcps.traefik.containo.us)
```

All IngressRoutes failing (404)

### What is your environment & configuration?

k8s v1.19.4 (k3os)

### Additional Information

```shell
Added the new CRD and things started working again:

kubectl apply -f https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/middlewarestcp.yaml

Not sure if this because my environment, but for whatever reason it didn't add the new MiddlewaresTCP CRD. Manually adding fixed it.
```

**Comment by jakubhajek** [comment]
hello @evanreichard 

Would you please let me know what tool do you use for automated Helm deployment and how the CRD deployment is managed by that tool?

**Comment by budimanjojo** [comment]
I have the same problem here, After updating the crds to v10.3.0 I can no longer access all my ingressroutes. Here's the log in traefik pod:
```
E0819 12:24:29.250516       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Faile
d to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.containo.us is fo
rbidden: User "system:serviceaccount:ingress-system:traefik" cannot list resource "middlewaretcps" in API group "tra
efik.containo.us" at the cluster scope
```
I'm using flux and renovatebot only to update CRDs from this repository. This is my deployment manifest (updated to traefik 2.5.0): https://github.com/budimanjojo/home-cluster/blob/main/cluster/core/traefik/deployment.yaml
and here is the CRDs deployment: https://github.com/budimanjojo/home-cluster/blob/main/cluster/crds/traefik/gitrepository-fluxCRD.yaml

**Comment by budimanjojo** [comment]
Sorry, seems like I know what's wrong with mine, it's because I haven't update my service account to use the CRDs yet. I have the middlewaresTCP but the service account is forbidden to use it. Please just ignore my post :)

**Comment by jakubhajek** [comment]
Hello!

This is a commonly known [Helm issue](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations) that there is no support for upgrading or deleting CRD. 

The problem you were facing was related to the lack of the new CRD: Middleware TCP that has been introduced together with the new 2.5 release. That CRD has to be available on a cluster once you deploy Traefik

For FluxCD I use the following code to manage CRDs for Traefik. I hope that helps: 

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/traefik/traefik-helm-chart.git
  ref:
    tag: v10.3.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/traefik/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-api-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: traefik-crds
    namespace: flux-system
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ingressroutes.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ingressroutetcps.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ingressrouteudps.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: middlewares.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: middlewaretcps.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: serverstransports.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: tlsoptions.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: tlsstores.traefik.containo.us
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: traefikservices.traefik.containo.us
```
