### ISSUE TITLE
Configuration changes not implemented on K3s. 

### ISSUE THREAD

**Issue by fabltd** [traefik/traefik-helm-chart#486]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Followed instructions to implment Metrics and Access Logs but will not work.

traefik is deployed by k3s. Changes should be added to a yaml file and are applied by helm.

These changes are present in the configuration map chart-values-traefik.

The changes are never implemented.

### What did you see instead?

Configuration is not updated.

### What version of Traefik are you using?

 rancher/library-traefik:2.4.8

### What is your environment & configuration?

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-9.18.2.tgz
  valuesContent: |-k
    dashboard:
       enabled: true
       domain: "fab.local"      
    metrics:
      prometheus: 
        enabled: true 
    accessLog:
        enabled: true
```

Add more configuration information here.
