### ISSUE TITLE
Kubernetes Middleware Resource 'namespace' key does not have effect in IngressRoute Resource

### ISSUE THREAD

**Issue by garygan89** [traefik/traefik-helm-chart#487]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.1.3

### What version of Traefik are you using?

2.4.13

### What did you do?

Namespace key specified in IngressRoute `middlewares.namespace` resource has no effect. For some reason Traefik cannot locate the Middleware defined in the IngressRoute `middlewares.namespace` key.

However this has no problem with `TLSOption` namespace. Where my TLSOption resource is defined in `proxy` namespace, and all IngressRoute in different namespace with `tlsoption.namespace=proxy` works fine.

My scenario:
Middleware namespace: proxy
Traefik deploy namespace: proxy
IngressRoute namespace: monitoring

Example of IngressRoute (partial)
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: $INGRESS_ROUTE_NAME
  annotations:
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host("$DNS_NAME")
    kind: Rule
    middlewares:
    - name: redirect-http-to-https   
      namespace: $NAMESPACE_MIDDLEWARE
...
```

### What did you see instead?

Traefik log output that the middleware key is not found:
```
...
{"ingress":"prometheus-ui","level":"error","msg":"Failed to create middleware keys: middleware proxy/redirect-http-to-https is not in the IngressRoute namespace monitoring","namespace":"monitoring","providerName":"kubernetescrd","time":"2021-08-21T01:24:19Z"}
...
```

Confirmed that the IngressRoute resource is using the Middleware namespace key.
kubectl describe ingressroute/...
```
...
Spec:
  Entry Points:
    websecure
  Routes:
    Kind:   Rule
    Match:  Host("...")
    Middlewares:
      Name:       redirect-http-to-https
      Namespace:  proxy
...
```

Solution:
It is most likely that Traefik operator forgot to monitor the Middlware `namespace` key.

### What is your environment & configuration?

- Bare metal kubernetes
- Docker runtime
- Host OS: Ubuntu Linux 18.04 LTS x64

### Additional Information

```shell
-
```
