### ISSUE TITLE
new crossnamespace behavior lead to downtime

### ISSUE THREAD

**Issue by HaveFun83** [traefik/traefik-helm-chart#489]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.3.1

### What version of Traefik are you using?

traefik:2.5.0

### What did you do?

Upgrade traefik-helm-chart from 10.1.1 to 10.3.1 break crossnamespaced service in ingressroute crd as the default `providers.kubernetescrd.allowcrossnamespace` changed from true to false.

https://github.com/traefik/traefik/releases/tag/v2.4.11
https://github.com/traefik/traefik/pull/8260

### What did you see instead?

```
ingress/traefik-64d6f66b4b-gmr2m[traefik]: time="2021-08-22T22:09:00Z" level=error msg="service monitoring/infra-grafana not in the parent resource namespace ingress" namespace=ingress providerName=kubernetescrd ingress=grafana-ingress
```
**And all ingressroutes with crossnamspaced services went unreachable.**

### What is your environment & configuration?

k3s v1.21.4

### Additional Information

```shell
The following argument fixed this issue

    additionalArguments:
      - "--providers.kubernetescrd.allowcrossnamespace=true"
```
I used the following default provider config
```
    providers:
      kubernetesCRD:
        enabled: true
        namespaces: []

      kubernetesIngress:
        enabled: true
        namespaces: []
```
```

**Comment by faust64** [comment]
Hi,

That doesn't sound like something that would have changed recently. From 10.1.1 to 10.3.1, diff shows changes to annotations, some missing rbac apiGroups, and ingressClasses fallback API version.

Any chance you someone may have added that option to your deployment/daemonset without updating your values file?

**Comment by hannius** [comment]
HI,HaveFun83 ,Did you have faced the problem about crossnamespace of kubernetesGateway
```
# Enable experimental features
experimental:
  plugins:
    #enabled: false
    enabled: true
  kubernetesGateway:
    enabled: true
    #enabled: true
    appLabelSelector: "traefik"
    #certificates: []
    certificates:
     - group: "core"
       kind: "Secret"
       #name: "mysecret"
       name: "martinm-tls"
```

**Comment by HaveFun83** [comment]
Hi i dont use the kubernetesGateway.
This only happen when you use the ingressroute crd as the crossnamespace behavior was changed via https://github.com/traefik/traefik/pull/8260 in the traefik image v2.4.11.

My ingressroute look like this:
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`grafana.example.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: infra-grafana
          port: 80
          namespace: monitoring  <-- This here break if --providers.kubernetescrd.allowcrossnamespace is set to false which is the new default
      middlewares:
        - name: redirect-https
          namespace: ingress
  tls:
    secretName: tls-grafana
```

Maybe we should add this https://github.com/dtomcej/traefik/blob/master/docs/content/providers/kubernetes-crd.md#allowcrossnamespace as an option into the providers.kubernetesCRD values?
