### ISSUE TITLE
CRD for TLSOption doesn't support documented spec.alpnProtocols

### ISSUE THREAD

**Issue by sdwire** [traefik/traefik-helm-chart#495]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.3.2

### What version of Traefik are you using?

2.5.1

### What did you do?

Tried adding the following TLSOption using kubernetes, as suggested by https://doc.traefik.io/traefik/https/tls/#alpn-protocols

```
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: placeholder-star-tlsoption
spec:
  alpnProtocols:
    - http/1.1
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
  sniStrict: false
  preferServerCipherSuites: true
```

Helm chart 10.3.2 claims to use traefik 2.5.1, in which the ALPN protocol configuration was added

### What did you see instead?

I got an error message claiming that spec.alpnProtocols is not a valid property.

I confirmed by looking in the helm chart's CRD in github that it is not expecting the new property that the documentation says should be there.

### What is your environment & configuration?

Including traefik via helm:

```
- name: traefik
  version: 10.3.2
  repository: https://helm.traefik.io/traefik
```
Running on Docker for Desktop on Windows

### Additional Information

```shell
I realize the 2.5.1 release is less than a month old, but I really need to disable http2 for one of my services because the wildcard certificate combined with http2 connection reuse is confusing Safari.
```
