### ISSUE TITLE
TLSOption CRD missing RequireAnyClientCert value

### ISSUE THREAD

**Issue by Aetf** [traefik/traefik-helm-chart#503]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.3.5

### What version of Traefik are you using?

2.5.3

### What did you do?

Use `RequireAnyClientCert` for `TLSOption`'s `clientAuth.clientAuthType`, which is a supported value per the [doc](https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls)

### What did you see instead?

The value is not allowed. All other values listed in the doc are allowed.

### What is your environment & configuration?

I'm setting tls option using helm chart values:
```
tlsOptions:
  mtlsany:
    sniStrict: true
    clientAuth:
      clientAuthType: RequireAnyClientCert
```
