### ISSUE TITLE
AWS NLB annotations

### ISSUE THREAD

**Issue by e-tip** [traefik/traefik-helm-chart#507]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.3.6

### What version of Traefik are you using?

2.5.3

### What did you do?

I've installed traefik using the latest helm charts. and everything works. I then tried to enable ProxyProtocol so i modified the values.yaml with these values 
```
---
deployment:
  kind: DaemonSet
ingressClass:
  enabled: true
  isDefaultClass: true
ingressRoute:
  dashboard:
    enabled: false
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: certificate-arn
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes:stickiness.enabled=true,stickiness.type=source_ip,proxy_protocol_v2.enabled=true
  spec:
    externalTrafficPolicy: "Cluster"
ports:
  web:
    redirectTo: websecure
additionalArguments:
  - "--providers.kubernetescrd.allowCrossNamespace=true"
  - "--entryPoints.websecure.proxyProtocol.trustedIPs=10.0.1.0/24,10.0.2.0/24,10.0.101.0/24,10.0.100.0/24"
  - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.1.0/24,10.0.2.0/24,10.0.101.0/24,10.0.100.0/24"
  - "--entryPoints.web.proxyProtocol.trustedIPs=10.0.1.0/24,10.0.2.0/24,10.0.101.0/24,10.0.100.0/24"
  - "--entryPoints.web.forwardedHeaders.trustedIPs=10.0.1.0/24,10.0.2.0/24,10.0.101.0/24,10.0.100.0/24"
```

Doing this i expected that, on the target-group i will see proxyProtocol enabled

### What did you see instead?

Unfortunately the proxy protocol is not enabled

### What is your environment & configuration?

AWS EKS 1.20
