### ISSUE TITLE
Server Transport CRD is missing field peerCertURI

### ISSUE THREAD

**Issue by cnwaldron** [traefik/traefik-helm-chart#510]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.3.6

### What version of Traefik are you using?

2.5.3

### What did you do?

Create a ServersTransport:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: mytransport
spec:
  serverName: servername
  rootCAsSecrets: 
    - ca-secret
  certificatesSecrets: 
    - cert-secret
  peerCertURI: cluster1-ca
```

### What did you see instead?

After trying to create the ServersTransport this error was presented: 
```sh
error: error validating "traefik-servertransport.yaml": error validating data: ValidationError(ServersTransport.spec): unknown field "peerCertURI" in us.containo.traefik.v1alpha1.ServersTransport.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
I checked the CRD and compared to the Traefik documents and repo for the v 2.5.3 and they do not match the CRD created from the helm chart.
See: https://github.com/traefik/traefik/blob/v2.5.3/docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml#L81

### What is your environment & configuration?

Minikube v1.20.7 with default Traefik deployment via Helm Chart.
