### ISSUE TITLE
Helm: allow to run Traefik also on master nodes 

### ISSUE THREAD

**Issue by Cubid** [traefik/traefik-helm-chart#520]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like to be able to run traefik as DeamonSet on all nodes in the cluster included the master.

For this, I should configure the the tolerations in the template spec.

In the Helm chart it seems there is no option for this. And I temporarily use a patch as:

```
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

```

I run this patch with `kubectl patch daemonset traefik --patch "$(cat patch.yaml)`

It would be nice to be able to change the tolerations in the template.
