### ISSUE TITLE
acme.json problem: no such file or directory (even using an initContainer)

### ISSUE THREAD

**Issue by johanneskastl** [traefik/traefik-helm-chart#564]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-10.14.2

### What version of Traefik are you using?

2.6.1

### What did you do?

I enabled persistence and gave the necessary `additionalArguments` to enable a certificateresolver. I ran into the problem, that the acme.json could not be created.

```
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data


additionalArguments:
  - --certificatesresolvers.hetzner-staging.acme.caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
  - --certificatesresolvers.hetzner-staging.acme.dnschallenge="true"
  - --certificatesresolvers.hetzner-staging.acme.dnschallenge.provider="hetzner"
  - --certificatesresolvers.hetzner-staging.acme.dnschallenge.resolvers="192.168.99.1"
  - --certificatesresolvers.hetzner-staging.acme.email="some-email-address"
  - --certificatesresolvers.hetzner-staging.acme.dnschallenge.delaybeforecheck=10
  - --certificatesresolvers.hetzner-staging.acme.storage="/data/acme.json"
```

I searched the existing issues and found two things, that I tried to no avail:
- adding the annotation to the persistence section
- adding the podSecurityContext setting the fsGroup

```
persistence:
[...]
  annotations: {
    "pv.beta.kubernetes.io/gid": "65532"
  }

podSecurityContext:
  fsGroup: 65532

[...]
```

Unfortunately I still get the error shown below.
```
time="2022-02-22T21:16:55Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
```
The logs of the initContainer confirm that everything is fine:
```
mode of '/data/acme.json' changed to 0600 (rw-------)
total 0      
-rw-------    1 65532    65532          0 Feb 22 20:45 acme.json
```

Checking from the host system, I see the hostPath volume is set up and has the proper permissions.

### What did you see instead?

In the logs of the Traefik pod I get an error that the acme.json file could not be found/read:
```
time="2022-02-22T21:16:55Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
```

### What is your environment & configuration?

- k3s installed without traefik
- traefik installed via helm chart
  - configuration see above
- storage provided by local-path provisioner

### Additional Information

```shell
There are some other issues both in the Traefik issues as well as in the helm-chart issues, that describe similar problems. The difference is that in their cases, the file permissions are wrong (660 or 666 instead of 600).

The only related issues I could find are [#165](https://github.com/traefik/traefik-helm-chart/issues/165) and [#396](https://github.com/traefik/traefik-helm-chart/issues/396)
```
