### ISSUE TITLE
How is one to access the dashboard with a single traefik instance or multiple traefik instances on a cluster?

### ISSUE THREAD

**Issue by bitsofinfo** [traefik/traefik-helm-chart#604]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.19.4

### What version of Traefik are you using?

2.6.3

### What did you do?

I am deploying 2 instances of this chart. One called `traefik-internal` and one called `traefik-external`

I set in `values`  `--api.dashboard=true` on both

### What did you see instead?

I cannot access the dashboard via the IP @ either of the traefik instances LB ips

I also tried creating my own `IngressRoute` adding a custom `Host(...)` stanza.... to no avail

I noticed the `IngressRoute` on this chart references the service as:

```
    services:
    - kind: TraefikService
      name: api@internal
```

How is this supposed to determine which traefik instance, when there are multiple on the cluster/

### What is your environment & configuration?

the helm chart w/ the value noted above for the IngressRoute customization

### Additional Information

```shell
Overall both the documentation and simplicity of getting this to work is super confusing

https://github.com/traefik/traefik-helm-chart/issues/596
```

**Comment by maltegrosse** [comment]
I have two traefik instances deployed manually (as helm chart was not applicable for multi instances) in two different namespaces - traefik-int and traefik-ext. Even I deploy two ingressroutes in different namespaces (ingress allow cross namespace) - the dashboard always only refers the one traefik instance. I assume somehow the ingress class is bundled with the traefik deployment.

example:
- traefik ext - no dashboard - namespace - traefik-ext
- traefik int - one dashboard for traefik-int and one dashboard for traefik-ext -> both ingressroutes only shows traefik-int dashboard 

works:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-int
  name: traefik-dashboard-internal
  namespace: traefik-int

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`internal-routes.example.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
          namespace: traefik-int

  tls:
    certResolver: tx
```

does not work (shows internal dashboard)
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-int
  name: traefik-dashboard-public
  namespace: traefik-ext

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`public-routes.example.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
          namespace: traefik-ext

  tls:
    certResolver: tx
```
