### ISSUE TITLE
[Middleware CRDs] Schema never is the same as in the documentation

### ISSUE THREAD

**Issue by Y0ngg4n** [traefik/traefik-helm-chart#611]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.22.0

### What version of Traefik are you using?

2.7.1

### What did you do?

I have installed the Helm chart as described in the docs. I just used flux for the Helmrelease for GitOps but should be the same.
This is my Helmrelease:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: traefik
      version: "10.22.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    image:
      name: traefik # {"$imagepolicy": "flux-system:traefik:name"}
      tag: 2.7.1 # {"$imagepolicy": "flux-system:traefik:tag"}
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: true
    dashboard:
      enabled: true
      domain: traefik.oblivioncoding.pro
    rbac:
      enabled: true
    api:
      dashboard: true
      insecure: true
    globalArguments:
      - "--global.checknewversion"
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"
    #    - "--log.filePath=/var/log/traefik/traefik.log"
    #    - "--accesslog.filepath=/var/log/traefik/access.log"
    global:
      sendAnonymousUsage: false
    pilot:
      enabled: true
      token: "caf24dcf-2370-44cc-8feb-2ec08e69764b"
      dashboard: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.1.3.2
    ingressClass:
      enabled: true
      isDefaultClass: true
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
    ports:
      websecure:
        tls:
          enabled: true
```
Now i want to add a middleware:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-header
spec:
  headers:
    customRequestHeaders:
      X-Script-Name: "test"
    customResponseHeaders:
      X-Custom-Response-Header: "value"
```
It should at my middleware now.

### What did you see instead?

But if i apply that deployment i see the following:
```
error: error validating "ingress.yaml": error validating data: ValidationError(Middleware.spec): unknown field "headers" in us.containo.traefik.v1alpha1.Middleware.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

### What is your environment & configuration?

Kubernetes with talos.dev and YAML with Flux CI
