### ISSUE TITLE
Dualstack cluster, dualstack annotations - still results in singlestack ipv4 NLB in AWS

### ISSUE THREAD

**Issue by andrei-dascalu** [traefik/traefik-helm-chart#617]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.24.0

### What version of Traefik are you using?

2.8.1

### What did you do?

Values file:
```
        image:
          tag: 2.8.1
        deployment:
          replicas: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        additionalArguments:
        - "--log.level=DEBUG"
        pilot:
          enabled: false
        service:
          ipFamilyPolicy: PreferDualStack
          spec:
            externalTrafficPolicy: Local
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
            service.beta.kubernetes.io/aws-load-balancer-alpn-policy: "HTTP2Preferred"
            service.beta.kubernetes.io/aws-load-balancer-name: "<my lb name>"
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
            service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=true"
            service.beta.kubernetes.io/aws-load-balancer-subnets: "<my subnets>"
            service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "<my ip allocations>"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<my ssl arn>"
        certResolvers: {}
        ports:
          mysql:
            exposedPort: 3333
            expose: true
            protocol: TCP
            port: 3333
          web:
            exposedPort: 80
          websecure:
            exposedPort: 443
            tls:
              enabled: false
```

Running the chart with the above values results in an NLB that is stinglestack despite the DualStack prefference and despite annotations provided as per AWS specs. I am not entirely sure what could be the issue, as the cluster / vpc / subnets were created with ipv6

Issue somewhat similar to https://github.com/traefik/traefik-helm-chart/issues/453 though I have used the ipFamilyPolicy

### What did you see instead?

single stack ipv4 NLB

### What is your environment & configuration?

K8s 1.22.9, EKS
values file as per above.
