### ISSUE TITLE
Why ingress `ADDRESS` not shown

### ISSUE THREAD

**Issue by icefery** [traefik/traefik-helm-chart#621]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.24.0

### What version of Traefik are you using?

2.8.0

#### Chart

```yaml
ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: false

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    nodePort: 9000
    protocol: TCP
  web:
    port: 80
    expose: true
    exposedPort: 80
    nodePort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    nodePort: 443
    protocol: TCP

service:
  type: NodePort

securityContext:
  capabilities:
    drop: []
    add:
      - ALL
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 0
```

#### Install

```bash
helm upgrade traefik traefik/traefik \
  --install \
  --create-namespace \
  --namespace traefik \
  --values values.yaml \
  --version 10.24.0
```

#### Optionally

1. `kubectl -n default edit ingress my-app` change `ingressClassName` to `nginx`

2. change `ingressClassName` back to `traefik`

#### Ingress

```bash
kubectl get ingress -A
```

### What did you see instead?

1. Inress `ADDRESS` not shown.
   ![image](https://user-images.githubusercontent.com/61737634/182605842-97e2e701-5bf9-4697-8cda-d83816fcac41.png)

2. But they works.
   ![image](https://user-images.githubusercontent.com/61737634/182606780-b3cbb5f4-2f93-426d-b973-1a17acb21ce5.png)

3. Try to change `ingressClassName` to `nginx` and then change back. `ADDRESS` is shown.

4. external-dns can not find ingress endpoints.
   ![image](https://user-images.githubusercontent.com/61737634/182607031-698f2385-9401-4968-bb78-49e5d26bb161.png)

### What is your environment & configuration?

![image](https://user-images.githubusercontent.com/61737634/182607561-e5f68d8e-4356-4a52-9243-08d640a05ebd.png)

### Additional Information

```shell
Thanks!
```
