### ISSUE TITLE
Breaking change in minor version update: 10.26.0

### ISSUE THREAD

**Issue by sspreitzer** [traefik/traefik-helm-chart#634]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.26.0

### What version of Traefik are you using?

Helm 10.26.0

### What did you do?

ArgoCD auto update version region: 10.*

### What did you see instead?

Traefik configuration broke, ingresses unreachable.

### What is your environment & configuration?

Production

**Comment by sspreitzer** [comment]
The minor version update v1.25.1 to v1.26.0 should not have introduced breaking changes.

**Comment by mloiseleur** [comment]
Thanks for your report @sspreitzer.
Can you detail how it break your configuration ?

**Comment by sspreitzer** [comment]
@mloiseleur: We saw that suddenly all our ingresses where no longer configured in Traefik and presenting a self-signed certificate. I suspect that this has to do with rbac. Maybe a default value is missing in `values.yaml` for rbac. Resulting in maybe suddenly enabling/disabling rbac on clusters. 
For a non-breaking change I would use a default settting that would not affect installations that do not have configured rbac explicitely.
For a breaking change I would increment a major version and add a CHANGELOG description for Helm Chart users.

**Comment by mloiseleur** [comment]
@sspreitzer : I agree with you : a breaking change need CHANGELOG entry and a major version update. It was not supposed to be breaking. Can you share the _values_ file used before the update ?

**Comment by sspreitzer** [comment]
@mloiseleur Our ArgoCD Application configuration before the change:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-traefik
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 10.*
    helm:
      values: |
        deployment:
          replicas: 2
        experimental:
          plugins:
            enabled: true
        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--experimental.plugins.souin.modulename=github.com/darkweak/souin"
          - "--experimental.plugins.souin.version=v1.6.12"
          - "--experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/acouvreur/traefik-modsecurity-plugin"
          - "--experimental.plugins.traefik-modsecurity-plugin.version=v1.1.0"
        logs:
          general:
            level: INFO
        ports:
          websecure:
            tls:
              enabled: true
        service:
          annotations:
            service.beta.kubernetes.io/azure-dns-label-name: xxx
        providers:
          kubernetesIngress:
            allowExternalNameServices: true
            allowEmptyServices: true
            publishedService:
              enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
