### ISSUE TITLE
Unable to deploy on k8s 1.25 - HorizontalPodAutoscaler and PodDisruptionBudget using removed versions

### ISSUE THREAD

**Issue by mila-rodriguez-netapp** [traefik/traefik-helm-chart#639]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.24.0

### What version of Traefik are you using?

2.8.3

### What did you do?

Attempted to deploy helm chart on a Kubernetes 1.25 cluster with horizontal pod autoscaling and pod disruption budget enabled.

Relevant snippet from values.yaml:

```yaml
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
```

### What did you see instead?

```
unable to recognize \"\": no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\", unable to recognize \"\": no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2beta1\"
```

### What is your environment & configuration?

This can be reproduced on any Kubernetes 1.25 environment. I specifically reproduced it on Docker-Desktop with k8s 1.25, and also with minikube.

### Additional Information

```shell
* `PodDisruptionBudget` in `policy/v1beta1` has been deprecated for a long time and removed in k8s 1.25
  ** Replacement is version `policy/v1` available since k8s 1.21
* `HorizontalPodAutoscaler` in `autoscaling/v2beta1` has similarly been deprecated for a while and removed in k8s 1.25
  ** Note v2beta2 also deprecated and similarly will be removed in 1.26
  ** Replacement is `autoscaling/v2` available since 1.23
```

**Comment by mila-rodriguez-netapp** [comment]
The HPA issue is still present in `master`. Looks like the PDB issue was fixed in 10.24.1.

**Comment by mloiseleur** [comment]
With PR #518 , HPA is now updated to current version.

**Comment by FelipeEmerim** [comment]
We tried to deploy the latest version and got this error:

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(HorizontalPodAutoscaler.spec): unknown field "behaviour" in io.k8s.api.autoscaling.v2.HorizontalPodAutoscalerSpec
```

These are the values we used:

```yaml
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
```


I believe the error happens because of [this line](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/hpa.yaml#L38)
