### ISSUE TITLE
Daemonset cannot rollingupdate with host network due to port conflict.

### ISSUE THREAD

**Issue by comphilip** [traefik/traefik-helm-chart#645]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

11.1.0

### What version of Traefik are you using?

2.9.1

### What did you do?

Upgrade helm version to 11.1.0

### What did you see instead?

K8S cannot schedule to node due to listen ports are not available.

### What is your environment & configuration?

Helm value.yaml
```yaml
    additionalArguments:
    - --log.level=INFO
    - --ping
    - --metrics.prometheus
    deployment:
      kind: DaemonSet
    hostNetwork: true
    ports:
      metrics:
        exposePort: 9101
        port: 9101
      web:
        expose: true
        exposePort: 80
        port: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        expose: true
        exposePort: 443
        port: 443
        protocol: TCP
        tls:
          enable: true
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
      runAsNonRoot: false
      runAsUser: 0
    service:
      enabled: false
```

**Comment by mloiseleur** [comment]
Hello @comphilip,

Thanks for your report. RollingUpdate was working for you with this `values` on version 10.x of the Helm chart ?

**Comment by comphilip** [comment]
@mloiseleur RollingUpdate is working for 10.x.  Default value of  `maxSurge` and `maxUnavailable`  are change in 11.

 RolingUpdate works well after override to same values to 10.x.

```yaml
updateStrategy:
  rollingUpdate:
    maxSurge: 0 
    maxUnavailable: 1
  type: RollingUpdate
```
