### ISSUE TITLE
Chart 5.2.0 has breaking changes

### ISSUE THREAD

**Issue by Scrumplex** [traefik/traefik-helm-chart#669]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

5.2.0

### What version of Traefik are you using?

2.9.0

### What did you do?

Upgrade from Chart 5.1.1 to Chart 5.2.0

### What did you see instead?

The changes in 5.2.0 now add
```
--providers.kubernetescrd.namespaces=<release ns>
--providers.kubernetesingress.namespaces=<release ns>
```
when using default values (`i.e. RBAC enabled, but no namespaces set for the providers`)

### What is your environment & configuration?

Using FluxCD to deploy Traefik.

Values:

```
    deployment:
      replicas: 2
      additionalVolumes:
      - name: root-ca
        configMap:
          name: home-ca
      initContainers:
        # Related issue: https://github.com/traefik/traefik/issues/6972
        - name: volume-permissions
          image: busybox:1.35
          command: ["sh", "-c", "touch /data/acme.json /data/acma-local.json && chmod -Rv 600 /data/* && chown -Rv 65532:65532 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
    ingressClass:
      enabled: true
      isDefaultClass: true
    experimental:
      http3:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: true
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
    additionalVolumeMounts:
      - name: root-ca
        mountPath: "/etc/ssl/certs/home-ca.crt"
        subPath: root_ca.crt
    logs:
      access:
        enabled: true
    ports:
      traefik:
        expose: true
        exposedPort: 8080
      web:
        redirectTo: localsecure
      localsecure:
        port: 9443
        expose: true
        exposedPort: 443
        protocol: TCP
        http3: true
        tls:
          enabled: true
          options: "traefik-hardened@kubernetescrd"
          certResolver: local
      websecure:
        exposedPort: 8443
        http3: true
        tls:
          options: "traefik-hardened@kubernetescrd"
          certResolver: letsencrypt
    additionalArguments:
      - "--entrypoints.websecure.http.middlewares=traefik-security@kubernetescrd"
      - "--entrypoints.localsecure.http.middlewares=traefik-security@kubernetescrd"
    tlsOptions:
      hardened:
        minVersion: "VersionTLS12"
        cipherSuites:
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_AES_256_GCM_SHA384"
          - "TLS_CHACHA20_POLY1305_SHA256"
        curvePreferences:
          - "CurveP521"
          - "CurveP384"
        sniStrict: true
    service:
      spec:
        externalTrafficPolicy: Local
    persistence:
      enabled: true
    certResolvers:
      letsencrypt:
        email: "[redacted]"
        keyType: "EC384"
        httpChallenge:
          entryPoint: "web"
        storage: "/data/acme.json"

      local:
        email: "[redacted]"
        keyType: "EC384"
        caServer: "[redacted]"
        httpChallenge:
          entryPoint: "web"
        storage: "/data/acme-local.json"

```

### Additional Information

```shell
As this changes default behavior, it should be a major version bump.

CC @mloiseleur, Introduced by #666
```
