### ISSUE TITLE
Default TLSStore with multiple traefik releases in the same namespace

### ISSUE THREAD

**Issue by cest-pas-faux** [traefik/traefik-helm-chart#675]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

15.2.2

### What version of Traefik are you using?

2.9.1

### What did you do?

Hello,
We provide to our clients 3 different ingress classes serving 3 different purposes and allowing us to reduce the blast radius and ease the upgrade/releases process.
Historically the 3 different ingress controllers (traefik-internal, traefik-external and traefik-internal-static) are installed inside the same namespace using helm.

We had only traefik-internal so far and wanted to add the 2 missing ones, in the same namespace as the wildcards certs are all located here.

### What did you see instead?

A new helm release cannot be deployed since the name "default" for the TLSStore is already used

```
Release "traefik-internal-static" does not exist. Installing it now.
  Error: rendered manifests contain a resource that already exists. Unable to continue with install: TLSStore "default" in namespace "management" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "traefik-internal-static": current value is "traefik-internal"
  ```

As per the [documentation ](https://doc.traefik.io/traefik/https/tls/#certificates-stores):  

```
Any store definition other than the default one (named default) will be ignored, and there is therefore only one globally available TLS store.
```

Is there a way to make this setup work and allow each ingress controller to use a different default cert without creating other namespaces ?

### What is your environment & configuration?

Setup : EKS 1.21
The values file is pretty standard, some tweaks about the replicas number and some services annotations, nothing relevant for this issue

```yaml
# Traefik-external : the default cert is the one for the company tld
tlsStore:
  default:
    defaultCertificate:
      secretName: wild-company-com-tls
 ```
```yaml
# Traefik-internal: the default cert is the one for cluster internal domain
tlsStore:
  default:
    defaultCertificate:
      secretName: wild-clustername-company-org-tls
 ```
```yaml
# Traefik-internal-static: the default cert is the one for cluster internal domain
tlsStore:
  default:
    defaultCertificate:
      secretName: wild-clustername-company-org-tls
 ```
