### ISSUE TITLE
servicemonitor doesn't work

### ISSUE THREAD

**Issue by debu99** [traefik/traefik-helm-chart#691]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

17.0.5

### What version of Traefik are you using?

2.9.1

### What did you do?

servicemonitor doesn't work in helm chart

### What did you see instead?

```
kubectl describe service traefik -n ingress
Name:                     traefik
Namespace:                ingress
Labels:                   app.kubernetes.io/instance=traefik
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=traefik
                          helm.sh/chart=traefik-17.0.5
Annotations:              <none>
Selector:                 app.kubernetes.io/instance=traefik-ingress,app.kubernetes.io/name=traefik
```
Should the servicemonitor Match the labels of service instead of labels of service selector?
```
% kubectl describe servicemonitor traefik -n ingress
Name:         traefik
Namespace:    ingress
Labels:       app.kubernetes.io/instance=traefik
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=traefik
              helm.sh/chart=traefik-17.0.5
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2022-10-22T13:27:58Z
  Generation:          1
  Managed Fields:
    API Version:  monitoring.coreos.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:helm.sh/chart:
      f:spec:
        .:
        f:endpoints:
        f:jobLabel:
        f:namespaceSelector:
          .:
          f:matchNames:
        f:selector:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2022-10-22T13:27:58Z
  Resource Version:  690281
  UID:               1656488d-4dfc-40c3-b7b7-5a61bbc655f3
Spec:
  Endpoints:
    Metric Relabelings:
      Action:       drop
      Regex:        ^fluentd_output_status_buffer_(oldest|newest)_.+
      Replacement:  $1
      Separator:    ;
      Source Labels:
        __name__
    Path:  /metrics
    Port:  metrics
    Relabelings:
      Action:       replace
      Regex:        ^(.*)$
      Replacement:  $1
      Separator:    ;
      Source Labels:
        __meta_kubernetes_pod_node_name
      Target Label:  nodename
    Scrape Timeout:  5s
  Job Label:         traefik
  Namespace Selector:
    Match Names:
      ingress
  Selector:
    Match Labels:
      app.kubernetes.io/instance:  traefik-ingress
      app.kubernetes.io/name:      traefik
```

### What is your environment & configuration?

K8s + helm chart 17.0.5

**Comment by faust64** [comment]
> Should the servicemonitor Match the labels of service

Yes. ServiceMonitor selectors are used matching Services.

**Comment by mloiseleur** [comment]
Hello @debu99,

Thanks for your report.
With this parameters on v17.0.5, I can see a match between ServiceMonitor & Service. 
```bash
helm template traefik \
  -a "monitoring.coreos.com/v1" \
  --set metrics.prometheus.serviceMonitor.enabled=true \
  -n ingress traefik/traefik
```
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
[...]
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik-ingress
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-ingress
    helm.sh/chart: traefik-17.0.5
    app.kubernetes.io/managed-by: Helm
  annotations:
[...]
```

Can you provide more details about your issue ?

**Comment by mloiseleur** [comment]
Have you tried to either edit or delete this service and re-install the chart ?

**Comment by mloiseleur** [comment]
With this `values` file
```yaml
metrics:
  prometheus:
    serviceMonitor:
      enabled: true
service:
  labels:
    app.kubernetes.io/instance: traefik
```
It reproduces your issue:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-ingress
    helm.sh/chart: traefik-18.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
```

But it is expected behavior, so I will close this issue. 
Feel free to re-open it if you have more / new info on it.

**Comment by dmpe** [comment]
I think I can also obseve the very same issue. 
Using argocd 2.5.1 and chart version 19.0.3, I usually install traefik into "traefik" NS (@debu99 uses ingress NS for it). 
Hence my Service should look like:

```
kind: Service
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik
```

unfortunately, it is not when installed later on as it only contains Service label contains `app.kubernetes.io/instance: traefik`. The `-{{ .Release.Namespace }}` template gets ignored here somehow. Hence when SM is later installed, selectors do not match.
