### ISSUE TITLE
Customize labels on created TLSOptions

### ISSUE THREAD

**Issue by bitsofinfo** [traefik/traefik-helm-chart#692]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm experiencing the same issue as this: https://github.com/traefik/traefik/issues/7408

I have `--providers.kubernetesingress.labelSelector=traefik-context=external`

I also am setting `tlsOptions.external.maxVersion`... however the TLSOption that is created named `external` is not found because the CRD is looking only for objects w/ that label...

issue is that there is no way to customize the label on the generated TLSOptions created by this chart.

**Comment by mloiseleur** [comment]
Hello @bitsofinfo,

That's right. We should add this option.

**Comment by darkweaver87** [comment]
Hello @bitsofinfo,

I'm trying to reproduce and understand your issue. Obviously I can do a PR to add labels on `tlsOptions` objects created by the helm template. But I was not able to reproduce a `tlsOptions` not loaded by an ingress because of missing labels.

Here is my minimal setup:

```bash
k3d cluster create --k3s-arg '--no-deploy=traefik@servers:*' --image="rancher/k3s:v1.23.13-k3s1"

helm install traefik traefik/traefik --values=values.yaml

kubectl apply -f example.yaml
```

values.yaml:
```yaml
providers:
  kubernetesIngress:
    labelSelector: traefik-context=external

tlsOptions:
  default:
    sniStrict: true
    preferServerCipherSuites: true
  external:
    sniStrict: true
    preferServerCipherSuites: true
    maxVersion: VersionTLS13
```

example.yaml:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-tls
  labels:
    traefik-context: external
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls.options: "default-external@kubernetescrd"
spec:
  rules:
   - host: foo.docker.localhost
     http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: whoami
              port:
                number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: whoami
  name: whoami
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.8.7
          imagePullPolicy: Always
          args:
            - -port
            - "8080"
          ports:
            - containerPort: 8080
              name: web
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            tcpSocket:
              port: web
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            tcpSocket:
              port: web
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              cpu: 15m
              memory: 60Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  ports:
    - name: http
      port: 80
      targetPort: web
  selector:
    app.kubernetes.io/name: whoami
  type: ClusterIP
```

Would you mind to share a kick example ?

Thanks
