### ISSUE TITLE
Could not revert back traefik configuration

### ISSUE THREAD

**Issue by minh-oolio** [traefik/traefik-helm-chart#694]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

we implemented traefik with argocd in our system and i would like to patch more parameter but it failed 
- i replace helm parameters with Helm Valuefile for adding more line in additionalArguments
- using kubectl apply and it failed for generate
- revert it back with older yaml file but all routing gone 

Here is my application on argocd 
```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: applicaiton
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: "10.20.1"
    helm:
      parameters:
      - name: providers.kubernetesIngress.publishedService.enabled
        value: "true"
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - Validate=false
    automated:
      selfHeal: true
      prune: true 
```

### What did you see instead?

i saw log of traefik pod showing message
- No endtry point found ... 
- Not able to search tls cert 

### What version of Traefik are you using?

we are using helm chart version "10.20.1"

### What is your environment & configuration?

```yaml
# apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: till-x
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: "10.20.1"
    helm:
      parameters:
      - name: providers.kubernetesIngress.publishedService.enabled
        value: "true"
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - Validate=false
    automated:
      selfHeal: true
      prune: true
```

Add more configuration information here.
