### ISSUE TITLE
0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 2 node(s) didn't match Pod's node affinity/selector.

### ISSUE THREAD

**Issue by aliuq** [traefik/traefik-helm-chart#732]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

10.24.3

### What version of Traefik are you using?

2.8.5

### What did you do?

It was working fine, but I upgraded to the latest
```bash
> helm repo update
> helm upgrade --install traefik traefik/traefik -n traefik-system -f values.yaml
```
then uninstalled it
```bash
> helm uninstall traefik traefik/traefik -n traefik-system
> kubectl get crd | grep traefik | awk '{print $1}' | xargs kubectl delete crd
> kubectl get daemonsets.apps -n kube-system | grep traefik | awk '{print $1}' | xargs kubectl delete daemonsets.apps -n kube-system
```
and then installed the specified version `10.24.3`
```bash
> helm install traefik traefik/traefik -n traefik-system -f values1.yaml --version 10.24.3
```
and this problem appeared

### What did you see instead?

```bash
> kgs -n traefik-system

NAME      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
traefik   LoadBalancer   10.43.119.113   <pending>     32306:31498/TCP,80:31493/TCP,443:30900/TCP   118m
```

```bash
> kgp -n traefik-system

NAME                       READY   STATUS    RESTARTS   AGE
traefik-6b64765bcf-4rd5p   1/1     Running   0          2m17s
```

```bash
> k logs -n traefik-system pods/traefik-6b64765bcf-4rd5p

time="2022-11-21T09:44:49Z" level=info msg="Configuration loaded from flags."
```

```bash
> kgp -n kube-system -o wide

NAME                                            READY   STATUS    RESTARTS   AGE     IP              NODE      NOMINATED NODE   READINESS GATES
coredns-d76bd69b-8nrbj                          1/1     Running   0          58d     10.42.0.5       server1   <none>           <none>
kilo-5ndlc                                      1/1     Running   0          5h42m   172.19.15.217   server1   <none>           <none>
kilo-htp4v                                      1/1     Running   0          5h42m   172.19.18.49    node1     <none>           <none>
kilo-nmjnv                                      1/1     Running   0          5h42m   172.19.0.3      node2     <none>           <none>
local-path-provisioner-6c79684f77-2g6bj         1/1     Running   0          58d     10.42.0.6       server1   <none>           <none>
metrics-server-7cd5fcb6b7-p6x5g                 1/1     Running   0          58d     10.42.0.4       server1   <none>           <none>
snapshot-controller-0                           1/1     Running   0          58d     10.42.2.5       node2     <none>           <none>
svclb-kubesphere-router-bbs-vr-d4a38f19-bnv44   2/2     Running   0          7d4h    10.42.0.39      server1   <none>           <none>
svclb-kubesphere-router-bbs-vr-d4a38f19-cz45k   2/2     Running   0          7d4h    10.42.1.67      node1     <none>           <none>
svclb-kubesphere-router-bbs-vr-d4a38f19-mwx6g   2/2     Running   0          7d4h    10.42.2.34      node2     <none>           <none>
svclb-traefik-d6875d50-dmc2c                    0/3     Pending   0          2m31s   <none>          <none>    <none>           <none>
svclb-traefik-d6875d50-hg99d                    0/3     Pending   0          2m31s   <none>          <none>    <none>           <none>
svclb-traefik-d6875d50-nqc9t                    0/3     Pending   0          2m31s   <none>          <none>    <none>           <none>
```

### What is your environment & configuration?

<details>
<summary>k describe -n kube-system pod svclb-traefik-d6875d50-4mgxq</summary>

```bash
Name:             svclb-traefik-d6875d50-4mgxq
Namespace:        kube-system
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=svclb-traefik-d6875d50
                  controller-revision-hash=864b589dfb
                  pod-template-generation=3
                  svccontroller.k3s.cattle.io/svcname=traefik
                  svccontroller.k3s.cattle.io/svcnamespace=traefik-system
Annotations:      kubesphere.io/restartedAt: 2022-11-21T08:56:19.580Z
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    DaemonSet/svclb-traefik-d6875d50
Containers:
  lb-tcp-32306:
    Image:      rancher/klipper-lb:v0.3.5
    Port:       32306/TCP
    Host Port:  32306/TCP
    Environment:
      SRC_PORT:    32306
      DEST_PROTO:  TCP
      DEST_PORT:   32306
      DEST_IPS:    10.43.119.113
    Mounts:        <none>
  lb-tcp-80:
    Image:      rancher/klipper-lb:v0.3.5
    Port:       80/TCP
    Host Port:  80/TCP
    Environment:
      SRC_PORT:    80
      DEST_PROTO:  TCP
      DEST_PORT:   80
      DEST_IPS:    10.43.119.113
    Mounts:        <none>
  lb-tcp-443:
    Image:      rancher/klipper-lb:v0.3.5
    Port:       443/TCP
    Host Port:  443/TCP
    Environment:
      SRC_PORT:    443
      DEST_PROTO:  TCP
      DEST_PORT:   443
      DEST_IPS:    10.43.119.113
    Mounts:        <none>
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:         <none>
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  20m                   default-scheduler  0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 2 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling  8m21s (x12 over 20m)  default-scheduler  0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 2 node(s) didn't match Pod's node affinity/selector.
```
</details>

<details>
<summary>values.yaml for 10.24.3</summary>

```yaml
# Default values for Traefik
image:
  name: traefik
  tag: ""
  pullPolicy: IfNotPresent

deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  terminationGracePeriodSeconds: 60
  minReadySeconds: 0
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  additionalContainers: []
  additionalVolumes: []
  initContainers: []
  shareProcessNamespace: false
  imagePullSecrets: []

podDisruptionBudget:
  enabled: false

ingressClass:
  enabled: false
  isDefaultClass: false
  fallbackApiVersion: ""

pilot:
  enabled: false
  token: ""
experimental:
  http3:
    enabled: false
  plugins:
    enabled: false
  kubernetesGateway:
    enabled: false

ingressRoute:
  dashboard:
    enabled: false
    annotations: {}
    labels: {}

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: false
    allowEmptyServices: false
    namespaces: []

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: false
    allowEmptyServices: false
    namespaces: []
    publishedService:
      enabled: false

volumes: []

additionalVolumeMounts: []

logs:
  general:
    level: ERROR
  access:
    enabled: false
    filters: {}
    fields:
      general:
        defaultmode: keep
        names: {}
      headers:
        defaultmode: drop
        names: {}

metrics:
  prometheus:
    entryPoint: metrics

tracing: {}

globalArguments:
  - "--global.checknewversion"
  - "--global.sendanonymoususage"

additionalArguments:
  - "--entrypoints.mysql.address=:3306"

env: []

envFrom: []

ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: false
      options: ""
      certResolver: ""
      domains: []
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP
  mysql:
    port: 3306
    expose: true
    exposedPort: 32306
    protocol: TCP

tlsOptions: {}

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  annotationsTCP: {}
  annotationsUDP: {}
  labels: {}
  spec: {}
  loadBalancerSourceRanges: []
  externalIPs: []

autoscaling:
  enabled: false

persistence:
  enabled: false
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {}

certResolvers: {}

hostNetwork: false

rbac:
  enabled: true
  namespaced: false

podSecurityPolicy:
  enabled: false

serviceAccount:
  name: ""

serviceAccountAnnotations: {}

resources: {}
affinity: {}
nodeSelector:
  kubernetes.io/hostname: server1
tolerations: []

priorityClassName: ""

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  fsGroup: 65532
```
</details>

### Additional Information

```bash
> k get nodes

NAME      STATUS   ROLES                       AGE   VERSION
node1     Ready    <none>                      58d   v1.23.9+k3s1
node2     Ready    <none>                      58d   v1.23.9+k3s1
server1   Ready    control-plane,etcd,master   58d   v1.23.9+k3s1
```

```bash
> k top nodes

NAME      CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
node1     110m         5%     3633Mi          47%       
node2     72m          3%     2230Mi          60%       
server1   172m         8%     5257Mi          69%
```

**Comment by mloiseleur** [comment]
Hello @aliuq,

I'm not sure to follow. In the values.yaml, you specify a node selector:
```yaml
nodeSelector:
  kubernetes.io/hostname: server1
```
And you also specified a mysql port:
```yaml
  mysql:
    port: 3306
    expose: true
    exposedPort: 32306
    protocol: TCP
```

It seems you already have a mysql pod running on `server1` and it's unrelated to this chart. 
=> So I'll close this issue.
Feel free to re-open this issue if you have a reproducible error on current version of this Chart.
