### ISSUE TITLE
Custom NamespaceSelector in ServiceMonitor not working

### ISSUE THREAD

**Issue by grieshaber** [traefik/traefik-helm-chart#736]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.4.1

### What version of Traefik are you using?

2.9.4

### What did you do?

Installed the latest chart version and tried to enable the servicemonitor with a custom namespace-selector.

### What did you see instead?

```
➜  helm template --api-versions="monitoring.coreos.com/v1" traefik/traefik -f traefik-test.yaml --debug
```
lead to 
```
Error: YAML parse error on traefik/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 29: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 29: did not find expected key
```

And this is the "invalid" yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/component: metrics
    helm.sh/chart: traefik-20.4.1
    app.kubernetes.io/managed-by: Helm
    release: kube-prometheus-stack
spec:
  jobLabel: traefik
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
      interval: 30s
      scrapeTimeout: 5s
      relabelings:
      - action: replace
        regex: ^(.*)$
        replacement: $1
        separator: ;
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: nodename
  namespaceSelector:
        matchNames:
    - traefik-test
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/component: metrics
```

See the wrongly formated field object `namespaceSelector`

### What is your environment & configuration?

```
metrics:
  prometheus:
    entryPoint: metrics     
    serviceMonitor:
      namespaceSelector:
        matchNames:
        - traefik-test
```
and left the remaining servicemonitor config as given in the example.
