### ISSUE TITLE
ports.websecure.tls.forwardedHeaders not working

### ISSUE THREAD

**Issue by joachimnielandt** [traefik/traefik-helm-chart#767]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.8.0

### What version of Traefik are you using?

2.9.6

### What did you do?

I deployed the helm chart using Kustomization. See a redacted version below, I kept the relevant parts.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-crd-definition-v1.yaml
  - kubernetes-crd-rbac.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    includeCRDs: false
    version: 20.8.0
    releaseName: traefik
    valuesInline:
      ports:
        websecure:
          tls:
            enabled: true
            forwardedHeaders:
              trustedIPs: 
                - 10.10.10.0/24
```

### What did you see instead?

The forwardedHeaders were not functioning (I'm testing this with a whoami deployment in the cluster).

However, when applying this configuration in the following way, it does work:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes-crd-definition-v1.yaml
  - kubernetes-crd-rbac.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    includeCRDs: false
    version: 20.8.0
    releaseName: traefik
    valuesInline:
      additionalArguments:
        - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.10.10.0/24"
```

### What is your environment & configuration?

Azure AKS
Kubernetes v1.25.2

### Additional Information

```shell
Perhaps I am applying the chart incorrectly, but I'm not sure how I would troubleshoot this. Any help is much appreciated!
```

**Comment by mloiseleur** [comment]
Hello @joachimnielandt,

Thanks for your report. You are indeed applying the chart incorrectly but the documentation in values.yaml is misleading. 

It may work with this values file:
```yaml
ports:
  websecure:
    forwardedHeaders:
      trustedIPs: 
        - 10.10.10.0/24
```

You can see resources created with helm like this:
```bash
helm template traefik -f myvalues.yaml traefik/traefik 
```

I'll see what I can do to improve how it's documented in default `values`.
