### ISSUE TITLE
Some options for metrics seem to be hardcoded not allowing to modification through values

### ISSUE THREAD

**Issue by feniix** [traefik/traefik-helm-chart#770]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.8.0

### What version of Traefik are you using?

2.9.4

### What did you do?

```
helm template traefik traefik/traefik --version 20.8.0 -f helm-values.yml -n traefik-v2 --dry-run > something.yaml
```

relevant helm values

```
metrics:
  # datadog:
  #   address: 127.0.0.1:8125
  # influxdb:
  #   address: localhost:8089
  #   protocol: udp
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
```

expected relevant args

```
      - args:
        - --entrypoints.metrics.address=:9100/tcp
        - --entrypoints.traefik.address=:9000/tcp
        - --entrypoints.web.address=:8000/tcp
        - --entrypoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --metrics.prometheus.addRoutersLabels=true
        - --metrics.prometheus.addServicesLabels=true
        - --metrics.prometheus.addEntrypointsLabels=true
```

### What did you see instead?

```
      - args:
        - --entrypoints.metrics.address=:9100/tcp
        - --entrypoints.traefik.address=:9000/tcp
        - --entrypoints.web.address=:8000/tcp
        - --entrypoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --metrics.prometheus.addRoutersLabels=true
```

### What is your environment & configuration?

osx monterrey Apple M1 Pro
helm "v3.10.3"

**Comment by danielitus** [comment]
I am experiencing a similar issue with the access log in my Traefik deployment. Specifically, the configuration for the fields and headers in the access log does not seem to be applied as expected. My values.yml have the following:

```
accessLog:
      filePath: ""
      format: json
      bufferingSize: 0
      filters:
        statusCodes: ["200-600"]
        retryAttempts: true
        minDuration: 20
      fields:
        defaultMode: keep
        names:
          ClientUsername: drop
        headers:
          defaultMode: keep
          names:
            User-Agent: keep
            Authorization: drop
            Content-Type: keep
```

Running a ```kubectl describe deployment traefik``` gives me the following output, where the flag for **accesslog.fields.headers.defaultmode** is set to drop.


```
     ...
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetesingress
      --entrypoints.web.http.redirections.entryPoint.to=:443
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --entrypoints.websecure.http.tls=true
      --accesslog=true
      --accesslog.fields.defaultmode=keep
      --accesslog.fields.headers.defaultmode=drop
```

**Comment by project0** [comment]
@feniix the expected values you are missing are already per default "true" (see [docs](https://doc.traefik.io/traefik/observability/metrics/prometheus/#addserviceslabels)), so there is no need to enable them explicitly in the helm chart.
At the moment It looks like we check if the value is set to "false" to and set the argument only on false.
I agree that this is somehow irritating, but it is also very difficult to change existing behaviors without risk of breaking something else. 

@danielitus You need to ensure to respect the case sensitivity, your configuration does not work because the property name in your value should be actually fully lower cased: `defaultmode`. I also want to emphasize on creating a separate bug ticket for this as it is not related to this issue:

```yaml
      fields:
        defaultmode: keep
        names:
          ClientUsername: drop
        headers:
          defaultmode: keep
```
