### ISSUE TITLE
Transfer the client source ip from GCP load balancer to traefik ingress controller

### ISSUE THREAD

**Issue by smiledevopsfr** [traefik/traefik-helm-chart#771]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

latest

### What version of Traefik are you using?

latest

### What did you do?

I have a SFTP service hosted in the kubernetes engine is behind a traefik ingress controller which is behind a GCP regional external http load balancer.
When a sftp client connects to the SFTP service, the ip we see in the SFTP service logs is the sftp's pod ip : 10.31.68.49.
I need the right configuration to have the client source ip on the logs.

I use this configuration, but it doesn't work for me:
```
additionalArguments:
  - "--log.level=DEBUG"
  - "--api.insecure"
  - "--accesslog"
  - "--accesslog.fields.headers.defaultmode=keep"
  - "--providers.kubernetescrd"
  - "--serversTransport.insecureSkipVerify=true"
  - '--providers.file.filename=/etc/traefik/dynamic.toml'
  - "--entryPoints.web.proxyProtocol.insecure"
  - "--entryPoints.websecure.proxyProtocol.insecure"
  - "--entryPoints.web.forwardedHeaders.insecure"
  - "--entryPoints.websecure.forwardedHeaders.insecure"
```

```
service:
  enabled: true
  type: LoadBalancer
  # Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
    use-proxy-protocol: "true"
  annotationsTCP: {}
  # Additional annotations for UDP service only
  annotationsUDP: {}
  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}
  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: "x.x.x.x"
    # clusterIP: "2.3.4.5"
  loadBalancerSourceRanges:
    []
    # - 192.168.0.1/32
    # - 172.16.0.0/16
  externalIPs:
    []
    # - 1.2.3.4
```
Any idea please ?

![image (2)](https://user-images.githubusercontent.com/121098196/208654351-976cf290-abb9-4a48-bf35-4c0d4f32d74a.png)

### What did you see instead?

When a sftp client connects to the SFTP service, the ip we see in the SFTP service logs is the sftp's pod ip : 10.31.68.49.
I need the right configuration to have the client source ip on the logs.

### What is your environment & configuration?

Yaml
