### ISSUE TITLE
Dashboard seems to be missing the service api@internal

### ISSUE THREAD

**Issue by shadycuz** [traefik/traefik-helm-chart#773]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-20.8.0

### What version of Traefik are you using?

v2.9.6

### What did you do?

I deployed the helm chart according to the readme.

### What did you see instead?

I was not able to reach the dashboard via a port forward or exposing it using the example.

### What is your environment & configuration?

This was the overides I used:

```yml
# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: true
    # Custom match rule with host domain
    matchRule: Host(`traefik.mysite.co`)
    entryPoints: ["websecure"]
    # Add custom middlewares : authentication and redirection
    middlewares:
      - name: traefik-dashboard-auth

# Configure ports
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
    tls:
      enabled: false

persistence:
  enabled: true
  name: data
#  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "do-block-storage"
  path: /data
  annotations: {}
  # subPath: "" # only mount a subpath of the Volume into the pod

certResolvers:
  letsencrypt:
    # for challenge options cf. https://doc.traefik.io/traefik/https/acme/
    email: myemail@gmail.com
    httpChallenge:
      entryPoint: "web"
    # It has to match the path with a persistent volume
    storage: /data/acme.json

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: mypassword

  - apiVersion: traefik.containo.us/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret
```

### Additional Information

I first tried to port-forward to reach the dashboard but that didn't work. I got `404 page not found`. I then tried to expose it via a password protected ingress according to this [guide](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#publish-and-protect-traefik-dashboard-with-basic-auth). But I still got the same 404. 

I can see that the "traefik-dashboard" `ingressroutes.traefik.containo.us` was created but I do not see the `api@internal` service? `traefikservices.traefik.containo.us` list no objects but I'm assuming something should be there? 

Also very strange the port-forward is not working on port 9000.

EDIT: So setting the ingressRoute back to the default values:

```yaml
ingressRoute:
  dashboard:
    enabled: true
    # Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
    annotations: {}
    # Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
    labels: {}
    # The router match rule used for the dashboard ingressRoute
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    # Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
    # By default, it's using traefik entrypoint, which is not exposed.
    # /!\ Do not expose your dashboard without any protection over the internet /!\
    entryPoints: ["traefik"]
    # Additional ingressRoute middlewares (e.g. for authentication)
    middleware: []
```

Does allow me to access the Traefik dashboard using port-forward on port 9000. But I would still like to expose it with the "Publish and protect Traefik Dashboard with basic Auth" settings that don't seem to work.

**Comment by mloiseleur** [comment]
That's probably because you disabled TLS on `websecure` entrypoints:
```yaml
# Configure ports
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
    tls:
      enabled: false   <======= HERE
```

Also, when you try to access it with a web browser, don't forget to add the trailing `/` : from `/dashboard` to `/dashboard/`.
