### ISSUE TITLE
ServiceMonitor generates labels that cannot match anything

### ISSUE THREAD

**Issue by achernya** [traefik/traefik-helm-chart#791]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.0.0

### What version of Traefik are you using?

2.9.6

### What did you do?

I've installed kube-prometheus-stack into namespace`monitoring` and traefik into namespace `ingress`, using the `values.yaml` below.

### What did you see instead?

In prometheus, I can see the generated configuration using the ServiceMonitor stanzas, but nothing shows up in targets or service discovery as matching these labels.

Looking at the generated configs, ServiceMonitor has the following matchLabels

```yaml
selector:
  matchLabels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: ingress-ingress
    app.kubernetes.io/name: traefik
```

and the service has the following labels:

```yaml
metadata:
 labels:
   app.kubernetes.io/component: metrics
   app.kubernetes.io/instance: ingress
   app.kubernetes.io/managed-by: Helm
   app.kubernetes.io/name: traefik
```

and the traefik pods have the following labels:

```yaml
  labels:
    app.kubernetes.io/instance: ingress-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
```

These selectors are mutually exclusive: the only entity that matches component=metrics is the service does not match instance=ingress-ingress. Similarly, the only instances that have instance=ingress-ingress don't have component=metrics.

Turning off prometheus.service.enabled doesn't work either --- while it does end up removing the component=metrics requirement by switching to labelSelector over metricsLabelSelector in https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/servicemonitor.yaml#L64-L69, there's no `metrics` named port in the default service. 

It seems to me that either `metricsLabelSelector` needs to have a different instance or a different instance needs to be applied at the metrics service definition. 

### What is your environment & configuration?

`values.yaml`
```yaml
  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enable: true
        additionalLabels:
          release: "monitoring"
```

### Additional Information

I'm applying the helm chart using ArgoCD 2.6.0

**Comment by achernya** [comment]
This might be an instance of https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing with argocd clobbering `app.kubernetes.io/instance`.

**Comment by mloiseleur** [comment]
Using Helm CLI and your _values_ file
```bash
helm template ingress -a monitoring.coreos.com/v1 -f values.yaml -n ingress traefik/traefik | grep -C 5 app.kubernetes.io/instance
```
It produces a `ServiceMonitor` with labels that match those of dedicated `Service` metrics
```yaml
kind: ServiceMonitor
metadata:
  name: ingress-traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-ingress
    app.kubernetes.io/component: metrics
  [...]
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: ingress-ingress
      app.kubernetes.io/component: metrics
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-traefik-metrics
  namespace: ingress
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: ingress-ingress
    app.kubernetes.io/component: metrics
```

So yes, it's coming from ArgoCD.
You may be interested to set [instanceLabelOverride](https://github.com/traefik/traefik-helm-chart/blob/0f51df0eedf774942de93262f4fda579e00b0f98/traefik/values.yaml#L868).
