### ISSUE TITLE
Helm Chart does not set correctly accessLog headers

### ISSUE THREAD

**Issue by RafaelAybar** [traefik/traefik-helm-chart#793]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

20.8.0

### What version of Traefik are you using?

2.9.6

### What did you do?

Hi, I wanted to configure  some headers, with this configuration:

```yaml  logs:
    access:
      enabled: true
      format: json
      bufferingSize: 100
      headers:
        defaultMode: keep
        names:
          User-Agent: redact
          Autorization: keep
          Content-Type: keep
```

### What did you see instead?

Instead of that, I receive a wrong configuration: 

```bash
          - "--accesslog=true"
          - "--accesslog.format=json"
          - "--accesslog.fields.defaultmode=keep"
          - "--accesslog.fields.headers.defaultmode=drop"
```

### What is your environment & configuration?

* OS: Fedora 37.
* Helm version:  `version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.18.10"`
