### ISSUE TITLE
Lack of metrics for custom Entrypoint and IngressRouteTCP

### ISSUE THREAD

**Issue by thevops** [traefik/traefik-helm-chart#809]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v21.2.0

### What version of Traefik are you using?

v2.9.8

### What did you do?

I added custom Entrypoint: `--entrypoints.electrum-wss.address=:50004/tcp`
I enabled Prometheus metrics: `--metrics.prometheus=true`
I enabled DEBUG level log: `--log.level=DEBUG` and access log `--accesslog=true`.

I can see metrics for default Entrypoints like web, websecure, metrics, and traefik, but I don't see any metrics for my custom Entrypoint `electrum-wss`.

I would like to get metrics for my custom Entrypoint and IngressRouteTCP.

### What did you see instead?

There is just one thing that I found related to my custom TCP Entrypoint. Every time I send request to my application behind IngressRouteTCP there is just single line in logs:
```
level=debug msg="Handling TCP connection from xx.xx.xx.xx:21336 to 10.92.0.66:50004"
```
Nothing more. Even no metrics about that.

### What is your environment & configuration?

```
deployment:
  replicas: 2

service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: XXXXXXXXXXX

additionalArguments:
  - --api.insecure=true

metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      enabled: true

logs:
  general:
    level: DEBUG
  access:
    enabled: true

ports:
  electrum-wss:
    port: 50004
    expose: true
    protocol: TCP
```
