### ISSUE TITLE
Hortizonal Pod Scaling fails without pod.spec.container.resources.limits defined

### ISSUE THREAD

**Issue by timatlee** [traefik/traefik-helm-chart#812]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.2.1

### What version of Traefik are you using?

2.9.9

### What did you do?

I deployed Traefik using the Helm chart, following the example at https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#install-with-auto-scaling, but find that HPA does not work as expected. I am getting an <unknown>/80% result from `get HPA`.

```
kubectl apply -f 00-namespace.yaml
kubectl apply -f 01-combined.yaml
helm install -n traefik -f values.yaml traefik traefik/traefik
```

00-namespace.yaml does what it says on the tin - creates a namespace.

01-combined.yaml is as follows:
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-data
  namespace: traefik
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cephfs/apps/traefik"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: traefik
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

values.yaml is as follows:
```yaml
deployment:
  replicas: null

autoscaling:
  enabled: true
  maxReplicas: 2

service:
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.4.10

# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: true
    # Custom match rule with host domain
    matchRule: Host(`traefik.local`)
    entryPoints: ["web", "websecure"]
    # Add custom middlewares : authentication and redirection
    # middlewares:
    #   - name: traefik-dashboard-auth

persistence:
  enabled: true
  existingClaim: traefik-data
  accessMode: ReadWriteOnce
  size: 10Gi
  name: data
  path: /data

metrics:
  prometheus:
    enabled: true
    service:
      enabled: true
```

### What did you see instead?

I will find the following events:
```shell
> kubectl -n traefik get events
14s         Warning   FailedGetResourceMetric        horizontalpodautoscaler/traefik   failed to get cpu utilization: missing request for cpu
14s         Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/traefik   invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu
```

Looking at HPA,
```shell
> kubectl get hpa -n traefik
NAME      REFERENCE            TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
traefik   Deployment/traefik   <unknown>/80%   1         2         0          14s
```

### What is your environment & configuration?

Kubernetes version v1.24.11+k3s1.

Home-lab environment. No cloud provided services in use.

Arguments are defined in the above sections.

Master and worker nodes are Debian 11.

I don't know what else I should populate here.

### Additional Information

While looking into this, I find this issue: https://github.com/kubernetes-sigs/metrics-server/issues/989#issuecomment-1313971365

Evaluating the deployment from the Traefik chart, I do not see `pod.spec.container.resources.limits` defined in the deployment. Describing the deployment, I can also see the definitions are absent.

```shell
> kubectl -n traefik describe deployment
# Snip...
  Containers:
   traefik:
    Image:       docker.io/traefik:v2.9.9
    Ports:       9100/TCP, 9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entrypoints.metrics.address=:9100/tcp
      --entrypoints.traefik.address=:9000/tcp
      --entrypoints.web.address=:8000/tcp
      --entrypoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetesingress
      --entrypoints.websecure.http.tls=true
      --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
    Liveness:     http-get http://:9000/ping delay=2s timeout=2s period=10s #success=1 #failure=3
    Readiness:    http-get http://:9000/ping delay=2s timeout=2s period=10s #success=1 #failure=1
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /tmp from tmp (rw)
  Volumes:
# Snip ...
```

I don't know how to..  patch..  the deployment after it's been applied via the Helm chart, but if I edit the deployment with OpenLens to include resource limits, I no longer see the errors being generated, and `get hpa` shows a valid target:

```shell
> kubectl get hpa -n traefik
NAME      REFERENCE            TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
traefik   Deployment/traefik   0%/80%    1         2         1          7m40s
```

Describing the deployment also shows the target resource limits that I manually edited in:

```shell
> kubectl -n traefik describe deployment
# Snip...
  Containers:
   traefik:
    Image:       docker.io/traefik:v2.9.9
    Ports:       9100/TCP, 9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entrypoints.metrics.address=:9100/tcp
      --entrypoints.traefik.address=:9000/tcp
      --entrypoints.web.address=:8000/tcp
      --entrypoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetesingress
      --entrypoints.websecure.http.tls=true
      --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
    Limits:
      cpu:        250m
      memory:     128Mi
    Liveness:     http-get http://:9000/ping delay=2s timeout=2s period=10s #success=1 #failure=3
    Readiness:    http-get http://:9000/ping delay=2s timeout=2s period=10s #success=1 #failure=1
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /tmp from tmp (rw)
# Snip ...
```
```
