### ISSUE TITLE
TLSOptions do not get applied

### ISSUE THREAD

**Issue by eddykaya** [traefik/traefik-helm-chart#814]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.2.1

### What version of Traefik are you using?

2.9.9

### What did you do?

We have two ingress controllers in one namespace, handling different workloads.

I want to define a tlsoption for a namespace and apply it to every ingress object a traefik provides. Therefore, I defined the following values.yaml:

```yaml
fullnameOverride: ${fullnameOverride}

image:
  registry: <registry>
  repository: traefik
  # defaults to appVersion
  tag: ""
  pullPolicy: IfNotPresent

service:
  spec:
    loadBalancerIP: ${loadBalancerIP}
  annotations:
    loadbalancer.openstack.org/timeout-client-data: "300000"
    loadbalancer.openstack.org/timeout-member-data: "300000"

ports:
  websecure:
    tls:
      enabled: true
      options: ${namespace}-tls-traefik-${instance}@kubernetescrd

tlsOptions:
  tls-traefik-${instance}:
    minVersion: VersionTLS12
    cipherSuites:
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_FALLBACK_SCSV
    curvePreferences:
      - CurveP256
      - CurveP384
      - CurveP521
      - X25519

rbac:
  namespaced: false

logs:
  general:
    level: INFO
  access:
    enabled: true

providers:
  kubernetesCRD:
    labelSelector: expose_via in (${labelSelector_expose_via}, all)
  kubernetesIngress:
    labelSelector: expose_via in (${labelSelector_expose_via}, all)

additionalArguments:
  - "--providers.kubernetescrd.namespaces=${namespace}"
  - "--providers.kubernetesingress.namespaces=${namespace}"
``` 

However, when applying everything, the resources are present but no route is started because of an "unknown tlsoption" error.

### What did you see instead?

Traefik cannot find the tlsoptions

### What is your environment & configuration?

kubernetes v.1.24.8
