### ISSUE TITLE
IngressRouteTCP Error

### ISSUE THREAD

**Issue by tsimouris** [traefik/traefik-helm-chart#820]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v22.1.0

### What version of Traefik are you using?

2023-04-07

### What did you do?

Applying the ingress-route-tcp.yml:

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft
  namespace: default
spec:
  entryPoints:
    - minecraft
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: svc- minecraft
          port: 25565
```
### What did you see instead?

```shell
Error from server (BadRequest): error when creating "ingress-route-tcp.yml": IngressRouteTCP in version "v1alpha1" cannot be handled as a IngressRouteTCP: strict decoding error: unknown field "spec.routes[0].kind"
```

### REFERENCES:
- [guide](https://www.reddit.com/r/Traefik/comments/dfa3ld/minecraft_and_traefik_20/)
-  [Traefik](https://traefik.io/) installed via this [helm chart](https://github.com/traefik/traefik-helm-chart/releases/tag/v22.1.0)

### Additional Information

I remember reading somewhere that there have been issues with the CRDs being applied and have since applied them.

I really dont know if i applied the right thing for the CRDs, here is where I found [it](https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/#definitions)

Do I need to declare a `MiddlewareTCP` ?
