### ISSUE TITLE
Breaking vhange in tlsoptions.yaml

### ISSUE THREAD

**Issue by wargamez** [traefik/traefik-helm-chart#822]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

2.9.10

### What version of Traefik are you using?

2.9.10

### What did you do?

This commit https://github.com/traefik/traefik-helm-chart/commit/0244dde31be80432516030045309aa2a122d12d1 introduces a breaking change to Client Authentication (mTLS) compared to using just :  
{{- toYaml $config | nindent 2 }}

# values.yaml...
tlsOptions:
  clientca:
    clientAuth:
      # caFiles:
      #  - /clientcacerts/clientcacert.crt
      secretNames:
        - client-ca-cert
      clientAuthType: RequireAndVerifyClientCert

Ref: https://doc.traefik.io/traefik/https/tls/
As you can see, neither secretsNames nor clientAuthType is supported with the introduction of this change.

### What did you see instead?

Keeping the old template

### What is your environment & configuration?

Rancher 2.7, kubernetes 1.23, traefik 2.9.10

**Comment by mloiseleur** [comment]
Thanks for your report @wargamez.

That is correct, this option is valid, despite it's missing from documentation.

@eddykaya Would you please open a PR for fixing this issue ?

**Comment by eddykaya** [comment]
@mloiseleur sure

**Comment by eddykaya** [comment]
@wargamez I just templated the chart before and after this breaking change, the result seems identical to me:

Before my commit:
```yaml
# Source: traefik/templates/tlsoption.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: clientca
  namespace: default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: release-name-default
    helm.sh/chart: traefik-22.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
    - client-ca-cert
```

After my commit:
```yaml
# Source: traefik/templates/tlsoption.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: clientca
  namespace: default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: release-name-default
    helm.sh/chart: traefik-22.1.0
    app.kubernetes.io/managed-by: Helm    
spec:
  clientAuth:
      clientAuthType: RequireAndVerifyClientCert
      secretNames:
      - client-ca-cert
```

Would you please explain the problem in detail so that I can fix it appropriately?
