### ISSUE TITLE
AWS internal NLB targetPort is ignored

### ISSUE THREAD

**Issue by TLPNull** [traefik/traefik-helm-chart#825]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

22.0.0

### What version of Traefik are you using?

2.9.9

### What did you do?

Using AWS NLB, when settings targetPort to a differente port, for TLS termination, the value is ignored.

I need to do TLS termination, where the traffic come from HTTPS and is redirect to HTTP after reaching the NLB

```
  websecure:
    port: 443
    targetPort: 80
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
```

### What did you see instead?

The targetPort is always the name, in this case websecure, which translate to 443

Ref: https://github.com/traefik/traefik-helm-chart/blob/480c17f6d5ff3bb2b722d39802ea16ad36183257/traefik/templates/_service-internal.tpl#L41

### What is your environment & configuration?

```
service:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.internal
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:123456789012:certificate/abcdef12-3456-7890-abcd-ef1234567890
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: websecure
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-abcdef12"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
```

### Additional Information

```shell
Changed `_service-internal.tpl` line 41 to `targetPort: {{ default $name $config.targetPort }}`, so the desired result is achieved
```
