### ISSUE TITLE
clusterrole wrong apigroup or wrong list/get

### ISSUE THREAD

**Issue by brightdroid** [traefik/traefik-helm-chart#835]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

22.2.0

### What version of Traefik are you using?

2.9.10

### What did you do?

Update chart from 21.2.0 to 22.2.0 with argocd

### What did you see instead?

After upgrade no ingress works and  I can see these logs (traefik pods):
```
[traefik-rg8wm] W0425 09:32:21.141862       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSOption: tlsoptions.traefik.io is forbidden: User "system:serviceaccount:traefik:traefik" cannot list resource "tlsoptions" in API group "traefik.io" at the cluster scope
[traefik-rg8wm] E0425 09:32:21.143198       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSOption: failed to list *v1alpha1.TLSOption: tlsoptions.traefik.io is forbidden: User "system:serviceaccount:traefik:traefik" cannot list resource "tlsoptions" in API group "traefik.io" at the cluster scope
[traefik-6dblq] W0425 09:32:21.513794       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.io is forbidden: User "system:serviceaccount:traefik:traefik" cannot list resource "serverstransports" in API group "traefik.io" at the cluster scope
[traefik-6dblq] E0425 09:32:21.513832       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ServersTransport: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.io is forbidden: User "system:serviceaccount:traefik:traefik" cannot list resource "serverstransports" in API group "traefik.io" at the cluster scope
```

### What is your environment & configuration?

- k3s v1.26.3+k3s1
- traefik values.yaml (stripped down)
```yaml
deployment:
  kind: DaemonSet

priorityClassName: cluster-critical

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

globalArguments: []

ports:
  web:
    port: 8080
    redirectTo: websecure
  websecure:
    expose: true
    port: 8443
    tls:
      enabled: true

tlsOptions:
  default:
    minVersion: VersionTLS12
    
tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-cert

service:
  spec:
    loadBalancerIP: "x.x.x.x"
    externalTrafficPolicy: Local
```
