### ISSUE TITLE
HTTP challenge is not enabled & acme.json Permission denied

### ISSUE THREAD

**Issue by PahaCore** [traefik/traefik-helm-chart#847]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

k3s

### What version of Traefik are you using?

2.9.4

### What did you do?

level=error msg="The ACME resolver "le" is skipped from the resolvers list because: unable to get ACME account: open /data/acme.json: permission denied"

how to use traefik for tls

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --log.level=ERROR
      - --accesslog=false
      - --global.checknewversion
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.http.redirections.entryPoint.to=:443
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --providers.file.directory=/file
      - --certificatesresolvers.le.acme.email=mail@mail.com
      - --certificatesresolvers.le.acme.storage=/data/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data
    podSecurityContext:
      fsGroup: 65532
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
          securityContext
            runAsNonRoot: true
              runAsGroup: 65532
              runAsUser: 65532
          volumeMounts:
            - name: data
            ```
level=error msg="The ACME resolver "le" is skipped from the resolvers list because: unable to get ACME account: open /data/acme.json: permission denied"

how to use traefik for tls

### What did you see instead?

that's how a file is created
, but there are no such instructions in traefik

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --log.level=ERROR
      - --accesslog=false
      - --global.checknewversion
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.http.redirections.entryPoint.to=:443
      - --entrypoints.web.http.redirections.entryPoint.scheme=websecure
      - --providers.file.directory=/file
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=mail@mail.com
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.storage=/le/acme.json
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - name: config-file
        mountPath: file/
        type: configMap
    persistence:
      enabled: true
      name: le
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /le
    securityContext:
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsUser: 0
      runAsNonRoot: false
```

and all this makes sense if the file provider will receive tls
, but nothing happens

```yaml
  ittools.yaml: |-
    http:
      routers:
        ittools-router:
          entryPoints:
          - web
          service: ittools-service
          rule: Host(`ittools.domen.com`)
	  tls:
	    certResolver: le
      services:
        ittools-service:
          loadBalancer:
            servers:
            - url: http://192.168.88.3:8888
	    passHostHeader: true
```

### What is your environment & configuration?

k3s
