### ISSUE TITLE
IngressRoute: Traffic not exposed until CRDs applied manually

### ISSUE THREAD

**Issue by grossdaniel85** [traefik/traefik-helm-chart#849]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

23.0.1

### What version of Traefik are you using?

v2.10.1

## Description

It seems, that one needs to apply CRDs after the installation of traefik chart to route the traffic correctly. It has to be done manually, **and** the traefik pod needs to be restarted. This is not expected during an installation from scratch.

## How to reproduce

* install the traefik chart: `helm install traefik traefik/traefik -n traefik --version 23.0.1 -f t-values.yaml` (see the values file provided below)
* install default nginx chart: `helm install 
nginx oci://registry-1.docker.io/bitnamicharts/nginx -n nginx --set service.type=ClusterIP`
* apply ingressRoute yaml: `kubectl apply -f nginx-ingress.yaml -n nginx`

### nginx-ingress.yaml

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.<my-domain>`)
      kind: Rule
      services:
        - name: nginx
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-https
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx.<my-domain>`)
      kind: Rule
      services:
        - name: nginx
          port: 80
      middlewares:
        - name: redirect-https

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: "https"
    permanent: true
    port: "443"

```

### t-values.yaml

```yaml
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: false
      options: ""
      certResolver: ""
      domains: []
  mqttsecure:
    port: 1884
    expose: true
    exposedPort: 8883
    protocol: TCP

tlsOptions: {}
ingressRoute:
  dashboard:
    enabled: false
    annotations: {}
    labels: {}

providers:
  kubernetesCRD:
    allowCrossNamespace: false
    allowEmptyServices: false
    allowExternalNameServices: false
    enabled: true
    namespaces: []
  kubernetesIngress:
    allowEmptyServices: false
    allowExternalNameServices: false
    enabled: true
    namespaces: []
    publishedService:
      enabled: false

ingressClass:
  enabled: false
  isDefaultClass: false
  fallbackApiVersion: ""

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  annotationsTCP:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-name: "<my-lb-name>"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<valid acm cert arn for my domain>"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
  spec:
    externalTrafficPolicy: Local
  loadBalancerSourceRanges: []
  externalIPs: []

rbac:
  enabled: true
  namespaced: false
podSecurityPolicy:
  enabled: false
serviceAccount:
  name: ""

serviceAccountAnnotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  fsGroup: 65532

```

## Expectation:

* nginx ui is reachable under `nginx.<my-domain>`, as specified in ingressRoute

### What did you see instead?

* the ingressRoutes are installed, but the nginx ui is not reachable.
* after manually applying the CRDs by executing `kubectl apply --server-side --force-conflicts -k https://github.com/traefik/traefik-helm-chart/traefik/crds/` **and** restarting the traefik pod, the nginx ui is reachable.

### What is your environment & configuration?

* kubectl: 
 ```Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```
* helm: `version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}`
* Cluster: EKS, version 1.25
