### ISSUE TITLE
Generated ServiceMonitor doesn't work

### ISSUE THREAD

**Issue by tomasbedrich** [traefik/traefik-helm-chart#852]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

23.0.1

### What version of Traefik are you using?

v2.10.1

### What did you do?

I deployed Traefik Helm chart including ServiceMonitor.  My expectation is for Prometheus-operator to pick up the ServiceMonitor & setup targets based on that. The ServiceMonitor is discovered indeed, but it is "dropped" based on relabeling config.

### What did you see instead?

I debugged the dropping rule to be `__meta_kubernetes_endpoint_port_name`, which is based [on the value in a ServiceMonitor template](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/servicemonitor.yaml#L27). When I manually update the ServiceMonitor to use `targetPort: 9100` instead of `port: metrics`, it starts to work properly – Traefik instances are discovered by Prometheus.

### What is your environment & configuration?

```terraform
resource "helm_release" "traefik" {
  name       = "traefik"
  repository = "https://helm.traefik.io/traefik"
  chart      = "traefik"
  namespace  = kubernetes_namespace.traefik.metadata[0].name
  version    = "23.0.1"

  values = [jsonencode({
    deployment = {
      kind = "DaemonSet"
    }
    service = {
      spec = {
        externalTrafficPolicy = "Local"
      }
      annotations = local.lb_annotations
    }
    ports = {
      websecure = {
        http3 = {
          enabled        = true
          advertisedPort = 443
        }
      }
    }
    additionalArguments = [
      "--entrypoints.web.http.redirections.entryPoint.to=:443",
    ]
    metrics = {
      prometheus = {
        serviceMonitor = {
          enabled = true
        }
      }
    }
  })]
}
```

```terraform
resource "helm_release" "prometheus" {
  chart      = "kube-prometheus-stack"
  repository = "https://prometheus-community.github.io/helm-charts"
  name       = "monitoring"
  namespace  = kubernetes_namespace.monitoring.metadata[0].name
  version    = "45.7.1"

  values = [jsonencode({
    prometheus = {
      prometheusSpec = {
        # ...
        # override default behavior to match all ServiceMonitors in specified namespaces
        serviceMonitorSelectorNilUsesHelmValues = false
        serviceMonitorNamespaceSelector = {
          matchExpressions = [{
            key      = "kubernetes.io/metadata.name"
            operator = "In"
            values = [
              # ...
              kubernetes_namespace.traefik.metadata.0.name,
            ]
          }]
        }
      }
    }
  })]
}
```

Generated ServiceMonitor:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-23.0.1
  name: traefik
  namespace: traefik
spec:
  endpoints:
  - path: /metrics
     # port: metrics # <<<<<<<<<< original value
    targetPort: 9100 # <<<<<<<<<< this works
  jobLabel: traefik
  namespaceSelector:
    matchNames:
    - traefik
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/name: traefik
```
