### ISSUE TITLE
http3 support broken for 3.0 support

### ISSUE THREAD

**Issue by davhdavh** [traefik/traefik-helm-chart#853]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v23.0.1

### What version of Traefik are you using?

v3.0.0-beta2

### What did you do?

Tried:
```
experimental:
      v3:
        enabled: true
image:
  tag: v3.0.0-beta2
ports:
  websecure:
    asDefault: true
    http3: {}
```
and
```
experimental:
      v3:
        enabled: true
image:
  tag: v3.0.0-beta2
ports:
  websecure:
    asDefault: true
    http3:
      enabled: true
```
The former is the correct v3 config, and will run the http3 udp port, but it wont actually get mapped because the latter is needed for helm to see it, but it will give an error on traefik start because of invalid config.

### What did you see instead?

http3 support works with either config in v3

### What is your environment & configuration?

Latest
