### ISSUE TITLE
Datadog tracing failing to initialise when using environment variable in the `localAgentHostPort` config

### ISSUE THREAD

**Issue by juanwolf** [traefik/traefik-helm-chart#884]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have upgraded traefik from `v2.8.8` to `v2.10.3` where datadog's tracing is enabled however the tracer failed to initialise.

### What did you see instead?

Traefik was unable to initialise the datadog tracer and was throwing these errors:

```
2023/07/03 14:23:20 Datadog Tracer v1.51.0 ERROR: Loading features: parse "http://$%!B(MISSING)DD_AGENT_HOST%!D(MISSING):8126/info": invalid URL escape "%!B(MISSING)" (occurred: 03 Jul 23 14:22 UTC)
```

I suspect [the tracer version](https://github.com/DataDog/dd-trace-go/releases/tag/v1.51.0) to be the culprit 

### What version of Traefik are you using?

v2.10.3

### What is your environment & configuration?

Helm configuration for the datadog tracing:

```yaml
traefik:
  tracing:
    datadog:
      localAgentHostPort: "${DD_AGENT_HOST}:8126"
  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
```

**Comment by juanwolf** [comment]
@ldez I don't believe this issue belongs to the helm chart repo as we are able to send traces correctly using the latest version of this chart but deploying traefik `v2.8.8`.

The error only appear once we upgrade to v2.10.3 which I believe has been introduced by upgrading the datadog tracing library to `v1.51.0` (which is flagged [as introducing a regression]( https://github.com/DataDog/dd-trace-go/releases/tag/v1.51.0)) in `v2.10.2` of traefik. I will deploy `v2.10.1` to confirm this.

**Comment by ldez** [comment]
Hello,

The default value of `localAgentHostPort` is based on env vars:

https://github.com/traefik/traefik/blob/8a68ece2cc9476031548453126ef60e4e687d73a/pkg/tracing/datadog/datadog.go#L33-L46

and after the evaluation as an URL inside the tracer option:
https://github.com/traefik/traefik/blob/8a68ece2cc9476031548453126ef60e4e687d73a/pkg/tracing/datadog/datadog.go#L64

but as you are defining `localAgentHostPort` the default value is ignored and the value of the configuration is used.
```yml
traefik:
  tracing:
    datadog:
      localAgentHostPort: "${DD_AGENT_HOST}:8126"
```

This field (`localAgentHostPort`) is not a template so the string value is used without any evaluation.

> parse "http://$%!B(MISSING)DD_AGENT_HOST%!D(MISSING):8126/info"

https://github.com/DataDog/dd-trace-go/blob/2c7a8f4ed7e4ba2fca3ca838b6b6f5e48b049c7b/ddtrace/tracer/option.go#L450-L454

https://github.com/DataDog/dd-trace-go/blob/358307e1d1402c2c144665827dda25d424fd4ca6/ddtrace/tracer/option.go#L241-L246

For me, it's not related to `dd-trace-go`.
