### ISSUE TITLE
Service specific annotations

### ISSUE THREAD

**Issue by ichbestimmtnicht** [traefik/traefik-helm-chart#887]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Prep:
I searched the internet (Issues/Forum) and investigated the helm chart directly.

Context:
We are using Traefik as an IngressController on AWS-EKS and want to declarativly expose udp entrypoints with the help of external-dns. For that we need to add the annotation with the target domain to the specific entrypoint-service e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: myfancydomain.com
[...]
```

Workaround possible:
yes

Implementation idea:
ports.[x].annotations could be introduced.

**Comment by mloiseleur** [comment]
It seems it's possible with `service.annoations`, for instance this values file:

```yaml
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: myfancydomain.com
```

produce this `Service`, according to `helm template`:
```yaml
---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
[...]
  annotations:
    external-dns.alpha.kubernetes.io/hostname: myfancydomain.com
```

Does it answer to your need ? 
If yes, I invite you to submit a PR with a complete EXAMPLE on `external-dns`.

**Comment by ichbestimmtnicht** [comment]
This would add the annotation to all services created right? That is not the desired behavior.

**Comment by ichbestimmtnicht** [comment]
So I am opening a PR that allows this configuration:
```yaml
ports:
  myUdPport1:
    port: 1111
    hostPort: 1111
    expose: true
    exposedPort: 1111
    protocol: UDP
    annotations:
      external-dns.alpha.kubernetes.io/hostname: first.myfancydomain.com
  myUdPport2:
    port: 2222
    hostPort: 2222
    expose: true
    exposedPort: 2222
    protocol: UDP
    annotations:
      external-dns.alpha.kubernetes.io/hostname: second.myfancydomain.com
```
