### ISSUE TITLE
Using Vault as a certificates resolver

### ISSUE THREAD

**Issue by benjamin-altays** [traefik/traefik-helm-chart#918]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.2.1

### What version of Traefik are you using?

2.9.10

### What did you do?

I added a HelmChartConfig like that :
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    certResolvers:
      vault:
        url: "http://vault.example.com"
        auth:
          token: "my-secret-token"
        namespace: "ns"
        enginePath: "pki_int"
        role: "example-dot-com"
```
At first I tried with the yaml configuration file from : https://doc.traefik.io/traefik-enterprise/tls/vault-pki/ and used **certificatesResolvers**, traefik was starting but no provider Vault added
After I found your doc : https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-traefik-native-lets-encrypt-integration-without-cert-manager and tried **certResolvers**

### What did you see instead?

When using **certificatesResolvers** nothing happend
When using **certResolvers** I have log like this one : 
`2023/09/06 09:50:39 command traefik error: failed to decode configuration from flags: field not found, node: enginePath`
It seem it doesn't recognize vault configuration

### What is your environment & configuration?

I'am on rancher/k3s, I installed traefik Ingress with the cluster
