### ISSUE TITLE
HTTP3 is not exposing UDP port

### ISSUE THREAD

**Issue by nf404** [traefik/traefik-helm-chart#929]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

24.0.0

### What version of Traefik are you using?

2.10.4

### What did you do?

```bash
helm upgrade \
  --install traefik traefik \
  --repo https://traefik.github.io/charts \
  --namespace traefik --create-namespace \
  --set deployment.kind=DaemonSet \
  --set ports.web.redirectTo=websecure \
  --set ports.websecure.http3.enabled=true \
  --set ports.websecure.http3.advertisedPort=443 \
  --set ports.websecure.tls.enabled=true \
  --set service.ipFamilyPolicy=PreferDualStack \
  --set "service.ipFamilies={IPv4,IPv6}" \
  --set providers.kubernetesCRD.allowCrossNamespace=true
```

### What did you see instead?

In service traefik port 443/UDP is not created
In endpoint traefik port websecure-http3 is not created
In pods traefik port websecure-http3 is not created

### What is your environment & configuration?

K8S v1.28.2
metallb v0.13.10 in L2 mode

### Additional Information

```shell
After adding this ports manually everything become work.
```

**Comment by mschneider82** [comment]
i got the same problem, but when i render it with ```helm template --debug .``` i can see the udp lines in the Service definition.
So i deleted the already existing `Service` in the cluster so helm has to set it up again and get an error message:

```: may not contain more than 1 protocol when type is 'LoadBalancer'```

**Comment by mloiseleur** [comment]
The root cause is known bug on Kubernetes, see https://github.com/kubernetes/kubernetes/issues/105610

This chart provide [example on http3](https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md#use-http3) and also detail if one should [choose mixedprotocol or not in the readme](https://github.com/traefik/traefik-helm-chart#upgrading-from-17x-to-18x).

Feel free to submit a PR if you see a way to improve the situation on this complex matter.

**Comment by mloiseleur** [comment]
When trying to generate YAML with this command:

```shell
helm template traefik traefik/traefik
  --set deployment.kind=DaemonSet \
  --set ports.web.redirectTo=websecure \
  --set ports.websecure.http3.enabled=true \
  --set ports.websecure.http3.advertisedPort=443 \
  --set ports.websecure.tls.enabled=true \
  --set service.ipFamilyPolicy=PreferDualStack \
  --set "service.ipFamilies={IPv4,IPv6}" \
  --set providers.kubernetesCRD.allowCrossNamespace=true
```
It generates this `Service`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
    helm.sh/chart: traefik-24.0.0
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv4
  - IPv6
  ports:
  - port: 80
    name: "web"
    targetPort: web
    protocol: TCP
  - port: 443
    name: "websecure"
    targetPort: websecure
    protocol: TCP
  - port: 443
    name: "websecure-http3"
    targetPort: 8443
    protocol: UDP
```

It's a valid `Service` using _MixedProtocols_

**Comment by nf404** [comment]
@mloiseleur 
```bash
helm template traefik traefik/traefik \
  --set deployment.kind=DaemonSet \
  --set ports.web.redirectTo=websecure \
  --set ports.websecure.http3.enabled=true \
  --set ports.websecure.http3.advertisedPort=443 \
  --set ports.websecure.tls.enabled=true \
  --set service.ipFamilyPolicy=PreferDualStack \
  --set "service.ipFamilies={IPv4,IPv6}" \
  --set providers.kubernetesCRD.allowCrossNamespace=true
```

Looks like there is no port websecure-http3 in DeamonSet. So it not applied in Service 
```yaml
# Source: traefik/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: default
#....
        ports:
        - name: "metrics"
          containerPort: 9100
          protocol: "TCP"
        - name: "traefik"
          containerPort: 9000
          protocol: "TCP"
        - name: "web"
          containerPort: 8000
          protocol: "TCP"
        - name: "websecure"
          containerPort: 8443
          protocol: "TCP"
```
