### ISSUE TITLE
Add file provider from a ConfigMap

### ISSUE THREAD

**Issue by ebuildy** [traefik/traefik-helm-chart#936]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## Feature

Add a value field `extraStaticConfig` to add extra static configuration. 

Under the hood:

- Create a configMap

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  config.yml: |
    {{ .Values.extraStaticConfig | nindent 2 }}
```

- Mount the configMap
- Tell traefik to use the file `- "--providers.file.filename=/mnt/traefik/config/config.yml"`

## Use case

Better TLS store configuration in case of multiple Traefik instances

## Related

https://github.com/traefik/traefik-helm-chart/issues/69

I can do the PR ASAP if the feature is accepted!
