### ISSUE TITLE
Helm chart version is not bumped after updating app version from 2.10.4 to 2.10.5

### ISSUE THREAD

**Issue by grglzrv** [traefik/traefik-helm-chart#945]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

24.0.0

### What version of Traefik are you using?

v2.10.4

### What did you do?

I've upgraded to 24.0.0 but my Traefik version is still 2.10.4 version in master branch for helm chart version 24.0.0 appversion is 2.10.5

### What did you see instead?

I expect traefik version to be 2.10.5 but the helm chart version is not bumped to 24.0.1 cuz i saw there is a tag with 24.0.0 and app version 2.10.4, after the build of new traefik version 2.10.5 helm chart is not bumped from 24.0.0 to 24.0.1

### What is your environment & configuration?

```yaml

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 24.0.0
  interval: 1m0s
  maxHistory: 3
  install:
    crds: CreateReplace
    disableWait: true
  upgrade:
    crds: CreateReplace
    disableWait: true
    force: true
  rollback:
    disableWait: true
  values:
    additionalArguments:
    - --providers.kubernetesingress.allowexternalnameservices
    - --providers.kubernetescrd.allowexternalnameservices
    env:
    - name: CLOUDFLARE_EMAIL
      valueFrom:
        secretKeyRef:
          key: email
          name: cloudflare-api-credentials
    - name: CLOUDFLARE_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: apiKey
          name: cloudflare-api-credentials
    - name: CLOUDFLARE_ZONE_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: apiKey
          name: cloudflare-api-credentials
    ingressRoute:
      dashboard:
        enabled: false
    persistence:
      enabled: true
      path: /certs
      size: 128Mi
    ports:
      web:
        redirectTo: websecure

```

```shell
n/a
```
