### ISSUE TITLE
default certificate from secret is not used

### ISSUE THREAD

**Issue by vpkdyna** [traefik/traefik-helm-chart#952]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

25.0.0

### What version of Traefik are you using?

v2.10.5

### What did you do?

Set the values that should change the default cert. I would expect this certificate to be used when no other certificate matches. 
```
        tlsStore:
          default:
            defaultCertificate:
              secretName: mysecret
```

### What did you see instead?

When visiting the IP adress of the NLB traefik uses I get 
TRAEFIK DEFAULT CERT instead of the certificate in the secret. 

### What is your environment & configuration?

```
        logs:
          access:
   ``         enabled: true
            format: json
            fields:
              general:
                defaultmode: keep
              headers:
                defaultmode: keep        
                names:
                  Authorization: drop
        tlsOptions:
          default:
            sniStrict: true
            preferServerCipherSuites: true
        tlsStore:
          default:
            defaultCertificate:
              secretName: mysecret
        deployment:
          replicas: 2        
          lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "sleep 40"]
        podDisruptionBudget:
          enabled: true 
          maxUnavailable: 1
        globalArguments: {}
        additionalArguments:
          - "--entryPoints.web.proxyProtocol.trustedIPs=0.0.0.0/0"
          - "--entryPoints.websecure.proxyProtocol.trustedIPs=0.0.0.0/0"
          - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik-test/traefik-test"          
          - "--providers.kubernetescrd.labelselector=traffic-type=test"
          - "--providers.kubernetesingress.ingressclass=test"
          - "--serverstransport.insecureskipverify=true"
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true
            ingressEndpoint:
              publishedService: "traefik-test/traefik-test"
            publishedService:
              enabled: true

        ports:
          traefik:
            port: 9000
            expose: false
            protocol: TCP
          web:
            port: 8000
            expose: true
            exposedPort: 80
            protocol: TCP

          websecure:
            port: 8443
            expose: true
            exposedPort: 443
            protocol: TCP
            tls:
              enabled: true
              options: "default"

        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
```
The tlsstore gets created. 
```
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-test
spec:
  defaultCertificate:
    secretName: mysecret
```

### Additional Information

```shell
The certificate secret also exists and is in fact used by ingress where it works.
```
