### ISSUE TITLE
Allow extending env value more easily

### ISSUE THREAD

**Issue by jnoordsij** [traefik/traefik-helm-chart#958]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently the `env` key in the values file is a list. This means that it is not easily extendable, since Helm will overwrite list values when set, rather than merging them. This means that when one wants to pass an additional env variable, e.g. `TZ=US/Alaska`, the entire list contained in this repo has to be copied and passed with it, or else will get lost:
```
  env:
    # This has to be copied (current values.yaml content)
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    # Custom additions can then be placed afterwards
    - name: TZ
      value: US/Alaska
```

It would be nice to have another value type, e.g. key-based, for the environment, so Helm can properly merge it. This can then be parsed into the correct format within the relevant templates.

Suggested implementation: the approach on the following StackExchange question might be a good place to start:
https://stackoverflow.com/questions/59394422/helm-charts-with-multiple-lists-in-multiple-values-files
