### ISSUE TITLE
Allow setting (access) log timezone directly

### ISSUE THREAD

**Issue by jnoordsij** [traefik/traefik-helm-chart#959]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently, to allow setting a custom timezone for (access) logs, one needs to alter the following chart values (see also https://doc.traefik.io/traefik/observability/access-logs/#time-zones):
1. Pass an additional env parameter `TZ=US/Alaska`, i.e. in terms of values (see also #958):
```yaml
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: TZ
      value: US/Alaska
```
2. Drop the `StartUTC` field, i.e. in terms of values:
```yaml
  logs:
    access:
      fields:
        general:
          names:
            # see https://doc.traefik.io/traefik/observability/access-logs/#time-zones
            StartUTC: drop
```

It would be nice to add a new chart value, e.g. `timezone`, that would both of these things at once without further changes.
