### ISSUE TITLE
tls: failed to verify certificate: x509: certificate is valid for X and not for X

### ISSUE THREAD

**Issue by AyluinReymaer** [traefik/traefik-helm-chart#977]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

Not sure how to check. Its the default traefik installation that came with k3s version v1.26.10+k3s2

### What version of Traefik are you using?

rancher/mirrored-library-traefik:2.10.5

### What did you do?

Setup vaultwarden with a TLS certificate:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden.example.com
  namespace: homelab
spec:
  secretName: tls-traefik-vaultwarden.example.com
  issuerRef:
    name: vault-traefik-issuer
  commonName: vaultwarden.example.com
  dnsNames:
    - localhost
    - databases-vaultwarden
    - databases-vaultwarden.homelab
    - databases-vaultwarden.homelab.svc
    - databases-vaultwarden.homelab.svc.cluster.local
    - vaultwarden.example.com
  ipAddresses:
    - 127.0.0.1
    - 10.0.1.4
    - 192.168.1.113
```

Setup traefik with a root CA certificate (same root ca as the TLS cert Vaultwarden is using) with `--serversTransport.rootCAs=/certs/tls.crt`.
More details about the traefik config on the section: **What is your environment & configuration?**

Create a Service in k3s and an IngressRoute pointing to the service with https scheme. (My ingressroute is pointing https to port 80 as I had forgotten to change the port in vaultwarden. Please consider for now this port as https. Will change this later):

```yaml
apiVersion: v1
kind: Service
metadata:
  name: databases-vaultwarden
  namespace: homelab
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-homelab-databases-vaultwarden
  ports:
      # I know this port is for HTTP.
      # I forgot to change the port in VaultWarden itself so it is currently using this port for HTTPS.
      # Will change later.
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: homelab
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vaultwarden.example.com`)
    services:
    - name: databases-vaultwarden
      port: 80
      scheme: https
  tls:
    secretName: tls-traefik-vaultwarden.example.com
```

### What did you see instead?

```
time="2023-12-06T15:38:30Z" level=debug msg="'500 Internal Server Error' caused by: tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 10.0.1.4, 192.168.1.113, not 10.42.2.94"
2023-12-06T15:38:30.192362442Z 10.42.1.0 - - [06/Dec/2023:15:38:30 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 1289 "homelab-vaultwarden-b3c3ecabf5fae61de16b@kubernetescrd" "https://10.42.2.94:80" 2ms
time="2023-12-06T15:38:30Z" level=debug msg="'500 Internal Server Error' caused by: tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, 10.0.1.4, 192.168.1.113, not 10.42.2.94"
2023-12-06T15:38:30.201955374Z 10.42.1.0 - - [06/Dec/2023:15:38:30 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 1290 "homelab-vaultwarden-b3c3ecabf5fae61de16b@kubernetescrd" "https://10.42.2.94:80" 1ms
```

I was expecting to see traefik connect to the service via the service hostname `databases-vaultwarden` and not via the POD's IP Address. As the POD's IP Address is dynamic, I cannot include it in the TLS certificate's SANs.

I know I can just skip TLS verification, however, I would like to create a setup without relying on this insecure way of doing things.

### What is your environment & configuration?

Using k3s in a Debian OS.

Using the default traefik installation that came with k3s version v1.26.10+k3s2.

Created the following HelmChartConfig:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
    ingressRoute:
      dashboard:
        entryPoints: ["websecure"]
        matchRule: Host(`traefik.example.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    globalArguments:
      - "--global.checknewversion"
      - "--serversTransport.rootCAs=/certs/tls.crt"
    volumes:
      - name: tls-homelab-ca
        mountPath: "/certs"
        type: secret
    ports:
      web:
        redirectTo:
          port: websecure
```

### Additional Information

```shell
I checked for past issues and I found one that had the same issue, but the issue was closed due to the op using Traefik V1 and was advised to upgrade to V2:

https://github.com/traefik/traefik/issues/4227
```

**Comment by mloiseleur** [comment]
Hello @AyluinReymaer,

For configuration issues, users can share and learn from each other on the [community forum](https://community.traefik.io/).

If you want to configure TLS between Traefik Proxy and the backend, you will probably be interested in [ServersTransports](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-serverstransport) CRD.

I close this issue, since this repository is dedicated to issues related to Helm Chart.

Thanks for your understanding,

**Comment by interlock** [comment]
@AyluinReymaer  I would love to follow up this. Do you have a link to a community forum post or resolution. I am  experiencing something similar with a docker swarm cluster.

**Comment by AyluinReymaer** [comment]
Hey @interlock ,

I followed the solution provided in this thread to use [ServersTransports](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-serverstransport) CRD.

The schema is already in that link but a basic example is like this (this example is also in the doc above. Just changed the serverstransport to use rootCAsSecrets instead of insecureSkipVerify):

``` yaml
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: mytransport
  namespace: default
spec:
  serverName: example.org
  rootCAsSecrets:
    - secret containing ca.crt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: testroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`example.com`)
    kind: Rule
    services:
    - name: whoami
      port: 80
      serversTransport: mytransport
```

The key here is to create a ServersTransport with your required config and then link it to the IngressRoute in the serversTransport property.

Both need to be in the same namespace btw.
