### ISSUE TITLE
Helm updates break HTTP3 / HTTPS

### ISSUE THREAD

**Issue by ananace** [traefik/traefik-helm-chart#982]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

26.0.0

### What version of Traefik are you using?

2.10.6

### What did you do?

Installed the Helm chart with;
```yaml
ports:
  websecure:
    http3:
      enabled: true
      advertisedPort: 443
```

This results in a Deployment configured as;
```yaml
# ...
         ports:
# ...
         - containerPort: 8443
           name: websecure
           protocol: TCP
         - containerPort: 8443
           name: websecure-http3
           protocol: UDP
```

And a service like;
```yaml
# ...
  ports:
# ...
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: websecure-http3
    port: 443
    protocol: UDP
    targetPort: websecure-http3
```

### What did you see instead?

This configuration unfortunately seems to run into https://github.com/kubernetes/kubernetes/issues/105610 on `helm upgrade`s, causing the two ports to merge into one - with the first websecure winning and removing the UDP port from existence.

The resulting deployment looks like;
```yaml
# ...
        ports:
# ...
        - containerPort: 8000
          name: web
          protocol: TCP
        - containerPort: 8443
          name: websecure
          protocol: TCP
```

And the service ends up as;
```yaml
# ...
  ports:
# ...
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: websecure-http3    
    port: 443
    protocol: UDP
    targetPort: websecure-http3
```

This causes the incoming service traffic to fail as there's no `websecure-http3` port to reference

### What is your environment & configuration?

Bare-metal Kubernetes.
Traefik installed from Helm chart using FluxCD.
```
helm-controller: v0.31.1
kustomize-controller: v0.35.0
notification-controller: v0.33.0
source-controller: v0.36.0
```

### Additional Information

```shell
To keep the deployment working for now, I've added a post-renderer which replaces the service definition for the HTTP3 port to instead point directly to the port number
```
