### ISSUE TITLE
Cannot overwrite table with non table for experimental.plugins

### ISSUE THREAD

**Issue by mstimvol** [traefik/traefik-helm-chart#987]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

25.0.0

### What version of Traefik are you using?

2.10.5

### What did you do?

I ran `helm upgrade traefik -n traefik traefik/traefik --reuse-values --set="providers.file.enabled=false" --set="experimental.plugins={}" --dry-run`.

### What did you see instead?

After running the command above, I'm getting the following error:

```
coalesce.go:220: warning: cannot overwrite table with non table for traefik.experimental.plugins (map[enabled:false])
Error: UPGRADE FAILED: execution error at (traefik/templates/deployment.yaml:21:6): ERROR: .Values.experimental.plugins should be a map ([]interface {} provided) !
```

### What is your environment & configuration?

Up to now I was simply using the default setup (simply done by running `helm upgrade --install --create-namespace --namespace=traefik traefik traefik/traefik`). When I run `helm get values traefik -n traefik` it returns the following:

```
USER-SUPPLIED VALUES:
deployment:
  replicas: 2
ingressRoute:
  dashboard:
    enabled: false
logs:
  access:
    enabled: 1
  general:
    level: DEBUG
```

- Kubernetes Version: 1.26.1
