### ISSUE TITLE
initContainer does not set permissions

### ISSUE THREAD

**Issue by Hr46ph** [traefik/traefik-helm-chart#989]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

traefik-26.0.0

### What version of Traefik are you using?

v2.10.6

### What did you do?

Follow the instructions to install traefik with an init container to set permisisons for acme.json.

I run on a Talos cluster v1.6.1 with OpenEBS Jiva as explained here:
https://www.talos.dev/v1.6/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/

Specifically for installing Traefik:
`helm show values traefik/traefik > custom-values.yaml`
I set:
```
additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.email=my-issuer@domain.net"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
```
I set:
```
ports:
...
    redirectTo:
      port: websecure
```
I set persistence:
```
persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /data
  annotations: {}
```
I enable init-container:
```
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65532
        runAsUser: 65532
      volumeMounts:
        - name: data
          mountPath: /data
```
I create namespace:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
```
helm upgrade --install traefik traefik/traefik --values custom-values.yaml -n traefik

Pods get created, pv's and pvc's but this pod crashes:
`traefik          traefik-5bbd794b64-5l6cf                                          0/1     Init:CrashLoopBackOff`

### What did you see instead?

`kubectl logs -n traefik pods/traefik-5bbd794b64-5l6cf`
```
Defaulted container "traefik" out of: traefik, volume-permissions (init)
Error from server (BadRequest): container "traefik" in pod "traefik-5bbd794b64-5l6cf" is waiting to start: PodInitializing
```
Not sure how much info is relevant, but:
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned traefik/traefik-5bbd794b64-5l6cf to worker-01
  Normal   Pulled     13m                   kubelet            Successfully pulled image "busybox:latest" in 765ms (765ms including waiting)
  Normal   Pulled     13m                   kubelet            Successfully pulled image "busybox:latest" in 732ms (732ms including waiting)
  Normal   Pulled     13m                   kubelet            Successfully pulled image "busybox:latest" in 682ms (682ms including waiting)
  Normal   Created    12m (x4 over 13m)     kubelet            Created container volume-permissions
  Normal   Started    12m (x4 over 13m)     kubelet            Started container volume-permissions
  Normal   Pulled     12m                   kubelet            Successfully pulled image "busybox:latest" in 714ms (714ms including waiting)
  Normal   Pulling    12m (x5 over 13m)     kubelet            Pulling image "busybox:latest"
  Normal   Pulled     11m                   kubelet            Successfully pulled image "busybox:latest" in 742ms (743ms including waiting)
  Warning  BackOff    3m19s (x48 over 13m)  kubelet            Back-off restarting failed container volume-permissions in pod traefik-5bbd794b64-5l6cf_traefik(fea5c5db-340f-4c7a-b335-2dde3fa62b38)
```

### What is your environment & configuration?

Talos cluster v1.6.1 with OpenEBS Jiva
